@extends('layouts.app')
@section('title','Employer Registration — Ascendia')
@push('styles')<style>.er-wrap{padding:48px 16px 70px;background:#f6f8fc}.er-card{width:min(900px,100%);margin:auto;padding:34px;border:1px solid #dbe3ef;border-radius:18px;background:#fff;box-shadow:0 18px 50px #17233c14}.er-card h1{margin:0 0 8px}.er-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.field.full{grid-column:1/-1}.field label{display:block;margin-bottom:7px;font-weight:700}.req{color:#dc2626}.opt{color:#64748b;font-size:12px}.field input,.field select{width:100%;height:48px;padding:0 13px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.phone-row{display:grid;grid-template-columns:205px 1fr auto;gap:8px}.otp-panel{display:none;margin-top:10px;padding:12px;border:1px solid #bfdbfe;border-radius:10px;background:#eff6ff}.otp-panel.show{display:grid;grid-template-columns:1fr auto;gap:8px}.phone-status{margin-top:8px;font-weight:750}.help{margin-top:18px;padding:13px;border-radius:9px;background:#f8fafc;color:#64748b;font-size:13px}@media(max-width:760px){.er-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.phone-row{grid-template-columns:1fr}.er-card{padding:22px}}</style>@endpush
@section('content')<main class="er-wrap"><form method="post" action="{{route('employer.register.store')}}" class="er-card">@csrf<h1>Create an employer account</h1><p class="text-secondary mb-4">Register the company and its authorized HR contact. Required fields are marked <span class="req">*</span>.</p>
@if($errors->any())<div class="alert alert-danger"><strong>Please correct the following:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<div class="er-grid"><div class="field full"><label>Company name <span class="req">*</span></label><input name="company_name" value="{{old('company_name')}}" required maxlength="150" placeholder="Example Technologies Pvt. Ltd."></div>
<div class="field"><label>HR first name <span class="req">*</span></label><input name="first_name" value="{{old('first_name')}}" required maxlength="80"></div><div class="field"><label>HR last name <span class="req">*</span></label><input name="last_name" value="{{old('last_name')}}" required maxlength="80"></div>
<div class="field full"><label>Company phone number <span class="req">*</span></label><div class="phone-row"><select name="phone_country_code" id="phone_country_code" required>@foreach($countryCodes as $code=>$label)<option value="{{$code}}" @selected(old('phone_country_code','+91')===$code)>{{$label}}</option>@endforeach</select><input name="company_phone" id="company_phone" value="{{old('company_phone')}}" required inputmode="numeric" maxlength="15" placeholder="10-digit company number"><button class="btn btn-outline-primary" type="button" id="send-phone-code">Verify phone</button></div><div class="otp-panel" id="otp-panel"><input id="phone_code" inputmode="numeric" maxlength="6" placeholder="Enter 6-digit OTP"><button class="btn btn-primary" type="button" id="verify-phone-code">Confirm OTP</button></div><div class="phone-status" id="phone-status"></div><input type="hidden" name="phone_verification_token" id="phone_verification_token"></div>
<div class="field"><label>Company legal type <span class="req">*</span></label><select name="organization_type" required><option value="">Select legal type</option>@foreach(['private_limited'=>'Private Limited (Pvt. Ltd.)','public_limited'=>'Public Limited','llp'=>'Limited Liability Partnership (LLP)','partnership'=>'Partnership','sole_proprietorship'=>'Sole Proprietorship','government'=>'Government','nonprofit'=>'Nonprofit','other'=>'Other'] as $value=>$label)<option value="{{$value}}" @selected(old('organization_type')===$value)>{{$label}}</option>@endforeach</select></div>
<div class="field"><label>Primary business <span class="opt">(optional)</span></label><select name="business_type"><option value="">Select business type</option>@foreach(['services','consulting','finance','brokerage','commission','software','hardware','mechanical','chemical','other'] as $value)<option value="{{$value}}" @selected(old('business_type')===$value)>{{ucfirst($value)}}</option>@endforeach</select></div>
<div class="field"><label>Company email <span class="req">*</span></label><input type="email" name="company_email" value="{{old('company_email')}}" required placeholder="contact@company.com"></div><div class="field"><label>HR job-posting email <span class="req">*</span></label><input type="email" name="email" value="{{old('email')}}" required placeholder="recruiter@company.com"></div>
<div class="field"><label>Company website <span class="opt">(optional)</span></label><input type="url" name="website" value="{{old('website')}}" placeholder="https://company.com"></div><div class="field"><label>HR designation <span class="opt">(optional)</span></label><input name="designation" value="{{old('designation')}}" maxlength="100" placeholder="Talent Acquisition Manager"></div>
<div class="field"><label>Password <span class="req">*</span></label><input type="password" name="password" required minlength="8"></div><div class="field"><label>Confirm password <span class="req">*</span></label><input type="password" name="password_confirmation" required minlength="8"></div>
<div class="field full"><button class="btn btn-primary w-100 py-3" type="submit">Create company and send email verification code</button><a class="btn btn-outline-primary w-100 mt-2" href="{{route('employer.login')}}">Already registered? HR Login</a></div></div><p class="help">Local testing: phone OTP and email OTP are both <strong>123456</strong>.</p></form></main>@endsection
@push('scripts')<script>(()=>{const csrf=document.querySelector('input[name="_token"]').value,send=document.querySelector('#send-phone-code'),verify=document.querySelector('#verify-phone-code'),panel=document.querySelector('#otp-panel'),status=document.querySelector('#phone-status'),token=document.querySelector('#phone_verification_token'),phone=document.querySelector('#company_phone'),country=document.querySelector('#phone_country_code');async function post(url,data){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify(data)}),json=await response.json();if(!response.ok)throw new Error(json.message||Object.values(json.errors||{})[0]?.[0]||'Verification failed.');return json}send.onclick=async()=>{status.textContent='';token.value='';send.disabled=true;try{const result=await post('{{route('employer.phone.send')}}',{phone_country_code:country.value,company_phone:phone.value});panel.classList.add('show');status.style.color='#1d4ed8';status.textContent=result.message}catch(error){status.style.color='#b91c1c';status.textContent=error.message}finally{send.disabled=false}};verify.onclick=async()=>{verify.disabled=true;try{const result=await post('{{route('employer.phone.verify')}}',{phone_country_code:country.value,company_phone:phone.value,code:document.querySelector('#phone_code').value});token.value=result.verification_token;status.style.color='#15803d';status.textContent='✓ '+result.message;panel.classList.remove('show');phone.readOnly=true;country.disabled=true;const mirror=document.createElement('input');mirror.type='hidden';mirror.name='phone_country_code';mirror.value=country.value;country.after(mirror)}catch(error){status.style.color='#b91c1c';status.textContent=error.message}finally{verify.disabled=false}};phone.oninput=()=>{token.value='';status.textContent=''}})();</script>@endpush
