@extends('layouts.app')
@section('title','Employer Registration — Ascendia')
@push('styles')<style>
.er-wrap{min-height:calc(100vh - 84px);display:grid;grid-template-columns:minmax(360px,.82fr) minmax(0,1.18fr);background:#f5f8fd}
.er-story{position:relative;overflow:hidden;padding:clamp(48px,6vw,96px);background:linear-gradient(145deg,#0e1e39 0%,#173d78 72%,#2459a8 100%);color:#fff;display:flex;flex-direction:column;justify-content:center}
.er-story:before,.er-story:after{content:"";position:absolute;border-radius:50%;background:#60a5fa18}.er-story:before{width:380px;height:380px;right:-180px;top:-140px}.er-story:after{width:260px;height:260px;left:-120px;bottom:-100px}
.er-story-content{position:relative;z-index:1;max-width:620px}.er-eyebrow{display:inline-flex;padding:8px 13px;border:1px solid #93c5fd55;border-radius:999px;background:#ffffff12;color:#bfdbfe;font-weight:750;font-size:13px;letter-spacing:.04em;text-transform:uppercase}
.er-story h2{margin:24px 0 18px;color:#fff;font-size:clamp(40px,4.4vw,68px);line-height:1.04;letter-spacing:-.04em}.er-story p{max-width:590px;margin:0;color:#d4e2f6;font-size:18px;line-height:1.7}
.er-benefits{display:grid;gap:15px;margin-top:30px}.er-benefits span{display:flex;align-items:center;font-weight:650}.er-benefits span:before{content:"\2713";display:grid;place-items:center;flex:0 0 28px;width:28px;height:28px;margin-right:12px;border-radius:50%;background:#2f73ed;color:#fff}
.er-form-side{display:flex;align-items:flex-start;justify-content:center;padding:48px clamp(20px,4vw,64px) 70px;background:radial-gradient(circle at 100% 0,#dbeafe 0,transparent 33%),#f7f9fd}
.er-card{width:min(900px,100%);margin:0;padding:34px;border:1px solid #d6e1f0;border-radius:18px;background:#fff;box-shadow:0 22px 60px #13294b18}.er-card h1{margin:0 0 8px}.er-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.field.full{grid-column:1/-1}.field label{display:block;margin-bottom:7px;font-weight:700}.req{color:#dc2626}.opt{color:#64748b;font-size:12px}.field input,.field select{width:100%;height:48px;padding:0 13px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.field input:focus,.field select:focus{border-color:#2563eb;box-shadow:0 0 0 3px #2563eb1f;outline:0}.phone-row{display:grid;grid-template-columns:205px 1fr auto;gap:8px}.otp-panel{display:none;margin-top:10px;padding:12px;border:1px solid #bfdbfe;border-radius:10px;background:#eff6ff}.otp-panel.show{display:grid;grid-template-columns:1fr auto;gap:8px}.phone-status{margin-top:8px;font-weight:750}.help{margin-top:18px;padding:13px;border-radius:9px;background:#f8fafc;color:#64748b;font-size:13px}
@media(max-width:1100px){.er-wrap{grid-template-columns:1fr}.er-story{min-height:430px;padding:70px clamp(24px,7vw,80px)}.er-form-side{padding-top:36px}}
@media(max-width:760px){.er-story{min-height:380px;padding:54px 24px}.er-story h2{font-size:40px}.er-story p{font-size:16px}.er-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.phone-row{grid-template-columns:1fr}.er-card{padding:22px}.er-form-side{padding:24px 14px 50px}}
</style>@endpush
@section('content')<main class="er-wrap"><section class="er-story" aria-label="Employer recruitment introduction"><div class="er-story-content"><span class="er-eyebrow">Employer workspace</span><h2>Find the Right Talent. Build a Stronger Team.</h2><p>Create your verified company profile, publish opportunities and manage candidates from one coordinated recruitment workspace.</p><div class="er-benefits"><span>Reach qualified candidates</span><span>Post and manage jobs in minutes</span><span>Track applications from one dashboard</span></div></div></section><section class="er-form-side"><form method="post" action="{{route('employer.register.store')}}" class="er-card">@csrf<h1>Create an employer account</h1><p class="text-secondary mb-4">Register the company and its authorized HR contact. Required fields are marked <span class="req">*</span>.</p>
@if($errors->any())<div class="alert alert-danger"><strong>Please correct the following:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<div class="er-grid"><div class="field full"><label>Company name <span class="req">*</span></label><input name="company_name" value="{{old('company_name')}}" required maxlength="150" placeholder="Example Technologies Pvt. Ltd."></div>
<div class="field"><label>HR first name <span class="req">*</span></label><input name="first_name" value="{{old('first_name')}}" required maxlength="80"></div><div class="field"><label>HR last name <span class="req">*</span></label><input name="last_name" value="{{old('last_name')}}" required maxlength="80"></div>
<div class="field full"><label>Company phone number <span class="req">*</span></label><div class="phone-row"><select name="phone_country_code" id="phone_country_code" required>@foreach($countryCodes as $code=>$label)<option value="{{$code}}" @selected(old('phone_country_code','+91')===$code)>{{$label}}</option>@endforeach</select><input name="company_phone" id="company_phone" value="{{old('company_phone')}}" required inputmode="numeric" maxlength="15" placeholder="10-digit company number"><button class="btn btn-outline-primary" type="button" id="send-phone-code">Verify phone</button></div><div class="otp-panel" id="otp-panel"><input id="phone_code" inputmode="numeric" maxlength="6" placeholder="Enter 6-digit OTP"><button class="btn btn-primary" type="button" id="verify-phone-code">Confirm OTP</button></div><div class="phone-status" id="phone-status"></div><input type="hidden" name="phone_verification_token" id="phone_verification_token"></div>
<div class="field"><label>Company legal type <span class="req">*</span></label><select name="organization_type" required><option value="">Select legal type</option>@foreach(['private_limited'=>'Private Limited (Pvt. Ltd.)','public_limited'=>'Public Limited','llp'=>'Limited Liability Partnership (LLP)','partnership'=>'Partnership','sole_proprietorship'=>'Sole Proprietorship','government'=>'Government','nonprofit'=>'Nonprofit','other'=>'Other'] as $value=>$label)<option value="{{$value}}" @selected(old('organization_type')===$value)>{{$label}}</option>@endforeach</select></div>
<div class="field"><label>Primary business <span class="opt">(optional)</span></label><select name="business_type"><option value="">Select business type</option>@foreach(['services','consulting','finance','brokerage','commission','software','hardware','mechanical','chemical','other'] as $value)<option value="{{$value}}" @selected(old('business_type')===$value)>{{ucfirst($value)}}</option>@endforeach</select></div>
<div class="field"><label>Company email <span class="req">*</span></label><input type="email" name="company_email" value="{{old('company_email')}}" required placeholder="contact@company.com"></div><div class="field"><label>HR job-posting email <span class="req">*</span></label><input type="email" name="email" value="{{old('email')}}" required placeholder="recruiter@company.com"></div>
<div class="field"><label>Company website <span class="opt">(optional)</span></label><input type="url" name="website" value="{{old('website')}}" placeholder="https://company.com"></div><div class="field"><label>HR designation <span class="opt">(optional)</span></label><input name="designation" value="{{old('designation')}}" maxlength="100" placeholder="Talent Acquisition Manager"></div>
<div class="field"><label>Password <span class="req">*</span></label><input type="password" name="password" required minlength="8"></div><div class="field"><label>Confirm password <span class="req">*</span></label><input type="password" name="password_confirmation" required minlength="8"></div>
<div class="field full"><button class="btn btn-primary w-100 py-3" type="submit">Create company and send email verification code</button><a class="btn btn-outline-primary w-100 mt-2" href="{{route('employer.login')}}">Already registered? HR Login</a></div></div><p class="help">Local testing: phone OTP and email OTP are both <strong>123456</strong>.</p></form></section></main>@endsection
@push('scripts')<script>(()=>{const csrf=document.querySelector('input[name="_token"]').value,send=document.querySelector('#send-phone-code'),verify=document.querySelector('#verify-phone-code'),panel=document.querySelector('#otp-panel'),status=document.querySelector('#phone-status'),token=document.querySelector('#phone_verification_token'),phone=document.querySelector('#company_phone'),country=document.querySelector('#phone_country_code');async function post(url,data){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify(data)}),json=await response.json();if(!response.ok)throw new Error(json.message||Object.values(json.errors||{})[0]?.[0]||'Verification failed.');return json}send.onclick=async()=>{status.textContent='';token.value='';send.disabled=true;try{const result=await post('{{route('employer.phone.send')}}',{phone_country_code:country.value,company_phone:phone.value});panel.classList.add('show');status.style.color='#1d4ed8';status.textContent=result.message}catch(error){status.style.color='#b91c1c';status.textContent=error.message}finally{send.disabled=false}};verify.onclick=async()=>{verify.disabled=true;try{const result=await post('{{route('employer.phone.verify')}}',{phone_country_code:country.value,company_phone:phone.value,code:document.querySelector('#phone_code').value});token.value=result.verification_token;status.style.color='#15803d';status.textContent='✓ '+result.message;panel.classList.remove('show');phone.readOnly=true;country.disabled=true;const mirror=document.createElement('input');mirror.type='hidden';mirror.name='phone_country_code';mirror.value=country.value;country.after(mirror)}catch(error){status.style.color='#b91c1c';status.textContent=error.message}finally{verify.disabled=false}};phone.oninput=()=>{token.value='';status.textContent=''}})();</script>@endpush
