@extends('layouts.app')
@section('title', 'For Loop in Programming — '.config('platform.name'))
@push('styles')
<style>
.loop-hero{padding:52px 20px;color:#fff;background:linear-gradient(125deg,#0f1f3b,#1d4ed8)}.wrap{width:min(1120px,calc(100% - 32px));margin:auto}.loop-hero a{color:#bfdbfe}.loop-hero h1{margin:20px 0 8px;font-size:clamp(36px,5vw,56px)}.updated{color:#dbeafe}.lesson-page{padding:42px 0 70px}.panel{margin-bottom:20px;padding:26px;border:1px solid #dbe4f0;border-radius:18px;background:#fff}.lead{font-size:18px;line-height:1.8;color:#475569}.code-title{display:flex;justify-content:space-between;padding:11px 15px;border-radius:12px 12px 0 0;background:#0f172a;color:#fff}.code{overflow:auto;margin:0;padding:20px;border-radius:0 0 12px 12px;background:#020617;color:#bfdbfe;font:14px/1.7 Consolas,monospace}.flow-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.diagram{padding:20px;border:1px solid #dbe4f0;border-radius:14px;background:#f8fafc}.node{padding:12px;border:2px solid #2563eb;border-radius:10px;background:#fff;text-align:center;font-weight:750}.body-node{padding:14px;border-radius:10px;background:#dbeafe;text-align:center}.arrow{text-align:center;color:#2563eb;font-size:21px;line-height:1.4}.notes{line-height:1.9}.types{display:grid;gap:18px}.type-card{padding:22px;border:1px solid #dbe4f0;border-radius:15px;background:#fff}.type-card h3{margin-top:0}.type-card p{color:#536079;line-height:1.7}.challenge{border-color:#93c5fd;background:#eff6ff}.quiz-options{display:grid;grid-template-columns:1fr 1fr;gap:10px}.answer{padding:13px;text-align:left;border:1px solid #cbd5e1;border-radius:10px;background:#fff}.answer.correct{border-color:#16a34a;background:#dcfce7}.answer.wrong{border-color:#dc2626;background:#fee2e2}.feedback{display:none;padding:12px;border-radius:9px}.feedback.show{display:block;background:#eff6ff}@media(max-width:760px){.flow-grid,.quiz-options{grid-template-columns:1fr}}
</style>
@endpush
@section('content')
@php($lesson=$lessons[0])
<section class="loop-hero"><div class="wrap"><a href="{{route('learning.track','dsa')}}">← Data Structures & Algorithms</a><h1>{{$lesson['title']}}</h1><p class="updated">Last updated: {{$lesson['updated_at']}}</p></div></section>
<main class="wrap lesson-page">
<section class="panel"><p class="lead">{{$lesson['summary']}}</p><ul class="notes"><li>Ideal when the iteration count is known in advance.</li><li>Useful for arrays, lists, sequences, number series, and repeatable tasks.</li></ul><div class="code-title"><strong>Java example</strong><span>Output: 1 2 3 4 5</span></div><pre class="code"><code>{{$lesson['code']}}</code></pre></section>
<section class="panel"><h2>Flow of a For Loop</h2><div class="flow-grid"><article class="diagram"><h3>Java, C, C++ and JavaScript</h3><div class="node">Initialization</div><div class="arrow">↓</div><div class="node">Condition true?</div><div class="arrow">Yes ↓ &nbsp; No → Exit</div><div class="body-node">Execute loop body</div><div class="arrow">↓</div><div class="node">Update counter</div><div class="arrow">↺ Check condition</div></article><article class="diagram"><h3>Python iterable loop</h3><div class="node">Is there a next item?</div><div class="arrow">Yes ↓ &nbsp; No → Exit</div><div class="node">Assign item to variable</div><div class="arrow">↓</div><div class="body-node">Execute loop body</div><div class="arrow">↺ Check next item</div></article></div><ul class="notes"><li><strong>Initialization</strong> establishes the starting value.</li><li><strong>Condition</strong> is evaluated before each conventional iteration.</li><li><strong>Update</strong> changes the counter after the body runs.</li><li>Python directly requests each next value from an iterable.</li></ul></section>
<section class="panel"><h2>Types of For Loops</h2><div class="types">@foreach($lesson['sections'] as $section)<article class="type-card"><h3>{{$loop->iteration}}. {{$section['title']}}</h3><p>{{$section['text']}}</p><pre class="code"><code>{{$section['code']}}</code></pre></article>@endforeach</div></section>
<section class="panel challenge"><h2>Hands-on challenge</h2><p>{{$lesson['task']}}</p></section>
<section class="panel quiz" data-answer="{{$lesson['answer']}}"><h2>Quick quiz</h2><p>Which statement is correct?</p><div class="quiz-options">@foreach($lesson['options'] as $option)<button type="button" class="answer" data-option="{{$loop->index}}"><strong>{{chr(65+$loop->index)}}.</strong> {{$option}}</button>@endforeach</div><p class="feedback" aria-live="polite"></p></section>
</main>
@endsection
@push('scripts')<script>(()=>{const quiz=document.querySelector('.quiz'),correct=Number(quiz.dataset.answer),feedback=quiz.querySelector('.feedback');quiz.querySelectorAll('.answer').forEach(button=>button.addEventListener('click',()=>{quiz.querySelectorAll('.answer').forEach(option=>{option.disabled=true;if(Number(option.dataset.option)===correct)option.classList.add('correct')});const ok=Number(button.dataset.option)===correct;if(!ok)button.classList.add('wrong');feedback.classList.add('show');feedback.textContent=(ok?'Correct. ':'Not quite. ')+@json($lesson['why'])}))})();</script>@endpush
