@extends('layouts.app')
@push('scripts')
<script>const moduleLessonCounts=@json(collect($track['topics'])->mapWithKeys(fn($topic,$topicSlug)=>[$topicSlug=>count($topic['questions'])]));document.querySelectorAll('.course-card.tutorial').forEach(card=>{const moduleSlug=card.getAttribute('href').split('/').filter(Boolean).pop(),count=moduleLessonCounts[moduleSlug]||0,action=card.querySelector('.course-action'),more=card.querySelector('.lesson-preview span:last-child');if(action)action.textContent=`Begin ${count} lessons →`;if(more)more.textContent=`+${Math.max(0,count-5)} more`})</script>
@endpush
@if($slug === 'spring-boot')
@push('scripts')
<script>document.querySelectorAll('.course-card.tutorial').forEach(card=>{const action=card.querySelector('.course-action'),more=card.querySelector('.lesson-preview span:last-child');if(action)action.textContent='Begin 10 lessons →';if(more)more.textContent='+5 more'})</script>
@endpush
@endif
@section('title',$track['title'].' — '.config('platform.name'))
@push('styles')<style>.course-hero{padding:58px 20px;background:radial-gradient(circle at 80% 15%,#7c3aed55,transparent 28%),#10213e;color:#fff}.course-wrap{width:min(1120px,calc(100% - 34px));margin:auto}.course-hero a{color:#bfdbfe}.course-hero h1{margin:22px 0 10px;font-size:clamp(36px,5vw,54px)}.course-stats{display:flex;gap:22px;margin-top:25px}.course-stats span{padding:9px 13px;border:1px solid #ffffff22;border-radius:999px;background:#ffffff10}.course-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;padding:42px 0 70px}.course-card{position:relative;overflow:hidden;padding:25px;border:1px solid #dfe6f0;border-radius:18px;background:#fff;color:#10213e;text-decoration:none;transition:.2s}.course-card:hover{transform:translateY(-5px);border-color:#7c3aed;box-shadow:0 16px 36px #5421b314}.course-card.tutorial{grid-column:1/-1;padding:32px;background:linear-gradient(125deg,#f5f0ff,#fff 60%)}.course-badge{display:inline-flex;padding:7px 11px;border-radius:999px;background:#ede9fe;color:#6d28d9;font-size:12px;font-weight:800}.course-card h2{margin:15px 0 8px}.course-card p{color:#64748b;line-height:1.65}.course-action{display:inline-flex;margin-top:15px;color:#6d28d9;font-weight:800}.lesson-preview{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.lesson-preview span{padding:7px 9px;border-radius:8px;background:#fff;border:1px solid #ddd6fe;font-size:12px}@media(max-width:700px){.course-grid{grid-template-columns:1fr}.course-card.tutorial{grid-column:auto}}</style>@endpush
@section('content')<section class="course-hero"><div class="course-wrap"><a href="{{route('learning.index')}}">← All learning paths</a><h1>{{$track['title']}}</h1><p>{{$track['description']}}</p><div class="course-stats"><span>{{count($track['topics'])}} modules</span><span>{{collect($track['topics'])->sum(fn($topic)=>count($topic['questions']))}} learning questions</span><span>Practical + quizzes</span></div></div></section><div class="course-wrap course-grid">@foreach($track['topics'] as $topicSlug=>$topic)<a class="course-card {{($topic['type']??null)==='tutorial'?'tutorial':''}}" href="{{route('learning.show',[$slug,$topicSlug])}}">@if(($topic['type']??null)==='tutorial')<span class="course-badge">START HERE · INTERACTIVE COURSE</span>@endif<h2>{{$topic['title']}}</h2><p>{{($topic['type']??null)==='tutorial'?'Learn by reading less, running examples, completing tasks, and answering a quiz after every lesson.':count($topic['questions']).' focused interview questions with implementation-oriented preparation.'}}</p>@if(($topic['type']??null)==='tutorial')<div class="lesson-preview">@foreach(array_slice($topic['questions'],0,5) as $question)<span>{{$question}}</span>@endforeach<span>+20 more</span></div>@endif<span class="course-action">{{($topic['type']??null)==='tutorial'?'Begin 25 lessons':'Open module'}} →</span></a>@endforeach</div>@endsection
