<?php
namespace Database\Seeders;use App\Models\NewsArticle;use App\Models\NewsCategory;use App\Models\NewsSource;use Illuminate\Database\Seeder;
class NewsIntelligenceSeeder extends Seeder{public function run():void{
$items=[['Technology','technology','💻'],['Software & AI','software-ai','🤖'],['Computer Science','computer-science','🧠'],['Mechanical & Manufacturing','mechanical-manufacturing','⚙️'],['Automobile & EV','automobile-ev','🚗'],['Steel & Metals','steel-metals','🏭'],['Energy & Green Energy','green-energy','🌱'],['Data Centers','data-centers','☁️'],['Finance & Fintech','finance-fintech','💳'],['Companies','companies','🏢'],['Jobs & Hiring','jobs-hiring','💼'],['Salary Trends','salary-trends','💰'],['Government & Policy','government-policy','🏛️'],['Career Intelligence','career-intelligence','🎓']];
foreach($items as $i=>$v)NewsCategory::updateOrCreate(['slug'=>$v[1]],['name'=>$v[0],'icon'=>$v[2],'color'=>'#1769ff','is_active'=>true,'sort_order'=>$i+1]);
$source=NewsSource::updateOrCreate(['name'=>'Ascendia Research'],['website'=>config('app.url'),'source_type'=>'editorial','is_active'=>true]);
NewsSource::updateOrCreate(['name'=>'GitHub Blog'],['website'=>'https://github.blog','feed_url'=>'https://github.blog/feed/','source_type'=>'rss','is_active'=>true]);
$articles=[
['software-ai','AI platforms are becoming critical developer infrastructure','Modern software teams increasingly depend on hosted AI services, making resilience an engineering requirement.','Teams should design API fallbacks, caching, queues, observability and multi-provider architecture.',['Backend Engineer','AI Engineer','Cloud Engineer'],['API Design','Queues','Caching','Observability']],
['mechanical-manufacturing','Manufacturing expansion creates multidisciplinary engineering careers','Large integrated automobile and tractor facilities connect manufacturing investment with production capacity and supply-chain growth.','Potential demand spans mechanical, production, electrical, robotics, automation, quality and supply-chain roles.',['Mechanical Engineer','Production Engineer','Quality Engineer'],['Automation','Robotics','Quality','Supply Chain']],
['automobile-ev','EV growth links policy, manufacturing and software','EV adoption depends on demand incentives alongside charging and testing infrastructure.','Career paths cover batteries, BMS, charging, motors, power electronics, ADAS and vehicle software.',['EV Engineer','Electrical Engineer','Embedded Engineer'],['Battery Management','Power Electronics','Embedded Systems']],
['data-centers','India AI infrastructure expands through new data-center investment','Hyperscale and AI-ready data centers combine cloud capacity, networking, energy, cooling and physical infrastructure.','Growth supports cloud, DevOps, network, security, electrical, mechanical and AI engineering careers.',['Cloud Engineer','DevOps Engineer','Network Engineer','Cyber Security Engineer'],['AWS','Azure','Kubernetes','Networking','Cyber Security']],
['steel-metals','Green steel partnerships reshape automotive supply chains','Lower-carbon automotive-grade steel connects metals producers, vehicle manufacturers and cleaner energy systems.','Engineers need metallurgy, quality, manufacturing-process and sustainability expertise.',['Metallurgy Engineer','Quality Engineer','Automobile Engineer'],['Metallurgy','Quality Systems','Green Manufacturing']],
['salary-trends','Technology combinations improve backend engineer market value','Salary intelligence should be tied to role, experience, company type, location, source and period—not presented as one universal number.','Laravel combined with Redis, Docker, AWS, microservices and system design can broaden backend opportunities.',['Backend Engineer','Laravel Developer'],['Laravel','Redis','Docker','AWS','Microservices','System Design']],
];
foreach($articles as $i=>$a){$category=NewsCategory::where('slug',$a[0])->first();NewsArticle::updateOrCreate(['source_url'=>config('app.url').'/latest/source/'.$a[0]],['category_id'=>$category->id,'source_id'=>$source->id,'title'=>$a[1],'slug'=>$a[0].'-career-intelligence','excerpt'=>$a[2],'summary'=>$a[2],'industry_impact'=>$a[3],'career_impact'=>$a[3],'roles'=>$a[4],'skills'=>$a[5],'relevance_score'=>95-$i,'career_impact_level'=>'high','is_featured'=>$i<3,'is_published'=>true,'published_at'=>now()->subMinutes($i)]);}
}}
