@php
$examples = [
 'gears'=>['Gears & transmission','Product hierarchy',['Automobile','Auto Components','Transmission','Gears'],[['Product','Gears','The component you want to understand'],['Processes to explore','Hobbing, grinding, inspection','Operations associated with making or checking the product'],['Roles to explore','Gear Hobbing Operator, Gear Grinding Operator, Quality Inspector','Use the dictionary to compare skills and recorded openings']]],
 'axle'=>['Axle & chassis','Product hierarchy',['Automobile','Chassis','Axle'],[['Product','Axle','A component category within the vehicle'],['Work to explore','Machining, assembly, inspection','Explore the operations mapped in the directory'],['Roles to explore','Assembly Operator, Machining Technician, Quality Inspector','Compare the tasks and employer requirements']]],
 'brakes'=>['Braking systems','Component family',['Brake Disc','Brake Caliper','Brake Pads'],[['System','Braking System','The larger system containing these components'],['Components','Disc, caliper and pads','Related parts, shown as siblings rather than a production sequence'],['Career exploration','Production, assembly and quality','Look at the process, then the responsible department']]],
 'foundry'=>['Foundry & casting','Example learning sequence',['Foundry','Sand Casting','Moulding & Core Making','Melting & Pouring','Fettling & Inspection'],[['Learn the process','Start with casting and its mapped operations','Use the sequence to organise your study; plant workflows vary'],['Compare roles','Core Maker, Melter, Fettling Operator','These roles relate to different operations'],['Check skills','Read each role’s mapped skills and qualifications','The actual opening sets the required experience']]],
 'forging'=>['Forging','Example learning sequence',['Metal','Forging','Hot / Closed Die Forging','Heat Treatment / Machining','Inspection'],[['Understand the category','Forging is an industrial activity','Explore its more specific processes'],['Compare work','Production, tooling, maintenance and quality','Different departments contribute different kinds of work'],['Explore a career','Read the relevant role and skill profile','Follow recorded openings after reviewing requirements']]],
 'textile'=>['Textiles','Related activities',['Spinning','Weaving / Knitting','Dyeing','Garments','Testing / Packaging'],[['Industry','Textiles','A broad group of products and activities'],['Activities','Spinning, knitting, dyeing and garment work','These are areas to explore, not one universal factory sequence'],['Career exploration','Production, maintenance and quality roles','Compare the role’s skills with the selected operation']]],
];
$sectorName=strtolower($taxonomy['sector']->name ?? '');
$activeExample=str_contains($sectorName,'forg')?'forging':((str_contains($sectorName,'cast')||str_contains($sectorName,'foundry'))?'foundry':(str_contains($sectorName,'text')?'textile':(str_contains($sectorName,'brak')?'brakes':(str_contains($sectorName,'axle')?'axle':'gears'))));
@endphp
<section class="explain-panel" style="width:100%" data-industrial-examples aria-label="Industrial learning examples">
 <span class="explain-kicker">SEE AN EXAMPLE</span><h2>How an industry becomes a career path</h2><p>Choose an example to see the relationship between a product, its processes and the work people do.</p>
 <div class="explain-examples" role="group" aria-label="Choose an industrial example">@foreach($examples as $key=>$example)<button type="button" data-explain-example="{{ $key }}" aria-pressed="{{ $activeExample===$key?'true':'false' }}" aria-controls="industry-example-{{ $key }}">{{ $example[0] }}</button>@endforeach</div>
 @foreach($examples as $key=>[$title,$kind,$nodes,$rows])
 <div class="explain-example" data-explain-panel="{{ $key }}" id="industry-example-{{ $key }}" @if($key!==$activeExample) hidden @endif>
 <h3>{{ $title }} &middot; {{ $kind }}</h3>
 @if($key==='brakes')<p class="explain-parent">Automobile &rarr; Braking System</p><div class="explain-branch" aria-label="Sibling components">@foreach($nodes as $node)<span>{{ $node }}</span>@endforeach</div>
 @else<ol class="explain-flow" aria-label="{{ $kind }} diagram">@foreach($nodes as $node)<li><span class="explain-number">{{ $loop->iteration }}</span><strong>{{ $node }}</strong></li>@endforeach</ol>@endif
 <div class="explain-table-wrap" role="region" tabindex="0" aria-label="{{ $title }} comparison"><table><caption>Connect the idea to the work</caption><thead><tr><th scope="col">Focus</th><th scope="col">Example</th><th scope="col">How to use it</th></tr></thead><tbody>@foreach($rows as $row)<tr>@foreach($row as $cell)<td>{{ $cell }}</td>@endforeach</tr>@endforeach</tbody></table></div>
 <ul style="margin-top:18px"><li>Choose a sector or process below to explore the directory’s mapped records.</li><li>Use the career dictionary to compare role names, skills and qualifications.</li><li>Check the current opening count and source; these examples do not represent advertised vacancies.</li></ul>
 </div>@endforeach
</section>