@extends('layouts.app')
@section('title', 'About Us — ' . config('platform.name'))
@push('styles')
<style>
.about-page{background:#fff;color:#17233c}.about-section{padding:78px 24px}.about-wrap{width:min(1120px,100%);margin:auto}.about-narrow{width:min(780px,100%);margin:auto;text-align:center}.about-soft{background:#f7f9fc}.about-dark{background:#101d33;color:#fff}.about-hero{padding:92px 24px;background:linear-gradient(180deg,#eff6ff,#fff);text-align:center}.about-pill{display:inline-block;padding:7px 14px;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-size:13px;font-weight:750}.about-kicker{color:#2563eb;font-size:13px;font-weight:800;letter-spacing:.09em;text-transform:uppercase}.about-title{margin:22px auto 0;max-width:850px;font-size:clamp(38px,5vw,58px);line-height:1.1}.about-title span,.arrow{color:#2563eb}.about-lead{margin:24px auto 0;color:#64748b;font-size:18px;line-height:1.75}.about-heading{margin:12px 0 0;font-size:clamp(30px,4vw,42px);line-height:1.2}.about-copy{margin:18px 0 0;color:#64748b;line-height:1.75}.about-two{display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:center}.about-callout{padding:30px;border:1px solid #dce3ed;border-radius:18px;background:#f8fafc;font-size:18px;font-weight:650;line-height:1.9}.about-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin-top:48px}.about-grid.four{grid-template-columns:repeat(4,1fr)}.about-grid.three{grid-template-columns:repeat(3,1fr)}.about-card{padding:26px;border:1px solid #dfe6f0;border-radius:17px;background:#fff;transition:.2s}.about-card:hover{transform:translateY(-4px);border-color:#2563eb;box-shadow:0 16px 34px #2563eb14}.about-card h3{margin:0 0 9px;font-size:19px}.about-card p{margin:0;color:#64748b;line-height:1.65}.about-number{display:grid;place-items:center;width:38px;height:38px;margin-bottom:15px;border-radius:10px;background:#dbeafe;color:#1d4ed8;font-weight:800}.source-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:38px auto 0;max-width:800px}.source-grid div{padding:12px;border:1px solid #dfe6f0;border-radius:11px;background:#fff;color:#64748b;font-size:13px;font-weight:650;text-align:center}.market-icon{font-size:26px}.about-dark .about-copy{color:#cbd5e1}.about-dark .about-pill{background:#2563eb24;color:#93c5fd}.about-cta{display:inline-flex;margin-top:34px;padding:13px 24px;border-radius:10px;background:#2563eb;color:#fff;text-decoration:none;font-weight:750}.about-cta:hover{background:#1d4ed8}@media(max-width:850px){.about-two{grid-template-columns:1fr}.about-grid.four,.source-grid{grid-template-columns:repeat(2,1fr)}.about-grid.three{grid-template-columns:1fr 1fr}}@media(max-width:600px){.about-section,.about-hero{padding:56px 20px}.about-grid,.about-grid.three{grid-template-columns:1fr}}
</style>
@endpush
@section('content')
<div class="about-page">
<section class="about-hero"><div class="about-narrow"><span class="about-pill">Who we are</span><h1 class="about-title">More than a job portal.<br>We are a <span>career ecosystem.</span></h1><p class="about-lead">Today's job market is fragmented — the right opening, the right skill to learn, and the right way to present yourself all live on different websites. {{ config('platform.name') }} brings discovery, learning, practice, and resume building into one connected platform, so a student's future depends on their skill and effort.</p></div></section>
<section class="about-section" id="vision"><div class="about-wrap about-two"><div><span class="about-kicker">Our vision</span><h2 class="about-heading">One platform. Every opportunity. A better future.</h2><p class="about-copy">We believe a student's future should never depend on whether they knew the right website, company, or person. If a student has the skill and dedication, they should be able to find the opportunity that matches it.</p></div><div class="about-callout">Learn the right skills <span class="arrow">→</span> Practice regularly <span class="arrow">→</span> Build your profile <span class="arrow">→</span> Create a professional resume <span class="arrow">→</span> Discover jobs <span class="arrow">→</span> Apply <span class="arrow">→</span> Build your future.</div></div></section>
<section class="about-section about-soft"><div class="about-narrow"><span class="about-kicker">The problem we're solving</span><h2 class="about-heading">Talent should never miss an opportunity because of missing information.</h2><p class="about-copy">Job portals, company career pages, social media, learning platforms, resume tools, and coding practice sites all live separately. A talented student can miss a great opportunity simply because they did not know a company was hiring.</p></div><div class="source-grid">@foreach(['Job portals','Company career pages','Social media','Technology blogs','Learning platforms','Resume tools','Coding practice sites','News platforms'] as $source)<div>{{ $source }}</div>@endforeach</div><p style="margin:34px 0 0;text-align:center;font-size:18px;font-weight:750">One login. One profile. One career ecosystem.</p></section>
<section class="about-section"><div class="about-wrap"><div class="about-narrow"><span class="about-kicker">How we help</span><h2 class="about-heading">Everything a career journey needs, in one place.</h2></div><div class="about-grid">@foreach([['Discover the latest opportunities','Explore roles by skill, technology, experience, location, company, or industry.'],['Know which companies are hiring','Stay connected with the market instead of manually checking career pages every day.'],['Build an ATS-friendly resume','Present your skills, education, projects, experience, and achievements professionally.'],['Learn what the market actually needs','Explore languages, frameworks, and modern development skills as the market evolves.']] as $item)<article class="about-card"><h3>{{ $item[0] }}</h3><p>{{ $item[1] }}</p></article>@endforeach</div></div></section>
<section class="about-section about-soft"><div class="about-wrap"><div class="about-narrow"><span class="about-kicker">The journey</span><h2 class="about-heading">Your complete career journey, one step at a time.</h2><p class="about-copy">We are not helping students land one job. We are helping them build a long-term career.</p></div><div class="about-grid four">@foreach([['01','Learn','Discover technologies relevant to your career.'],['02','Practice','Sharpen programming and interview-ready skills.'],['03','Build','Create projects and a stronger profile.'],['04','Prepare','Build an ATS-friendly resume.'],['05','Discover','Find companies and openings worth pursuing.'],['06','Apply','Go after roles matching your goals.'],['07','Grow','Keep learning as markets evolve.']] as $step)<article class="about-card"><span class="about-number">{{ $step[0] }}</span><h3>{{ $step[1] }}</h3><p>{{ $step[2] }}</p></article>@endforeach</div></div></section>
<section class="about-section"><div class="about-narrow"><span class="about-kicker">Always current</span><h2 class="about-heading">Always updated. Never left behind.</h2><p class="about-copy">The job market changes every day. {{ config('platform.name') }} is built to refresh continuously, keeping you connected to today's openings, skills, and market — not yesterday's.</p><p style="font-size:18px;font-weight:750">Today's market. Today's opportunities. Today's knowledge.</p></div></section>
<section class="about-section about-soft"><div class="about-wrap"><div class="about-narrow"><span class="about-kicker">The marketplace</span><h2 class="about-heading">Everything you need to build your career.</h2></div><div class="about-grid four">@foreach([['🔍','Jobs','Relevant openings matched to your skills.'],['🏢','Companies','Roles, hiring activity, and career paths.'],['📄','Resume Builder','Professional, ATS-friendly resumes.'],['🎓','Learning','Skills that matter today.'],['💻','Practice','Coding, DSA, and problem-solving.'],['🚀','Technology','Languages, frameworks, and tools.'],['📰','Market News','What is happening in tech and hiring.'],['📈','Career Growth','What to learn next.']] as $item)<article class="about-card" style="text-align:center"><div class="market-icon">{{ $item[0] }}</div><h3>{{ $item[1] }}</h3><p>{{ $item[2] }}</p></article>@endforeach</div></div></section>
<section class="about-section"><div class="about-wrap"><div class="about-narrow"><span class="about-kicker">Why choose us</span><h2 class="about-heading">Your career journey should not be scattered across ten websites.</h2></div><div class="about-grid three">@foreach([['Discover Opportunities','Find companies hiring in your field.'],['Learn Modern Skills','Stay connected with relevant technologies.'],['Practice Regularly','Improve programming and problem-solving.'],['Build Your Resume','Create an ATS-friendly resume.'],['Stay Updated','Follow technology and career developments.'],['Apply With Confidence','Find relevant roles and take your next step.']] as $reason)<article class="about-card"><h3>{{ $reason[0] }}</h3><p>{{ $reason[1] }}</p></article>@endforeach</div></div></section>
<section class="about-section about-dark"><div class="about-narrow"><span class="about-pill">Our core belief</span><h2 class="about-heading">Talent is everywhere. Opportunity should be too.</h2><p class="about-copy">Millions of talented students have what it takes to build successful careers. Sometimes all they need is the right information, skills, guidance, and opportunity at the right time.</p><a class="about-cta" href="{{ route('register') }}">Start Your Career Journey</a></div></section>
</div>
@endsection
