@extends('layouts.app')
@section('title','Online Code Editor — '.config('platform.name'))
@push('styles')
<style>
.practice-shell{min-height:calc(100vh - 76px);padding:28px;background:#07111f;color:#dbeafe}.editor-top{display:flex;align-items:center;justify-content:space-between;gap:18px;margin:0 auto 18px;max-width:1500px}.editor-title h1{margin:0;font-size:25px;color:#fff}.editor-title p{margin:5px 0 0;color:#8fa8c8}.editor-actions{display:flex;align-items:center;gap:10px}.language-select,.run-code{height:44px;border-radius:10px;font:700 14px Inter,system-ui}.language-select{min-width:190px;padding:0 36px 0 13px;border:1px solid #334966;background:#10213a;color:#fff}.language-select option{background:#fff;color:#10213e}.run-code{padding:0 20px;border:0;background:linear-gradient(135deg,#2563eb,#4f83f1);color:#fff;cursor:pointer;box-shadow:0 8px 22px #2563eb4d}.run-code:disabled{opacity:.65;cursor:wait}.workspace{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(340px,.75fr);gap:15px;max-width:1500px;margin:auto}.editor-panel,.side-panel{overflow:hidden;border:1px solid #213653;border-radius:15px;background:#0c192b;box-shadow:0 20px 55px #0003}.panel-head{display:flex;align-items:center;justify-content:space-between;height:46px;padding:0 15px;border-bottom:1px solid #213653;color:#9db2ce;font-size:13px}.dots{display:flex;gap:6px}.dots i{width:9px;height:9px;border-radius:50%;background:#ef4444}.dots i:nth-child(2){background:#f59e0b}.dots i:nth-child(3){background:#22c55e}.code-area{display:block;width:100%;height:630px;padding:20px;border:0;outline:0;resize:vertical;background:#07111f;color:#c4f1df;font:14px/1.65 Consolas,'Courier New',monospace;tab-size:4}.side-panel{display:grid;grid-template-rows:auto minmax(155px,.42fr) auto minmax(240px,.58fr)}.stdin{width:100%;min-height:155px;padding:16px;border:0;outline:0;resize:vertical;background:#0a1627;color:#dbeafe;font:13px/1.55 Consolas,monospace}.output{min-height:240px;margin:0;padding:17px;overflow:auto;white-space:pre-wrap;background:#050d18;color:#a7f3d0;font:13px/1.6 Consolas,monospace}.output.error{color:#fecaca}.status{display:flex;gap:15px;color:#7f97b7}.status strong{color:#dbeafe}.preview{width:100%;height:100%;min-height:300px;border:0;background:#fff}@media(max-width:950px){.editor-top{align-items:flex-start;flex-direction:column}.editor-actions{width:100%}.language-select{flex:1}.workspace{grid-template-columns:1fr}.code-area{height:480px}}
</style>
@endpush
@section('content')
<main class="practice-shell">
    <header class="editor-top"><div class="editor-title"><h1>Online Code Editor</h1><p>Write, compile and run code in a secure sandbox.</p></div><div class="editor-actions"><select class="language-select" id="language" aria-label="Programming language"><option value="html">HTML / CSS / JavaScript</option><option value="javascript">JavaScript (Node.js)</option><option value="python">Python 3</option><option value="java">Java</option><option value="c">C</option><option value="cpp">C++</option><option value="php">PHP</option><option value="go">Go</option><option value="rust">Rust</option><option value="ruby">Ruby</option><option value="typescript">TypeScript</option></select><button class="run-code" id="run" type="button">▶ Run Code</button></div></header>
    <section class="workspace"><div class="editor-panel"><div class="panel-head"><span>main.<b id="extension">html</b></span><span class="dots"><i></i><i></i><i></i></span></div><textarea class="code-area" id="code" spellcheck="false" aria-label="Source code"></textarea></div><aside class="side-panel"><div class="panel-head"><strong>Standard Input</strong><span>Optional</span></div><textarea class="stdin" id="stdin" placeholder="Enter input supplied to your program..."></textarea><div class="panel-head"><strong>Output</strong><span class="status"><span>Status: <strong id="status">Ready</strong></span><span id="metrics"></span></span></div><pre class="output" id="output">Select a language and click Run Code.</pre></aside></section>
</main>
@endsection
@push('scripts')
<script>
const templates={html:`<!doctype html>\n<html>\n<head><style>body{font-family:system-ui;padding:32px;color:#10213e}</style></head>\n<body><h1>Hello Ascendia</h1><button onclick="document.querySelector('h1').textContent='It works!'">Test</button></body>\n</html>`,javascript:`const name = 'Ascendia';\nconsole.log('Hello from ' + name);`,python:`name = input() or 'Ascendia'\nprint(f'Hello, {name}!')`,java:`import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner input = new Scanner(System.in);\n        String name = input.hasNextLine() ? input.nextLine() : "Ascendia";\n        System.out.println("Hello, " + name + "!");\n    }\n}`,c:`#include <stdio.h>\n\nint main(void) {\n    printf("Hello from C!\\n");\n    return 0;\n}`,cpp:`#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Hello from C++!" << endl;\n    return 0;\n}`,php:`<?php\n$name = trim(fgets(STDIN)) ?: 'Ascendia';\necho "Hello, {$name}!\\n";`,go:`package main\n\nimport "fmt"\n\nfunc main() { fmt.Println("Hello from Go!") }`,rust:`fn main() {\n    println!("Hello from Rust!");\n}`,ruby:`name = STDIN.gets&.strip || 'Ascendia'\nputs "Hello, #{name}!"`,typescript:`const message: string = 'Hello from TypeScript!';\nconsole.log(message);`};
const extensions={html:'html',javascript:'js',python:'py',java:'java',c:'c',cpp:'cpp',php:'php',go:'go',rust:'rs',ruby:'rb',typescript:'ts'};
const language=document.getElementById('language'),code=document.getElementById('code'),stdin=document.getElementById('stdin'),output=document.getElementById('output'),statusText=document.getElementById('status'),metrics=document.getElementById('metrics'),runButton=document.getElementById('run');
function setLanguage(){code.value=templates[language.value];document.getElementById('extension').textContent=extensions[language.value];output.className='output';output.textContent=language.value==='html'?'HTML preview will appear here.':'Click Run Code to compile and execute.';statusText.textContent='Ready';metrics.textContent=''}
async function run(){runButton.disabled=true;runButton.textContent='Running…';statusText.textContent='Running';metrics.textContent='';output.className='output';output.textContent='Compiling and executing…';try{if(language.value==='html'){output.innerHTML='';const frame=document.createElement('iframe');frame.className='preview';frame.sandbox='allow-scripts';frame.srcdoc=code.value;output.appendChild(frame);statusText.textContent='Preview ready';return}const response=await fetch(@json(route('practice.run')),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':@json(csrf_token())},body:JSON.stringify({language:language.value,source:code.value,stdin:stdin.value})});const result=await response.json();if(!response.ok)throw new Error(result.message||Object.values(result.errors||{}).flat().join('\n')||'Execution failed.');const text=[result.compile_output,result.stderr,result.stdout,result.message].filter(Boolean).join('\n');output.textContent=text||'(Program finished with no output)';output.classList.toggle('error',Boolean(result.compile_output||result.stderr));statusText.textContent=result.status||'Finished';metrics.textContent=[result.time?`${result.time}s`:null,result.memory?`${result.memory} KB`:null].filter(Boolean).join(' · ')}catch(error){output.textContent=error.message;output.classList.add('error');statusText.textContent='Error'}finally{runButton.disabled=false;runButton.textContent='▶ Run Code'}}
language.addEventListener('change',setLanguage);runButton.addEventListener('click',run);code.addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();const start=code.selectionStart;code.setRangeText('    ',start,code.selectionEnd,'end')}if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();run()}});setLanguage();
</script>
@endpush