<?php
namespace App\Services;
use App\Models\Job;use App\Models\JobApplication;use App\Models\Resume;use Illuminate\Support\Collection;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class ResumeJobMatchingService
{
 public function process(Resume $resume):array{$resume->loadMissing('profile.user');$user=$resume->profile?->user;if(!$user||$resume->parsing_status!=='processed')return ['recommended'=>0,'applied'=>0,'reason'=>'Resume is not ready.'];$preference=DB::table('candidate_auto_apply_preferences')->where('user_id',$user->id)->first();$minimum=(int)($preference->minimum_match_score??75);$limit=min(10,max(1,(int)($preference->daily_limit??10)));$skills=$this->normalizeSkills($resume->parsed_data['skills']??[]);if($skills->isEmpty())return ['recommended'=>0,'applied'=>0,'reason'=>'No supported skills were extracted.'];$todayCount=JobApplication::where('user_id',$user->id)->where('application_source','resume_auto_match')->whereDate('applied_at',today())->count();$remaining=max(0,$limit-$todayCount);$recommended=0;$applied=0;$jobs=Job::query()->active()->whereNotNull('employer_id')->where('source','employer')->where('application_method','portal')->whereDoesntHave('applications',fn($q)=>$q->where('user_id',$user->id))->whereDoesntHave('screeningQuestions',fn($q)=>$q->where('is_required',true))->with('skills')->latest('posted_at')->limit(500)->get();$ranked=$jobs->map(function($job)use($skills){return ['job'=>$job]+$this->score($skills,$job);})->filter(fn($m)=>$m['score']>=35)->sortByDesc('score')->values();foreach($ranked as $match){$recommended++;if(!$preference||!$preference->enabled||!$preference->consented_at||$remaining<=0||$match['score']<$minimum)continue;$application=DB::transaction(function()use($user,$resume,$match){$application=JobApplication::firstOrCreate(['job_id'=>$match['job']->id,'user_id'=>$user->id],['status'=>'applied','applied_at'=>now(),'application_source'=>'resume_auto_match','match_score'=>$match['score'],'matched_skills'=>$match['matched']->all(),'resume_id'=>$resume->id]);if($application->wasRecentlyCreated)DB::table('application_status_history')->insert(['job_application_id'=>$application->id,'changed_by'=>$user->id,'from_status'=>null,'to_status'=>'applied','note'=>'Submitted by candidate-authorized resume skill matching. Match: '.$match['score'].'%.','created_at'=>now()]);return $application;});if($application->wasRecentlyCreated){$applied++;$remaining--;}}return ['recommended'=>$recommended,'applied'=>$applied,'reason'=>$preference?->enabled?'Matching completed.':'Recommendations built; auto-apply consent is disabled.'];}
 private function score(Collection $candidate,Job $job):array{$required=$job->skills->filter(fn($s)=>in_array($s->pivot->importance,['required','mandatory'],true))->pluck('name');if($required->isEmpty())$required=$job->skills->pluck('name');if($required->isEmpty()){$text=implode(' ',[$job->title,is_array($job->requirements)?implode(' ',$job->requirements):(string)$job->requirements,$job->description]);$required=collect(config('recruitment.skills',[]))->filter(fn($skill)=>preg_match('/(?<![a-z0-9])'.preg_quote($skill,'/').'(?![a-z0-9])/i',$text));}$required=$this->normalizeSkills($required);$matched=$required->intersect($candidate)->values();$coverage=$required->isEmpty()?0:$matched->count()/$required->count();$precision=$candidate->isEmpty()?0:$matched->count()/min(12,$candidate->count());return ['score'=>round(min(100,($coverage*85)+($precision*15)),2),'matched'=>$matched,'required'=>$required];}
 private function normalizeSkills(iterable $skills):Collection{return collect($skills)->map(fn($s)=>Str::lower(trim(preg_replace('/\s+/',' ',(string)$s))))->map(fn($s)=>match($s){'js'=>'javascript','ts'=>'typescript','nodejs'=>'node.js','reactjs'=>'react','springboot'=>'spring boot','html5'=>'html','css3'=>'css',default=>$s})->filter()->unique()->values();}
}
