@extends('layouts.employer')
@section('title','Dashboard')
@push('styles')<style>.welcome{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.welcome h1{font-size:30px;margin:0 0 7px}.muted{color:var(--muted)}.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:14px;margin-bottom:28px}.stat{padding:20px}.stat b{display:block;font-size:28px;margin:9px 0}.stat span{color:var(--muted)}.grid{display:grid;grid-template-columns:1.7fr 1fr;gap:20px}.block{padding:23px;margin-bottom:20px}.block-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.block h2{margin:0;font-size:19px}.job{display:grid;grid-template-columns:1fr 110px 110px 100px;gap:12px;align-items:center;padding:16px 0;border-top:1px solid var(--line)}.job:first-of-type{border-top:0}.badge{display:inline-block;padding:5px 9px;background:#eef4ff;color:#2457bd;border-radius:30px;font-size:12px;font-weight:750}.actions{display:flex;gap:6px;flex-wrap:wrap}.mini{border:1px solid var(--line);background:#fff;border-radius:7px;padding:6px 9px;cursor:pointer}.person{display:flex;justify-content:space-between;padding:14px 0;border-top:1px solid var(--line)}.company-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.company-form input,.company-form select{width:100%;padding:11px;border:1px solid var(--line);border-radius:8px}.empty{text-align:center;padding:35px;color:var(--muted)}@media(max-width:1150px){.stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.grid{display:block}.job{grid-template-columns:1fr}.company-form{grid-template-columns:1fr}}@media(max-width:560px){.stats{grid-template-columns:1fr 1fr}.welcome{align-items:flex-start;gap:15px;flex-direction:column}}</style>@endpush
@section('content')
<div class="welcome"><div><h1>Welcome back, {{strtok(auth()->user()->name,' ')}}</h1><div class="muted">Manage your hiring activities and find the right candidates.</div></div><a class="btn btn-primary" href="{{route('employer.jobs.create')}}">＋ Post a New Job</a></div>
<section class="stats">@foreach(['active'=>'Active Jobs','applications'=>'Total Applications','new'=>'New Applications','shortlisted'=>'Shortlisted','interviews'=>'Interviews Scheduled','closed'=>'Jobs Closed'] as $key=>$label)<div class="card stat"><span>{{$label}}</span><b>{{$stats[$key]}}</b><small class="muted">Live account data</small></div>@endforeach</section>
@if(!$profile)<section id="company" class="card block"><div class="block-head"><div><h2>Complete your company profile</h2><p class="muted">A company profile is required before publishing a job.</p></div></div><form class="company-form" method="post" action="{{route('employer.company.store')}}">@csrf<input name="name" placeholder="Company name" required><select name="company_type"><option value="company">Company</option><option value="recruitment_agency">Recruitment agency</option><option value="consultancy">Consultancy</option><option value="staffing_agency">Staffing agency</option></select><input name="website" placeholder="https://company.com"><input name="country" value="India" required><input name="designation" placeholder="Your designation"><input name="phone" placeholder="Phone"><button class="btn btn-primary">Save company profile</button></form></section>@endif
<div class="grid"><section id="jobs" class="card block"><div class="block-head"><h2>Recent Jobs</h2><a class="btn" href="{{route('employer.jobs.create')}}">Post Job</a></div>@forelse($jobs as $job)<div class="job"><div><strong>{{$job->title}}</strong><div class="muted">{{$job->location?:'Location pending'}} · {{$job->job_type}}</div></div><span class="badge">{{ucwords(str_replace('_',' ',$job->status))}}</span><span>{{$job->applications_count}} applicants</span><div class="actions"><a class="mini" href="{{route('employer.jobs.edit',$job)}}">Edit</a><a class="mini" href="{{route('employer.jobs.applicants',$job)}}">Applicants</a><form method="post" action="{{route('employer.jobs.duplicate',$job)}}">@csrf<button class="mini">Copy</button></form>@if($job->status==='published')<form method="post" action="{{route('employer.jobs.status',[$job,'paused'])}}">@csrf @method('PATCH')<button class="mini">Pause</button></form>@elseif($job->status==='paused')<form method="post" action="{{route('employer.jobs.status',[$job,'published'])}}">@csrf @method('PATCH')<button class="mini">Resume</button></form>@endif</div></div>@empty<div class="empty"><h3>No jobs posted yet</h3><p>Create your first professional job listing.</p></div>@endforelse {{$jobs->links()}}</section><section id="applicants" class="card block"><div class="block-head"><h2>Recent Applicants</h2></div>@forelse($recentApplicants as $app)<div class="person"><div><strong>{{$app->candidate->name}}</strong><div class="muted">{{$app->job->title}}</div></div><span class="badge">{{ucwords(str_replace('_',' ',$app->status))}}</span></div>@empty<div class="empty">Applications will appear here.</div>@endforelse</section></div>
@endsection
