@extends('layouts.employer')
@section('title',$job->exists?'Edit Job':'Post a Job')
@push('styles')<style>.page-title h1{font-size:30px;margin:0 0 8px}.stepper{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:25px 0}.step{padding:13px 9px;border-bottom:3px solid #dbe2ed;color:#718096;font-weight:750}.step.active{border-color:var(--blue);color:var(--blue)}.form-card{padding:28px 28px 0;margin-bottom:32px;overflow:visible}.pane{display:none;min-height:260px;padding-bottom:28px}.pane.active{display:block}.pane h2{font-size:20px;margin:0 0 5px}.sub{color:var(--muted);margin-bottom:24px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:18px}.full{grid-column:1/-1}.label{display:block;font-weight:750;margin-bottom:7px}.req{color:#d92d20}.field{width:100%;padding:12px 13px;border:1px solid #cfd8e6;border-radius:9px;background:#fff;font:inherit}.field:focus{outline:3px solid #2563eb20;border-color:var(--blue)}textarea.field{min-height:180px;resize:vertical}.checks{display:flex;flex-wrap:wrap;gap:10px}.check{padding:9px 11px;border:1px solid var(--line);border-radius:8px;background:#fafbfc}.hint{font-size:12px;color:var(--muted);margin-top:6px}.sticky{position:sticky;bottom:0;margin:0 -28px;background:#fff;border-top:1px solid var(--line);border-radius:0 0 14px 14px;padding:14px 28px;display:flex;align-items:center;justify-content:space-between;gap:16px;z-index:10;box-shadow:0 -8px 24px rgba(15,35,70,.08)}.right{display:flex;align-items:center;gap:10px}.preview{padding:25px;border:1px solid var(--line);border-radius:14px}.preview h2{font-size:25px}.chips{display:flex;gap:7px;flex-wrap:wrap}.chip{padding:6px 9px;border-radius:6px;background:#eef4ff;color:#2457bd}.question{display:grid;grid-template-columns:1fr 170px 80px;gap:10px;margin-bottom:10px}.location-row{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}.counter{text-align:right;color:var(--muted);font-size:12px}.success-review{padding:14px;background:#ecfdf3;color:#087443;border-radius:9px}@media(max-width:850px){.fields{grid-template-columns:1fr}.full{grid-column:auto}.stepper{overflow:auto}.step{min-width:145px}.question,.location-row{grid-template-columns:1fr}.form-card{padding:20px 20px 0}.sticky{margin:0 -20px;padding:12px 20px}.right{gap:7px}.sticky .btn{padding-left:12px;padding-right:12px}}</style>@endpush
@section('content')
<div class="page-title"><h1>{{$job->exists?'Edit Job':'Post a New Job'}}</h1><div class="muted">Create a detailed job listing to attract the most relevant candidates.</div></div>
<div class="stepper">@foreach(['Basic Information','Requirements','Compensation','Application','Review & Publish'] as $i=>$label)<div class="step {{$i===0?'active':''}}" data-step-label="{{$i}}"><small>0{{$i+1}}</small><br>{{$label}}</div>@endforeach</div>
<form id="jobForm" class="card form-card" method="post" action="{{$job->exists?route('employer.jobs.update',$job):route('employer.jobs.store')}}">@csrf @if($job->exists)@method('PUT')@endif
<section class="pane active" data-pane="0"><h2>Job Details</h2><p class="sub">Tell candidates what the opportunity is and where they will work.</p><div class="fields">
@php
    $selectedTitle = old('title', $job->title);
    $selectedRole = old('role', $job->role);
    $knownTitles = $jobTitles->flatten()->pluck('title');
@endphp
<div class="full"><label class="label">Job Title <span class="req">*</span></label><select class="field" name="title" required><option value="" disabled @selected(!$selectedTitle)>Select a job title</option>@if($selectedTitle && !$knownTitles->contains($selectedTitle))<option value="{{$selectedTitle}}" selected>{{$selectedTitle}} (existing title)</option>@endif @foreach($jobTitles as $category=>$titles)<optgroup label="{{$category}}">@foreach($titles as $title)<option value="{{$title->title}}" @selected($selectedTitle===$title->title)>{{$title->title}}</option>@endforeach</optgroup>@endforeach</select></div>
<div><label class="label">Job Category <span class="req">*</span></label><input class="field" name="category" list="categories" value="{{old('category',$job->category)}}" required><datalist id="categories">@foreach($options['categories'] as $v)<option value="{{$v}}">@endforeach</datalist></div>
<div><label class="label">Primary Role / Designation <span class="req">*</span></label><select class="field" name="role" required><option value="" disabled @selected(!$selectedRole)>Select a primary role</option>@if($selectedRole && !$knownTitles->contains($selectedRole))<option value="{{$selectedRole}}" selected>{{$selectedRole}} (existing role)</option>@endif @foreach($jobTitles as $category=>$titles)<optgroup label="{{$category}}">@foreach($titles as $title)<option value="{{$title->title}}" @selected($selectedRole===$title->title)>{{$title->title}}</option>@endforeach</optgroup>@endforeach</select></div>
<div><label class="label">Employment Type</label><select class="field" name="job_type">@foreach(['Full Time','Part Time','Contract','Freelance','Internship','Temporary','Consultant','Apprenticeship','Trainee'] as $v)<option @selected(old('job_type',$job->job_type)===$v)>{{$v}}</option>@endforeach</select></div>
<div><label class="label">Work Mode</label><select class="field" id="workMode" name="work_mode">@foreach(['On-site','Remote','Hybrid'] as $v)<option @selected(old('work_mode',$job->work_mode)===$v)>{{$v}}</option>@endforeach</select></div>
<div class="full location-row" id="locationFields"><div><label class="label">Country</label><input class="field" name="country" value="{{old('country',$job->country?:'India')}}"></div><div><label class="label">State</label><input class="field" name="state" value="{{old('state',$job->state)}}"></div><div><label class="label">City</label><input class="field" name="location" value="{{old('location',$job->location)}}"></div></div>
<label class="check full"><input type="checkbox" name="relocation_allowed" value="1" @checked(old('relocation_allowed',$job->relocation_allowed))> Open to candidates willing to relocate</label>
<div><label class="label">Number of Openings</label><input class="field" type="number" name="vacancies" min="1" max="10000" value="{{old('vacancies',$job->vacancies?:1)}}"></div><div><label class="label">Hiring Urgency</label><select class="field" name="hiring_urgency">@foreach(['Immediate','Within 7 Days','Within 15 Days','Within 30 Days','Flexible'] as $v)<option @selected(old('hiring_urgency',$job->hiring_urgency)===$v)>{{$v}}</option>@endforeach</select></div></div></section>
<section class="pane" data-pane="1"><h2>Job Requirements</h2><p class="sub">Define experience, education, skills and the work candidates will perform.</p><div class="fields">
<div><label class="label">Minimum Experience</label><input class="field" type="number" min="0" max="60" name="experience_min" value="{{old('experience_min',$job->experience_min)}}" placeholder="0"></div><div><label class="label">Maximum Experience</label><input class="field" type="number" min="0" max="60" name="experience_max" value="{{old('experience_max',$job->experience_max)}}" placeholder="5"></div>
<div><label class="label">Minimum Education</label><select class="field" name="education">@foreach(['Education Not Mandatory','High School','Diploma',"Bachelor's Degree",'B.Tech / B.E.','BCA','B.Sc','MCA','M.Tech / M.E.','MBA',"Master's Degree",'PhD','Any Graduate'] as $v)<option @selected(old('education',$job->education)===$v)>{{$v}}</option>@endforeach</select></div><div><label class="label">Preferred Specialization</label><input class="field" name="specialization" value="{{old('specialization',$job->specialization)}}" placeholder="Computer Science"></div>
<div><label class="label">Primary Technology</label><input class="field" list="skills" name="primary_technology" value="{{old('primary_technology',$job->primary_technology)}}"><datalist id="skills">@foreach($options['skills'] as $v)<option value="{{$v}}">@endforeach</datalist></div><div><label class="label">Job Level</label><select class="field" name="job_level">@foreach(['Entry Level','Junior','Mid Level','Senior','Lead','Manager','Director','Executive'] as $v)<option @selected(old('job_level',$job->job_level)===$v)>{{$v}}</option>@endforeach</select></div>
@php $skillText=fn($importance)=>$job->exists?$job->skills->filter(fn($s)=>$s->pivot->importance===$importance)->pluck('name')->implode(', '):''; @endphp
<div class="full"><label class="label">Required Skills</label><input class="field" name="required_skills" value="{{old('required_skills',$skillText('required'))}}" placeholder="Java, Spring Boot, MySQL, Microservices"><div class="hint">Comma-separated; custom skills are supported.</div></div><div><label class="label">Mandatory Skills</label><input class="field" name="mandatory_skills" value="{{old('mandatory_skills',$skillText('mandatory'))}}"></div><div><label class="label">Good to Have Skills</label><input class="field" name="good_to_have_skills" value="{{old('good_to_have_skills',$skillText('preferred'))}}"></div>
<div class="full"><label class="label">Job Description <span class="req">*</span></label><div class="hint">Suggested sections: About the Role · What You Will Do · Key Responsibilities · Required Qualifications · What We Offer</div><textarea class="field" id="description" maxlength="10000" name="description" required placeholder="We are looking for a skilled and motivated Senior Backend Engineer...">{{old('description',$job->description)}}</textarea><div class="counter"><span id="descCount">0</span> / 10,000</div></div></div></section>
<section class="pane" data-pane="2"><h2>Salary & Benefits</h2><p class="sub">Transparent compensation helps attract qualified candidates.</p><div class="fields"><div><label class="label">Salary Visibility</label><select class="field" id="salaryType" name="salary_type"><option value="exact">Show Exact Salary</option><option value="range">Show Salary Range</option><option value="undisclosed">Do Not Disclose</option><option value="competitive">Competitive Salary</option></select></div><div><label class="label">Currency</label><select class="field" name="salary_currency">@foreach(['INR','USD','EUR','GBP','Other'] as $v)<option @selected(old('salary_currency',$job->salary_currency)===$v)>{{$v}}</option>@endforeach</select></div><div><label class="label">Minimum Salary</label><input class="field" type="number" name="salary_min" value="{{old('salary_min',$job->salary_min)}}"></div><div><label class="label">Maximum Salary</label><input class="field" type="number" name="salary_max" value="{{old('salary_max',$job->salary_max)}}"></div><div><label class="label">Salary Period</label><select class="field" name="salary_period"><option value="year">Per Year</option><option value="month">Per Month</option><option value="hour">Per Hour</option></select></div><div class="full"><label class="label">Benefits</label><div class="checks">@foreach($options['benefits'] as $benefit)<label class="check"><input type="checkbox" name="benefits[]" value="{{$benefit}}"> {{$benefit}}</label>@endforeach</div></div></div></section>
<section class="pane" data-pane="3"><h2>Application Settings</h2><p class="sub">Choose how candidates apply and what information they must provide.</p><div class="fields"><div><label class="label">Application Method</label><select class="field" id="applicationMethod" name="application_method"><option value="portal">Apply on Our Portal</option><option value="external">Redirect to External Website</option><option value="email">Apply via Email</option></select></div><div id="externalField"><label class="label">Application URL</label><input class="field" type="url" name="external_url" value="{{old('external_url',$job->external_url)}}"></div><div id="emailField"><label class="label">Application Email</label><input class="field" type="email" name="application_email" value="{{old('application_email',$job->application_email)}}"></div><div><label class="label">Application Deadline</label><input class="field" type="date" name="application_deadline" value="{{old('application_deadline',$job->application_deadline?->format('Y-m-d'))}}"></div><div><label class="label">Job Visibility</label><select class="field" name="job_visibility"><option value="public">Public — all candidates</option><option value="private">Private — direct link</option><option value="internal">Internal — invited candidates</option><option value="draft">Draft</option></select></div><div class="full"><label class="label">Candidate Requirements</label><div class="checks">@foreach(['resume_required'=>'Resume Required','cover_letter_required'=>'Cover Letter Required','portfolio_required'=>'Portfolio Required','github_required'=>'GitHub Profile Required','linkedin_required'=>'LinkedIn Profile Required'] as $name=>$label)<label class="check"><input type="checkbox" name="{{$name}}" value="1" @checked(old($name,$job->{$name}??$name==='resume_required'))> {{$label}}</label>@endforeach</div></div><div class="full"><div style="display:flex;justify-content:space-between"><label class="label">Screening Questions</label><button type="button" class="btn" id="addQuestion">＋ Add Question</button></div><div id="questions"></div></div></div></section>
<section class="pane" data-pane="4"><h2>Preview & Publish</h2><p class="sub">Review how candidates will see this opportunity.</p><div class="preview"><div class="muted" id="pCompany">{{$job->company->name??'Your company'}}</div><h2 id="pTitle">Job title</h2><p id="pMeta">Location · Experience · Work mode · Employment type</p><div class="chips" id="pSkills"></div><p id="pDescription" class="muted"></p></div><p class="success-review">Publishing makes a public job immediately searchable. Saving a draft keeps it private.</p></section>
<div class="sticky"><button type="button" class="btn" id="backBtn" disabled>Back</button><div class="right"><button class="btn" name="action" value="draft">Save as Draft</button><button type="button" class="btn btn-primary" id="nextBtn">Continue</button><button class="btn btn-primary" id="publishBtn" name="action" value="publish" style="display:none">Publish Job</button></div></div></form>
@endsection
@push('scripts')<script>(()=>{let step=0,q=0;const panes=[...document.querySelectorAll('.pane')],labels=[...document.querySelectorAll('.step')],next=document.querySelector('#nextBtn'),back=document.querySelector('#backBtn'),publish=document.querySelector('#publishBtn'),form=document.querySelector('#jobForm');function show(n){step=n;panes.forEach((x,i)=>x.classList.toggle('active',i===n));labels.forEach((x,i)=>x.classList.toggle('active',i<=n));back.disabled=n===0;next.style.display=n===4?'none':'';publish.style.display=n===4?'':'none';if(n===4)preview();scrollTo({top:0,behavior:'smooth'})}next.onclick=()=>{const required=[...panes[step].querySelectorAll('[required]')];if(required.some(x=>!x.reportValidity()))return;show(Math.min(4,step+1))};back.onclick=()=>show(Math.max(0,step-1));labels.forEach((x,i)=>x.onclick=()=>show(i));function val(n){return form.elements[n]?.value||''}function preview(){document.querySelector('#pTitle').textContent=val('title')||'Job title';document.querySelector('#pMeta').textContent=[val('location'),`${val('experience_min')||0}-${val('experience_max')||'+'} years`,val('work_mode'),val('job_type')].filter(Boolean).join(' · ');document.querySelector('#pDescription').textContent=val('description').slice(0,350);document.querySelector('#pSkills').innerHTML=val('required_skills').split(',').filter(Boolean).map(s=>`<span class="chip">${s.trim().replace(/[<>]/g,'')}</span>`).join('')}const desc=document.querySelector('#description'),count=document.querySelector('#descCount');function counter(){count.textContent=desc.value.length}desc.oninput=counter;counter();document.querySelector('#addQuestion').onclick=()=>{const box=document.createElement('div');box.className='question';box.innerHTML=`<input class="field" name="questions[${q}][question]" placeholder="Screening question"><select class="field" name="questions[${q}][type]"><option value="yes_no">Yes / No</option><option value="text">Text</option><option value="long_text">Long Text</option><option value="number">Number</option><option value="dropdown">Dropdown</option><option value="multiple_choice">Multiple Choice</option></select><label class="check"><input type="checkbox" name="questions[${q}][required]" value="1"> Required</label>`;document.querySelector('#questions').append(box);q++};form.addEventListener('submit',e=>{if(e.submitter?.value==='publish'&&!confirm('Are you sure you want to publish this job?'))e.preventDefault()});const mode=document.querySelector('#workMode'),loc=document.querySelector('#locationFields');function modeUI(){loc.style.opacity=mode.value==='Remote'?'.45':'1'}mode.onchange=modeUI;modeUI()})();</script>@endpush
