<style>.sitebar{min-height:76px;background:#203f68;color:#fff}.sitebar-inner{width:100%;min-height:76px;padding:0 30px;display:flex;align-items:center;gap:30px}.site-logo{display:block;flex:0 0 auto;padding:3px 9px;border-radius:8px;background:#fff}.site-logo img{display:block;width:145px;height:55px;object-fit:contain}.site-nav{display:flex;flex:1;align-items:center;gap:20px;flex-wrap:wrap}.site-nav a{color:#e8f0fa;text-decoration:none;font-size:14px}.site-nav>.btn:first-of-type{margin-left:auto}.site-auth{padding:9px 14px;border:1px solid #7fa7d5;border-radius:8px;background:#315f96;color:#fff!important;font-weight:750}.candidate-nav{display:flex!important;align-items:center;gap:8px}.candidate-nav img,.candidate-nav span{width:36px;height:36px;border-radius:50%;object-fit:cover;background:#3f73ad;display:grid;place-items:center;color:#fff}@media(max-width:1050px){.sitebar{padding:12px 0}.sitebar-inner{padding:0 18px;align-items:flex-start;flex-wrap:wrap}.site-nav{flex-basis:100%}.site-nav>.btn:first-of-type{margin-left:0}}</style>
<style>.site-dropdown{position:relative}.site-dropdown-toggle{display:flex;align-items:center;gap:7px;padding:12px 0;border:0;background:transparent;color:#cbd5e1;font:inherit;font-size:14px;cursor:pointer}.site-dropdown-toggle:after{content:'\2304';font-size:15px}.site-dropdown-menu{position:absolute;top:calc(100% + 9px);left:0;z-index:120;display:none;min-width:250px;padding:9px;background:#fff;border:1px solid #dbe4f0;border-radius:12px;box-shadow:0 18px 42px rgba(0,0,0,.24)}.site-dropdown:hover .site-dropdown-menu,.site-dropdown:focus-within .site-dropdown-menu,.site-dropdown.open .site-dropdown-menu{display:grid}.site-dropdown-menu a{display:block;padding:10px 12px;border-radius:8px;color:#1d2c47!important;text-decoration:none;font-size:14px;font-weight:650}.site-dropdown-menu a:hover{background:#eef5ff;color:#1769ff!important}.site-dropdown-menu small{display:block;margin-top:2px;color:#718096;font-size:11px;font-weight:500}</style>
<header class="sitebar"><div class="sitebar-inner">@include('partials.logo')<nav class="site-nav"><div class="site-dropdown"><button class="site-dropdown-toggle" type="button" aria-expanded="false">Find Jobs</button><div class="site-dropdown-menu"><a href="{{route('home')}}#jobs">Find Jobs<small>Search verified openings</small></a><a href="{{route('companies.index')}}">Companies<small>Browse company profiles</small></a><a href="{{route('jobs.hr')}}">Jobs Posted by HR<small>Direct recruiter opportunities</small></a></div></div><div class="site-dropdown"><button class="site-dropdown-toggle" type="button" aria-expanded="false">Learning</button><div class="site-dropdown-menu"><a href="{{route('learning.index')}}">Learning<small>Courses and interview preparation</small></a><a href="{{route('practice')}}">Practice<small>Code and test your skills</small></a></div></div><div class="site-dropdown"><button class="site-dropdown-toggle" type="button" aria-expanded="false">Resume Builder</button><div class="site-dropdown-menu"><a href="{{route('resume.builder')}}">Resume Builder<small>Create and edit your resume</small></a><a href="{{route('resume.builder')}}#ats-preview">ATS-Friendly Resume<small>Preview the ATS-readable format</small></a></div></div><a href="{{route('about')}}">About Us</a><a href="{{route('contact')}}">Contact</a>@auth @if(auth()->user()->role_code===2||auth()->user()->role==='admin')<a href="{{route('admin.dashboard')}}">Owner Dashboard</a>@elseif(auth()->user()->role_code===0||auth()->user()->role==='employer')<a href="{{route('employer.dashboard')}}">HR Dashboard</a>@else @php($navProfile=auth()->user()->candidateProfile)<a class="candidate-nav" href="{{route('dashboard')}}">@if($navProfile?->avatar_url)<img src="{{$navProfile->avatar_url}}" alt="Profile">@else<span>{{strtoupper(substr(auth()->user()->name,0,1))}}</span>@endif<b>{{auth()->user()->name}}</b></a>@endif<form method="post" action="{{route('logout')}}" style="margin:0">@csrf<button class="site-auth">Logout</button></form>@else<a class="btn btn-primary" href="{{route('employer.login')}}">HR Login</a><a class="btn btn-primary" href="{{route('owner.login')}}">Owner Login</a><a class="btn btn-primary site-auth" href="{{route('register')}}">Student Sign Up</a>@endauth</nav></div></header>
<style>.site-nav .btn{width:132px!important;min-width:132px;height:40px;padding:0 10px!important;display:inline-flex!important;align-items:center;justify-content:center;color:#fff!important;white-space:nowrap}.site-nav .hr-jobs-link{width:auto!important;min-width:172px!important}</style>
@include('partials.alerts')
<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.site-dropdown-toggle').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();const menu=button.closest('.site-dropdown');document.querySelectorAll('.site-dropdown.open').forEach(item=>{if(item!==menu){item.classList.remove('open');item.querySelector('.site-dropdown-toggle')?.setAttribute('aria-expanded','false')}});const open=menu.classList.toggle('open');button.setAttribute('aria-expanded',String(open))}));document.addEventListener('click',()=>document.querySelectorAll('.site-dropdown.open').forEach(item=>{item.classList.remove('open');item.querySelector('.site-dropdown-toggle')?.setAttribute('aria-expanded','false')}))})</script>
<script>
document.addEventListener('DOMContentLoaded', () => {
    const nav = document.querySelector('.site-nav');
    const jobsMenu = nav?.querySelector('.site-dropdown');
    if (nav && jobsMenu && !nav.querySelector('.companies-nav-link')) {
        const companies = document.createElement('a');
        companies.className = 'companies-nav-link';
        companies.href = @json(route('companies.index'));
        companies.textContent = 'Companies';
        jobsMenu.insertAdjacentElement('afterend', companies);
    }
});
</script>
