<style>.sitebar{min-height:76px;background:#203f68;color:#fff}.sitebar-inner{width:100%;min-height:76px;padding:0 30px;display:flex;align-items:center;gap:30px}.site-logo{display:block;flex:0 0 auto;padding:3px 9px;border-radius:8px;background:#fff}.site-logo img{display:block;width:145px;height:55px;object-fit:contain}.site-nav{display:flex;flex:1;align-items:center;gap:20px;flex-wrap:wrap}.site-nav a{color:#e8f0fa;text-decoration:none;font-size:14px}.site-nav>.nav-action:first-of-type{margin-left:auto}.site-nav>form:last-child{margin-left:auto!important}.nav-action{display:inline-flex!important;align-items:center;justify-content:center;width:132px!important;min-width:132px;height:42px;padding:0 12px!important;border:1px solid #7fa7d5!important;border-radius:8px!important;background:#315f96!important;color:#fff!important;font:750 14px Inter,system-ui,sans-serif!important;line-height:1!important;text-decoration:none!important;white-space:nowrap;cursor:pointer;box-shadow:none!important;transition:background-color .18s ease,border-color .18s ease,transform .18s ease}.nav-action:hover{border-color:#9fc1e8!important;background:#3f73ad!important;color:#fff!important;transform:translateY(-1px)}.nav-action:focus-visible{outline:3px solid rgba(159,193,232,.4);outline-offset:3px}.candidate-nav{display:flex!important;align-items:center;gap:8px}.candidate-nav img,.candidate-nav span{width:36px;height:36px;border-radius:50%;object-fit:cover;background:#3f73ad;display:grid;place-items:center;color:#fff}@media(max-width:1050px){.site-nav>form:last-child{margin-left:0!important}.sitebar{padding:12px 0}.sitebar-inner{padding:0 18px;align-items:flex-start;flex-wrap:wrap}.site-nav{flex-basis:100%}.site-nav>.nav-action:first-of-type{margin-left:0}}</style>
<style>.site-dropdown{position:relative}.site-dropdown-toggle{display:flex;align-items:center;gap:7px;padding:12px 0;border:0;background:transparent;color:#cbd5e1;font:inherit;font-size:14px;cursor:pointer}.site-dropdown-toggle:after{content:'\2304';font-size:15px}.site-dropdown-menu{position:absolute;top:calc(100% + 9px);left:0;z-index:120;display:none;min-width:250px;padding:9px;background:#fff;border:1px solid #dbe4f0;border-radius:12px;box-shadow:0 18px 42px rgba(0,0,0,.24)}.site-dropdown:hover .site-dropdown-menu,.site-dropdown:focus-within .site-dropdown-menu,.site-dropdown.open .site-dropdown-menu{display:grid}.site-dropdown-menu a{display:block;padding:10px 12px;border-radius:8px;color:#1d2c47!important;text-decoration:none;font-size:14px;font-weight:650}.site-dropdown-menu a:hover{background:#eef5ff;color:#1769ff!important}.site-dropdown-menu small{display:block;margin-top:2px;color:#718096;font-size:11px;font-weight:500}</style>
<header class="sitebar"><div class="sitebar-inner">@include('partials.logo')<nav class="site-nav"><div class="site-dropdown"><button class="site-dropdown-toggle" type="button" aria-expanded="false">Find Jobs</button><div class="site-dropdown-menu"><a href="{{route('home')}}#jobs">Find Jobs<small>Search verified openings</small></a><a href="{{route('companies.index')}}">Companies<small>Browse company profiles</small></a><a href="{{route('jobs.hr')}}">Jobs Posted by HR<small>Direct recruiter opportunities</small></a></div></div><div class="site-dropdown"><button class="site-dropdown-toggle" type="button" aria-expanded="false">Learning</button><div class="site-dropdown-menu"><a href="{{route('learning.index')}}">Learning<small>Courses and interview preparation</small></a><a href="{{route('practice')}}">Practice<small>Code and test your skills</small></a></div></div><div class="site-dropdown"><button class="site-dropdown-toggle" type="button" aria-expanded="false">Resume Builder</button><div class="site-dropdown-menu"><a href="{{route('resume.builder')}}">Resume Builder<small>Create and edit your resume</small></a><a href="{{route('resume.builder')}}#ats-preview">ATS-Friendly Resume<small>Preview the ATS-readable format</small></a></div></div><a href="{{route('about')}}">About Us</a><a href="{{route('contact')}}">Contact</a><a class="nav-action" href="{{route('news.index')}}">Latest in Tech</a>@auth @if(auth()->user()->role_code===2||auth()->user()->role==='admin')<a href="{{route('admin.dashboard')}}">Owner Dashboard</a>@elseif(auth()->user()->role_code===0||auth()->user()->role==='employer')<a href="{{route('employer.dashboard')}}">HR Dashboard</a>@else @php($navProfile=auth()->user()->candidateProfile)<a class="candidate-nav" href="{{route('dashboard')}}">@if($navProfile?->avatar_url)<img src="{{$navProfile->avatar_url}}" alt="Profile">@else<span>{{strtoupper(substr(auth()->user()->name,0,1))}}</span>@endif<b>{{auth()->user()->name}}</b></a>@endif<form method="post" action="{{route('logout')}}" style="margin:0">@csrf<button class="nav-action">Logout</button></form>@else<a class="nav-action" href="{{route('employer.login')}}">HR Login</a><a class="nav-action" href="{{route('owner.login')}}">Owner Login</a><a class="nav-action" href="{{route('register')}}">Student Sign Up</a>@endauth</nav></div></header>
@include('partials.alerts')
<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.site-dropdown-toggle').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();const menu=button.closest('.site-dropdown');document.querySelectorAll('.site-dropdown.open').forEach(item=>{if(item!==menu){item.classList.remove('open');item.querySelector('.site-dropdown-toggle')?.setAttribute('aria-expanded','false')}});const open=menu.classList.toggle('open');button.setAttribute('aria-expanded',String(open))}));document.addEventListener('click',()=>document.querySelectorAll('.site-dropdown.open').forEach(item=>{item.classList.remove('open');item.querySelector('.site-dropdown-toggle')?.setAttribute('aria-expanded','false')}))})</script>
<script>
document.addEventListener('DOMContentLoaded', () => {
    const nav = document.querySelector('.site-nav');
    const jobsMenu = nav?.querySelector('.site-dropdown');
    if (nav && jobsMenu && !nav.querySelector('.companies-nav-link')) {
        const companies = document.createElement('a');
        companies.className = 'companies-nav-link';
        companies.href = @json(route('companies.index'));
        companies.textContent = 'Companies';
        jobsMenu.insertAdjacentElement('afterend', companies);
    }
});
</script>
<style>
.sitebar .site-nav{gap:10px!important}.sitebar .site-nav>.site-dropdown,.sitebar .site-nav>a:not(.candidate-nav),.sitebar .site-nav>form{margin-left:0!important}.sitebar .site-nav>.site-dropdown>.site-dropdown-toggle,.sitebar .site-nav>a:not(.candidate-nav),.sitebar .site-nav>form>.nav-action,.sitebar .site-nav>form>.site-auth{display:inline-flex!important;align-items:center!important;justify-content:center!important;min-width:112px!important;width:auto!important;height:44px!important;padding:0 15px!important;border:1px solid #7095c2!important;border-radius:9px!important;background:#315f96!important;color:#fff!important;font:750 14px/1 Inter,system-ui,sans-serif!important;text-decoration:none!important;white-space:nowrap!important;box-shadow:0 4px 12px rgba(8,28,54,.12)!important;cursor:pointer!important;transition:background-color .18s ease,border-color .18s ease,transform .18s ease,box-shadow .18s ease!important}.sitebar .site-nav>.site-dropdown>.site-dropdown-toggle:hover,.sitebar .site-nav>a:not(.candidate-nav):hover,.sitebar .site-nav>form>.nav-action:hover,.sitebar .site-nav>form>.site-auth:hover{border-color:#9fc1e8!important;background:#3f73ad!important;color:#fff!important;transform:translateY(-1px)!important;box-shadow:0 7px 16px rgba(8,28,54,.2)!important}.sitebar .site-nav>.site-dropdown>.site-dropdown-toggle:focus-visible,.sitebar .site-nav>a:not(.candidate-nav):focus-visible,.sitebar .site-nav>form>button:focus-visible{outline:3px solid rgba(159,193,232,.42)!important;outline-offset:3px!important}.sitebar .site-dropdown-toggle:after{margin-left:7px}@media(max-width:1050px){.sitebar .site-nav>.site-dropdown,.sitebar .site-nav>a:not(.candidate-nav),.sitebar .site-nav>form{flex:1 1 140px}.sitebar .site-nav>.site-dropdown>.site-dropdown-toggle,.sitebar .site-nav>a:not(.candidate-nav),.sitebar .site-nav>form>.nav-action,.sitebar .site-nav>form>.site-auth{width:100%!important}}
</style>
