<style>
.sitebar[data-shared-header]{background:#203f68;color:#fff;position:relative;z-index:200;width:100%;height:auto;min-height:84px;padding:12px 0;box-sizing:border-box}.sitebar[data-shared-header] .sitebar-inner{width:min(1700px,calc(100% - 32px));margin:auto;display:flex;align-items:center;justify-content:space-between;gap:24px;height:auto}.sitebar[data-shared-header] .site-logo{background:white;padding:4px 12px;border-radius:8px;display:block;flex:0 0 auto}.sitebar[data-shared-header] .site-logo img{display:block;width:140px;height:55px;object-fit:contain}.sitebar[data-shared-header] .site-nav{display:flex;flex-wrap:wrap;align-items:center;justify-content:flex-end;gap:9px;min-width:0;overflow:visible}.header-group{position:relative}.header-group>summary{list-style:none;display:flex;align-items:center;justify-content:center;gap:10px;padding:14px 16px;border:1px solid #7095c2;border-radius:9px;background:#315f96;color:#fff;font:700 14px/1.2 Inter,system-ui,sans-serif;cursor:pointer;white-space:nowrap}.header-group>summary::-webkit-details-marker{display:none}.header-group>summary:after{content:'';width:6px;height:6px;border-right:2px solid;border-bottom:2px solid;transform:rotate(45deg);margin-top:-4px}.header-group[open]>summary{background:#224977}.header-group[open]>summary:after{transform:rotate(225deg);margin-top:3px}.header-menu{position:absolute;top:calc(100% + 8px);right:0;display:grid;min-width:230px;max-width:calc(100vw - 32px);padding:8px;background:#fff;border:1px solid #dbe4f0;border-radius:10px;box-shadow:0 16px 35px #06192c40}.sitebar[data-shared-header] .header-menu a,.sitebar[data-shared-header] .header-menu button{display:block;text-align:left;width:100%;padding:12px;border:0;border-radius:6px;background:transparent;color:#16324d!important;font:600 14px/1.4 Inter,system-ui,sans-serif;text-decoration:none;white-space:normal;box-sizing:border-box;cursor:pointer}.header-menu form{margin:0}.sitebar[data-shared-header] .header-menu a:hover,.sitebar[data-shared-header] .header-menu button:hover{background:#edf4fc}.header-group>summary:focus-visible,.header-menu a:focus-visible,.header-menu button:focus-visible{outline:3px solid #e3ab44;outline-offset:2px}@media(max-width:760px){.sitebar[data-shared-header] .sitebar-inner{flex-direction:column;align-items:flex-start;gap:12px}.sitebar[data-shared-header] .site-nav{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));width:100%;gap:8px}.header-group>summary{font-size:12px;padding:12px 7px;gap:7px;white-space:normal;min-height:42px;box-sizing:border-box}.header-group:nth-child(3n+1) .header-menu{left:0;right:auto}.header-group:nth-child(3n+2) .header-menu{left:50%;right:auto;transform:translateX(-50%)}.header-menu{min-width:210px}.sitebar[data-shared-header] .site-logo img{width:112px;height:44px}}
</style>
<header class="sitebar" data-shared-header><div class="sitebar-inner"><a class="site-logo" href="{{ route('home') }}" aria-label="Ascendia home"><img src="{{ asset('images/ascendia-logo.png') }}" alt="Ascendia"></a><nav class="site-nav" aria-label="Main navigation">
@foreach(['Find Jobs'=>[['home','Find Jobs'],['companies.index','Companies'],['jobs.hr','Jobs Posted by HR']],'Learning'=>[['learning.index','Learning'],['practice','Practice']],'Resume Builder'=>[['resume.builder','Resume Builder']],'About'=>[['about','About Us'],['contact','Contact']],'Explore'=>[['company.experiences.index','Company Experiences'],['industrial.index','Industries'],['news.index','Latest in Tech']]] as $label=>$links)
<details class="header-group"><summary>{{ $label }}</summary><div class="header-menu">@foreach($links as [$route,$text])<a href="{{ route($route) }}{{ $route === 'home' ? '#jobs' : '' }}">{{ $text }}</a>@endforeach @if($label === 'Resume Builder')<a href="{{ route('resume.builder') }}#ats-preview">ATS-Friendly Resume</a>@endif</div></details>
@endforeach
<details class="header-group"><summary>Account</summary><div class="header-menu">@auth
@if(auth()->user()->role_code===2 || auth()->user()->role==='admin')<a href="{{ route('admin.dashboard') }}">Owner Dashboard</a><a href="{{ route('admin.industrial.index') }}">Industrial Manager</a>@elseif(auth()->user()->role_code===0 || auth()->user()->role==='employer')<a href="{{ route('employer.dashboard') }}">HR Dashboard</a>@else<a href="{{ route('dashboard') }}">{{ auth()->user()->name }} &middot; Dashboard</a>@endif
<form method="post" action="{{ route('logout') }}">@csrf<button type="submit">Logout</button></form>
@else<a href="{{ route('employer.login') }}">HR Login</a><a href="{{ route('owner.login') }}">Owner Login</a><a href="{{ route('register') }}">Student Sign Up</a>@endauth</div></details>
</nav></div></header>
<script>
(()=>{if(window.ascendiaHeaderBound)return;window.ascendiaHeaderBound=true;document.addEventListener('click',event=>{const selected=event.target instanceof Element?event.target.closest('.header-group'):null;document.querySelectorAll('[data-shared-header] .header-group[open]').forEach(group=>{if(group!==selected)group.open=false;});});document.addEventListener('keydown',event=>{if(event.key==='Escape'){document.querySelectorAll('[data-shared-header] .header-group[open]').forEach(group=>{group.open=false;group.querySelector('summary').focus();});}});})();
</script>
