<style>.sitebar{height:72px;background:#0b1933;color:#fff}.sitebar-inner{width:min(1160px,calc(100% - 32px));height:100%;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:24px}.site-logo{font-size:22px;font-weight:850;color:#fff!important;text-decoration:none}.site-logo b{color:#60a5fa}.site-nav{display:flex;align-items:center;gap:20px;flex-wrap:wrap}.site-nav a{color:#cbd5e1!important;text-decoration:none;font-size:14px}.site-nav a:hover{color:#fff!important}.site-auth{padding:9px 14px;border-radius:8px;background:#2563eb;color:#fff!important;font-weight:750}@media(max-width:820px){.sitebar{height:auto;padding:16px 0}.sitebar-inner{align-items:flex-start;flex-direction:column}.site-nav{gap:12px}}</style>
<header class="sitebar"><div class="sitebar-inner"><a class="site-logo" href="{{ route('home') }}" aria-label="Ascendia home"><img src="{{asset('images/ascendia-logo.png')}}" alt="Ascendia"></a><nav class="site-nav"><a href="{{ route('home') }}#jobs">Jobs</a><a href="{{ route('home') }}#companies">Companies</a><a href="{{ route('learning.index') }}">Learning</a><a href="{{ route('practice') }}">Practice</a><a href="{{ route('about') }}">About us</a>@auth @if(auth()->user()->role_code===2||auth()->user()->role==='admin')<a href="{{route('admin.dashboard')}}">Owner Dashboard</a>@elseif(auth()->user()->role_code===0||auth()->user()->role==='employer')<a href="{{route('employer.dashboard')}}">HR Dashboard</a>@else @php $navProfile=auth()->user()->candidateProfile; @endphp<a class="candidate-nav" href="{{route('dashboard')}}">@if($navProfile?->avatar_url)<img src="{{$navProfile->avatar_url}}" alt="Profile">@else<span>{{strtoupper(substr(auth()->user()->name,0,1))}}</span>@endif <b>{{auth()->user()->name}}</b></a>@endif<form method="post" action="{{ route('logout') }}" style="margin:0">@csrf<button class="site-auth" style="border:0">Logout</button></form>@else<a class="btn btn-primary" href="{{route('employer.login')}}">HR Login</a><a class="btn btn-primary" href="{{route('owner.login')}}">Owner Login</a><a class="btn btn-primary site-auth" href="{{route('register')}}">Student Sign Up</a>@endauth</nav></div></header>
<style>.site-logo{display:block!important;padding:3px 9px;border-radius:8px;background:#fff}.site-logo img{display:block;width:145px;height:55px;object-fit:contain}.candidate-nav{display:flex!important;align-items:center;gap:8px}.candidate-nav img,.candidate-nav span{width:36px;height:36px;border-radius:50%;object-fit:cover;background:#2563eb;display:grid;place-items:center;color:#fff}.candidate-nav b{max-width:110px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<style>.site-nav .btn{width:132px!important;min-width:132px;height:40px;padding:0 10px!important;display:inline-flex!important;align-items:center;justify-content:center;color:#fff!important;white-space:nowrap}.site-nav .hr-jobs-link{width:auto!important;min-width:172px!important}</style>
@include('partials.alerts')
<script>document.addEventListener('DOMContentLoaded',()=>{const about=[...document.querySelectorAll('.site-nav a')].find(a=>a.textContent.trim().toLowerCase()==='about us');if(about&&!document.querySelector('.site-nav [data-resume-builder]'))about.insertAdjacentHTML('afterend','<a data-resume-builder href="{{route('resume.builder')}}">Resume Builder</a>')})</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const jobs=[...document.querySelectorAll('.site-nav a')].find(a=>a.textContent.trim().toLowerCase()==='jobs');if(jobs&&!document.querySelector('[data-hr-jobs]'))jobs.insertAdjacentHTML('afterend','<a class="btn btn-primary hr-jobs-link" data-hr-jobs href="{{route('jobs.hr')}}">Jobs Posted by HR</a>')})</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const companies=[...document.querySelectorAll('.site-nav a')].find(a=>a.textContent.trim().toLowerCase()==='companies');if(companies)companies.href='{{route('companies.index')}}'})</script>
