@extends('layouts.site')
@section('title','Candidate Dashboard')
@push('styles')
<style>
.application-tabs{display:flex;gap:8px;overflow:auto;margin:18px 0 8px;padding-bottom:8px}.application-tab{border:1px solid #cfd9ea;border-radius:999px;background:#fff;color:#53627a;padding:8px 13px;white-space:nowrap;cursor:pointer}.application-tab.active{border-color:#2563eb;background:#2563eb;color:#fff}.application{grid-template-columns:minmax(0,1fr) 120px 170px 100px!important}.application strong,.application small{display:block}.application small{margin-top:5px;color:#667085}
</style>
@endpush
@push('styles')<style>.dash{display:grid;grid-template-columns:330px 1fr;gap:22px}.profile{padding:25px}.avatar{width:90px;height:90px;border-radius:50%;object-fit:cover;background:#eaf1ff;display:grid;place-items:center;color:#2563eb;font-size:30px;font-weight:850}.completion{height:9px;background:#edf2f7;border-radius:10px;overflow:hidden}.completion span{display:block;height:100%;background:#2563eb}.profile-form{display:grid;grid-template-columns:1fr 1fr;gap:15px}.profile-fieldset{display:contents}.profile-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.profile-heading h1{margin-top:0}.full{grid-column:1/-1}.resume{padding:20px;margin-top:18px;background:#f8fafc;border-radius:10px}.success,.errors{padding:12px;border-radius:8px;margin-bottom:16px}.success{background:#ecfdf3;color:#087443}.errors{background:#fff1f2;color:#b42318}.pill{display:inline-block;padding:6px 10px;border-radius:20px;background:#eef4ff;color:#2457bd;font-weight:750}.salary-fields{display:grid;grid-template-columns:122px minmax(0,1fr);gap:8px}.currency-picker{position:relative}.currency-picker select{padding-left:40px}.currency-symbol{position:absolute;left:13px;top:50%;transform:translateY(-50%);z-index:1;color:#1769ff;font-size:18px;font-weight:800;pointer-events:none}.salary-amount::placeholder{font-size:13px;color:#9aa5b1}.applications{padding:24px;margin-top:20px}.application{display:grid;grid-template-columns:1fr 160px 170px;gap:15px;padding:15px 0;border-top:1px solid #e4e9f2}@media(max-width:850px){.dash{grid-template-columns:1fr}.profile-form{grid-template-columns:1fr}.full{grid-column:auto}.application{grid-template-columns:1fr}}</style>@endpush
@section('content')
<section class="section"><div class="container">
@if(session('success'))<div class="success">{{session('success')}}</div>@endif
<div class="dash"><aside class="panel profile">
@if($profile->avatar_url)<img class="avatar" src="{{$profile->avatar_url}}" alt="Profile">@else<div class="avatar">{{strtoupper(substr($profile->first_name?:auth()->user()->name,0,1))}}</div>@endif
<h2>{{$profile->first_name}} {{$profile->last_name}}</h2><p>{{$profile->headline?:'Add a professional headline'}}</p><strong>Profile completion: {{$profile->profile_completion}}%</strong><div class="completion"><span style="width:{{$profile->profile_completion}}%"></span></div><p><strong>{{auth()->user()->email}}</strong><br>{{$profile->phone?:'Add phone number'}}<br>{{$profile->location?:'Add location'}}</p>
<div id="resume-builder" class="resume"><h3>Resume Profile Builder</h3><p>Upload a text-based PDF to extract profile fields. Existing values are not overwritten.</p>@php($resume=$profile->resumes->first())@if($resume)<strong>{{$resume->original_name}}</strong><br><span class="pill">{{ucwords(str_replace('_',' ',$resume->parsing_status))}}</span>@if($resume->parsed_data && count($resume->parsed_data['skills']??[]))<p><strong>Skills found:</strong> {{implode(', ',array_slice($resume->parsed_data['skills'],0,10))}}</p>@endif @if($resume->parse_error)<div class="errors">{{$resume->parse_error}}</div>@endif @endif<form id="resume-form" method="post" action="{{route('candidate.resume.upload')}}" enctype="multipart/form-data">@csrf<input class="field" type="file" name="resume" accept="application/pdf" required><button id="resume-btn" class="btn btn-primary" style="margin-top:10px">Upload and extract profile</button></form></div>
</aside><main><form id="candidate-profile-form" class="panel profile profile-form" method="post" action="{{route('candidate.profile.update')}}" enctype="multipart/form-data">@csrf @method('PUT')
<input type="hidden" name="profile_id" value="{{$profile->id}}">
<div class="full profile-heading"><div><h1>Candidate Profile</h1><p>Review extracted information, complete the remaining fields, then save.</p></div>@if($profile->exists)<button id="edit-profile" type="button" class="btn btn-outline-primary">Edit Profile</button>@endif</div>
<fieldset id="profile-fields" class="profile-fieldset" @disabled($profile->exists && !$errors->any())>
<div class="full"><label class="label">Email Address <span style="color:#dc2626">*</span></label><input class="field" type="email" name="email" value="{{old('email',auth()->user()->email)}}" required readonly><small style="color:#667085">Your verified account email uniquely identifies this profile.</small></div>
<div><label class="label">First Name <span style="color:#dc2626">*</span></label><input class="field" name="first_name" value="{{old('first_name',$profile->first_name)}}" required></div><div><label class="label">Last Name</label><input class="field" name="last_name" value="{{old('last_name',$profile->last_name)}}"></div>
@include('candidate.profile-fields')
<div><label class="label">Professional Headline</label><select class="field" name="headline"><option value="">Select headline</option>@foreach(config('recruitment.roles',[]) as $role)<option value="{{$role}}" @selected(old('headline',$profile->headline)===$role)>{{$role}}</option>@endforeach</select></div>
<div><label class="label">Current Company</label><input id="company" class="field" name="current_company" list="company-results" autocomplete="off" value="{{old('current_company',$profile->current_company)}}"><datalist id="company-results"></datalist></div>
<div><label class="label">Current Designation</label><select class="field" name="current_designation"><option value="">Select designation</option>@foreach(config('recruitment.roles',[]) as $role)<option value="{{$role}}" @selected(old('current_designation',$profile->current_designation)===$role)>{{$role}}</option>@endforeach</select></div>
<div><label class="label">Notice Period</label><select class="field" name="notice_period"><option value="">Select notice period</option>@foreach(['Immediate','15 days','1 month','2 months','3 months','More than 3 months'] as $v)<option value="{{$v}}" @selected(old('notice_period',$profile->notice_period)===$v)>{{$v}}</option>@endforeach</select></div>
<div><label class="label">Experience</label><select class="field" name="experience_years">@foreach(range(0,30) as $v)<option value="{{$v}}" @selected((int)old('experience_years',$profile->experience_years)===$v)>{{$v?$v.' years':'Fresher'}}</option>@endforeach</select></div>
@php($currencies=['INR'=>'₹','USD'=>'$','CAD'=>'C$','AUD'=>'A$','EUR'=>'€','GBP'=>'£','AED'=>'د.إ','JMD'=>'J$','JPY'=>'¥'])
<div><label class="label">Current Salary</label><div class="salary-fields"><div class="currency-picker"><span class="currency-symbol" data-symbol-for="current_salary_currency">{{$currencies[old('current_salary_currency',$profile->current_salary_currency?:$profile->salary_currency?:'INR')]??'₹'}}</span><select class="field currency-select" name="current_salary_currency" id="current_salary_currency">@foreach($currencies as $code=>$symbol)<option value="{{$code}}" data-symbol="{{$symbol}}" @selected(old('current_salary_currency',$profile->current_salary_currency?:$profile->salary_currency?:'INR')===$code)>{{$code}}</option>@endforeach</select></div><input class="field salary-amount" type="number" min="0" step="0.01" name="current_salary" placeholder="Enter amount" value="{{old('current_salary',$profile->current_salary)}}"></div></div>
<div><label class="label">Expected Salary</label><div class="salary-fields"><div class="currency-picker"><span class="currency-symbol" data-symbol-for="expected_salary_currency">{{$currencies[old('expected_salary_currency',$profile->expected_salary_currency?:$profile->salary_currency?:'INR')]??'₹'}}</span><select class="field currency-select" name="expected_salary_currency" id="expected_salary_currency">@foreach($currencies as $code=>$symbol)<option value="{{$code}}" data-symbol="{{$symbol}}" @selected(old('expected_salary_currency',$profile->expected_salary_currency?:$profile->salary_currency?:'INR')===$code)>{{$code}}</option>@endforeach</select></div><input class="field salary-amount" type="number" min="0" step="0.01" name="expected_salary" placeholder="Enter amount" value="{{old('expected_salary',$profile->expected_salary)}}"></div></div>
<div><label class="label">Preferred Role</label><select class="field" name="preferred_role"><option value="">Select preferred role</option>@foreach(config('recruitment.roles',[]) as $role)<option value="{{$role}}" @selected(old('preferred_role',$profile->preferred_role)===$role)>{{$role}}</option>@endforeach</select></div>
<div class="full"><label class="label">Address</label><textarea class="field" name="address">{{old('address',$profile->address)}}</textarea></div><div class="full"><label class="label">Bio</label><textarea class="field" name="bio">{{old('bio',$profile->bio)}}</textarea></div><div class="full"><label class="label">Education</label><textarea class="field" name="education">{{old('education',$profile->education)}}</textarea></div><div class="full"><label class="label">Profile Image</label><input class="field" type="file" name="avatar" accept="image/*"></div><button id="save-profile" class="btn btn-primary" type="submit">Save Profile</button>
</fieldset>
</form></main></div>
<section class="panel applications"><h2>My Job Applications</h2><div class="application-tabs" role="tablist">@foreach(['all'=>'All','applied'=>'Applied','viewed_by_recruiter'=>'Viewed by Recruiter','in_progress'=>'In Progress','rejected'=>'Rejected','withdrawn'=>'Withdrawn','joined'=>'Joined'] as $value=>$label)<button type="button" class="application-tab {{$value==='all'?'active':''}}" data-application-filter="{{$value}}">{{$label}}</button>@endforeach</div><div id="application-list">@forelse($applications as $application)<article class="application" data-application-status="{{$application->status}}"><div><strong>{{$application->job->title}}</strong><small>{{$application->job->company->name}}</small></div><span>{{$application->applied_at?->format('d M Y')}}</span><span class="pill">{{ucwords(str_replace('_',' ',$application->status))}}</span>@if(in_array($application->status,['applied','viewed_by_recruiter','in_progress'],true))<form method="post" action="{{route('applications.withdraw',$application)}}">@csrf @method('PATCH')<button class="btn btn-outline-danger btn-sm" type="submit">Withdraw</button></form>@else<span></span>@endif</article>@empty<p>You have not applied for a portal job yet.</p>@endforelse</div><p id="no-status-applications" hidden>No applications exist in this status.</p>{{$applications->links()}}</section>
</div></section>
@if(session('profile_saved'))
<div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content text-center p-4">
      <div class="modal-body">
        <svg class="text-success mb-3" xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" viewBox="0 0 16 16" aria-hidden="true">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l4.992-6.005a.75.75 0 0 0-.01-1.05z"/>
        </svg>
        <h4 class="fw-bold" id="successModalLabel">Success!</h4>
        <p class="text-muted">Your profile has been saved successfully.</p>
        <button type="button" class="btn btn-success px-4" data-bs-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>
@endif
<script>let companyTimer;document.getElementById('company').addEventListener('input',function(){clearTimeout(companyTimer);const q=this.value;if(q.length<2)return;companyTimer=setTimeout(async()=>{const response=await fetch(`{{route('profile.lookups.companies')}}?q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}});const list=document.getElementById('company-results');list.innerHTML='';(await response.json()).forEach(name=>list.append(new Option(name,name)));},250);});document.querySelectorAll('.currency-select').forEach(select=>select.addEventListener('change',()=>{document.querySelector(`[data-symbol-for="${select.id}"]`).textContent=select.options[select.selectedIndex].dataset.symbol;}));document.getElementById('edit-profile')?.addEventListener('click',event=>{document.getElementById('profile-fields').disabled=false;event.currentTarget.disabled=true;document.querySelector('#candidate-profile-form .field')?.focus();document.getElementById('save-profile').scrollIntoView({behavior:'smooth',block:'nearest'});});document.getElementById('resume-form').addEventListener('submit',()=>{const button=document.getElementById('resume-btn');button.disabled=true;button.textContent='Extracting profile...';});</script>
@if(session('profile_saved'))
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script>document.addEventListener('DOMContentLoaded',()=>bootstrap.Modal.getOrCreateInstance(document.getElementById('successModal')).show());</script>
@endpush
@endif
@push('scripts')
<script>document.querySelectorAll('[data-application-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-application-filter]').forEach(tab=>tab.classList.remove('active'));button.classList.add('active');let visible=0;document.querySelectorAll('[data-application-status]').forEach(card=>{const show=button.dataset.applicationFilter==='all'||card.dataset.applicationStatus===button.dataset.applicationFilter;card.hidden=!show;if(show)visible++});document.getElementById('no-status-applications').hidden=visible>0;}));</script>
@endpush
@endsection
