@extends('layouts.site')
@section('title', $company->name.' Careers — Ascendia')
@push('styles')
<style>
.company-hero{background:linear-gradient(135deg,#eef4ff,#f8fbff);padding:55px 0 28px;border-bottom:1px solid #dfe8f5}.company-summary{display:flex;gap:22px;align-items:center}.company-logo-large{width:125px;height:125px;display:grid;place-items:center;border:1px solid #dbe4f2;border-radius:22px;background:#fff;color:#2563eb;font-size:36px;font-weight:900;overflow:hidden}.company-logo-large img{width:100%;height:100%;object-fit:contain}.company-title h1{font-size:38px;margin:0 0 8px}.meta-tags,.job-skills{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.meta-tag,.job-skill{padding:6px 9px;border:1px solid #d8e2f0;border-radius:999px;background:#fff;color:#52627d;font-size:12px}.company-actions{margin-left:auto;display:flex;gap:10px}.company-tabs{display:flex;gap:30px;border-bottom:1px solid #dde5f0;margin-top:28px}.company-tabs a{padding:14px 3px;color:#64748b;text-decoration:none;font-weight:750}.company-tabs a.active{color:#16325c;border-bottom:3px solid #2563eb}.company-content{padding:32px 0 60px}.department-box{padding:25px;background:#f4f8ff;border:1px solid #dce7f8;border-radius:20px}.department-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.department-card{display:block;padding:18px;border:1px solid #dce5f2;border-radius:14px;background:#fff;color:#152849;text-decoration:none}.department-card strong,.department-card span{display:block}.department-card span{margin-top:8px;color:#2563eb}.job-area{margin-top:34px}.job-toolbar{display:flex;align-items:flex-end;justify-content:space-between;gap:15px;margin-bottom:18px}.job-filters{display:flex;gap:9px;flex-wrap:wrap}.job-filters select{min-width:165px}.company-job-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.company-job{padding:21px;border:1px solid #dfe7f2;border-radius:16px;background:#fff}.company-job h3{font-size:18px;margin:6px 0 10px}.job-meta{color:#64748b}.job-skill{background:#eef4ff;color:#315fba}.job-bottom{display:flex;align-items:center;justify-content:space-between;margin-top:18px;padding-top:15px;border-top:1px solid #edf1f6}.overview{margin-top:28px;padding:25px}.overview p{line-height:1.75;color:#52627d}.empty-jobs{text-align:center;padding:45px}.pagination-wrap{margin-top:25px}@media(max-width:900px){.company-summary{align-items:flex-start;flex-wrap:wrap}.company-actions{margin-left:0;width:100%}.department-grid,.company-job-grid{grid-template-columns:1fr 1fr}.job-toolbar{align-items:flex-start;flex-direction:column}}@media(max-width:600px){.company-logo-large{width:88px;height:88px}.company-title h1{font-size:28px}.department-grid,.company-job-grid{grid-template-columns:1fr}}
.company-job-grid{grid-template-columns:1fr}.company-job{padding:24px;border-radius:18px;transition:.2s ease}.company-job:hover{border-color:#9dbbf3;box-shadow:0 12px 30px rgba(32,74,135,.09);transform:translateY(-2px)}.company-job-head{display:flex;align-items:flex-start;gap:15px}.job-company-logo{width:58px;height:58px;display:grid;place-items:center;flex:0 0 auto;border:1px solid #dce5f2;border-radius:12px;background:#f7faff;color:#2563eb;font-weight:850;overflow:hidden}.job-company-logo img{width:100%;height:100%;object-fit:contain}.company-job h3{font-size:20px;margin:0 0 7px}.job-facts{display:flex;gap:16px;flex-wrap:wrap;margin-top:15px;color:#52627d;font-size:14px}.job-description{margin:15px 0 0;color:#52627d;line-height:1.65}.company-insight{margin-top:20px;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.company-insight>div{padding:16px;border:1px solid #dfe7f2;border-radius:14px;background:#f5f9ff}.company-insight strong,.company-insight span{display:block}.company-insight strong{font-size:22px;color:#1f5fc4}.company-insight span{font-size:12px;color:#64748b;margin-top:4px}@media(max-width:600px){.company-insight{grid-template-columns:1fr}.company-job-head{align-items:flex-start}}
</style>
@endpush
@section('content')
<section class="company-hero"><div class="container">
<div class="company-summary"><div class="company-logo-large">@if($company->logo_url)<img src="{{$company->logo_url}}" alt="{{$company->name}} logo">@else{{strtoupper(substr($company->name,0,2))}}@endif</div><div class="company-title"><h1>{{$company->name}}</h1><div>{{$company->industry?:$company->sector?:'Organization'}} · {{$company->country?:'Global'}}</div>@if(($company->published_reviews_count ?? 0)>0)<a href="#company-reviews" style="display:inline-block;margin-top:8px;color:#d97706;font-weight:800;text-decoration:none">★ {{number_format((float)$company->published_reviews_avg_rating,1)}} · {{$company->published_reviews_count}} {{\Illuminate\Support\Str::plural('review',$company->published_reviews_count)}}</a>@endif<div class="meta-tags">@foreach($company->categories->take(5) as $category)<span class="meta-tag">{{$category->symbol}} {{$category->name}}</span>@endforeach @if($company->company_type)<span class="meta-tag">{{str_replace('_',' ',ucwords($company->company_type))}}</span>@endif</div></div><div class="company-actions">@if($company->website)<a class="btn" href="{{$company->website}}" target="_blank" rel="noopener noreferrer">Official website</a>@endif @if($company->careers_url)<a class="btn btn-primary" href="{{$company->careers_url}}" target="_blank" rel="noopener noreferrer">Official careers</a>@endif</div></div>
<nav class="company-tabs"><a href="#overview">Overview</a><a class="active" href="#jobs">Jobs ({{number_format($company->active_jobs_count)}})</a><a href="#company-reviews">Reviews ({{$company->published_reviews_count ?? 0}})</a></nav>
</div></section>
<div class="container company-content">
@if($departments->isNotEmpty())<section class="department-box"><h2>Departments hiring at {{$company->name}}</h2><div class="department-grid">@foreach($departments->take(8) as $department)<a class="department-card" href="{{route('companies.show',[$company,'department'=>$department->label]).'#jobs'}}"><strong>{{$department->label}}</strong><span>{{number_format($department->jobs_count)}} {{Str::plural('opening',$department->jobs_count)}} →</span></a>@endforeach</div></section>@endif
<section class="job-area" id="jobs"><div class="job-toolbar"><div><h2>{{number_format($jobs->total())}} job openings at {{$company->name}}</h2><span class="job-meta">50 records per page</span></div><form class="job-filters" method="get"><select class="field" name="department"><option value="">All departments</option>@foreach($departments as $department)<option value="{{$department->label}}" @selected(($filters['department']??'')===$department->label)>{{$department->label}} ({{$department->jobs_count}})</option>@endforeach</select><select class="field" name="discipline"><option value="">All engineering disciplines</option>@foreach($disciplines as $discipline)<option value="{{$discipline->label}}" @selected(($filters['discipline']??'')===$discipline->label)>{{$discipline->label}} ({{$discipline->jobs_count}})</option>@endforeach</select><select class="field" name="location"><option value="">All locations</option>@foreach($locations as $location)<option value="{{$location->label}}" @selected(($filters['location']??'')===$location->label)>{{$location->label}} ({{$location->jobs_count}})</option>@endforeach</select><select class="field" name="experience"><option value="">All experience</option><option value="entry" @selected(($filters['experience']??'')==='entry')>Entry level</option><option value="experienced" @selected(($filters['experience']??'')==='experienced')>Experienced</option></select><button class="btn btn-primary">Apply filters</button></form></div>
<div class="company-insight"><div><strong>{{number_format($company->active_jobs_count)}}</strong><span>Active openings</span></div><div><strong>{{number_format($departments->count())}}</strong><span>Hiring departments</span></div><div><strong>{{number_format($disciplines->count())}}</strong><span>Engineering disciplines</span></div></div>
@if($jobs->isEmpty())<div class="panel empty-jobs"><h3>No jobs match these filters</h3><p>Clear a filter or visit the official careers page.</p></div>@else<div class="company-job-grid">@foreach($jobs as $job)<article class="company-job"><div class="company-job-head"><div class="job-company-logo">@if($company->logo_url)<img src="{{$company->logo_url}}" alt="">@else{{strtoupper(substr($company->name,0,2))}}@endif</div><div><h3>{{$job->title}}</h3><div class="job-meta">{{$company->name}} · {{$job->category?:$job->role?:'General'}}</div></div></div><div class="job-facts"><span>Experience: @if(!is_null($job->experience_min)){{$job->experience_min}}–{{$job->experience_max??'+'}} years @else Not specified @endif</span><span>@if(!is_null($job->salary_min)){{$job->salary_currency?:'INR'}} {{number_format($job->salary_min)}}@if(!is_null($job->salary_max))–{{number_format($job->salary_max)}}@endif @else Salary not disclosed @endif</span><span>{{$job->work_mode?:'Work mode not specified'}} · {{$job->location?:$job->country?:'Location not specified'}}</span></div>@if($job->description)<p class="job-description">{{Str::limit(strip_tags($job->description),190)}}</p>@endif<div class="job-skills">@foreach($job->skills->take(7) as $skill)<span class="job-skill">{{$skill->name}}</span>@endforeach</div><div class="job-bottom"><span class="job-meta">{{$job->posted_at?->diffForHumans()?:'Recently added'}}</span>@if($job->slug)<a class="btn btn-primary" href="{{route('jobs.show',$job)}}">View job</a>@elseif($job->external_url)<a class="btn btn-primary" href="{{$job->external_url}}" target="_blank" rel="noopener noreferrer">View official job</a>@endif</div></article>@endforeach</div><div class="pagination-wrap">{{$jobs->links()}}</div>@endif</section>
@include('companies.partials.reviews',['company'=>$company])
<section class="panel overview" id="overview"><h2>About {{$company->name}}</h2><p>{{$company->description?:'This profile uses information supplied by registered employers and supported official career sources. Job availability and counts are calculated from Ascendia records.'}}</p></section>
</div>
@endsection
