@extends('layouts.site')
@section('title','ATS Resume Builder — Ascendia')
@push('styles')
<style>
.resume-shell{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(340px,.7fr);gap:24px;align-items:start}.builder-top{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:22px}.builder-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.builder-card{margin-bottom:16px;padding:22px;border:1px solid #64748b;border-radius:14px;background:#fff}.builder-card h2{margin:0 0 16px;font-size:17px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.form-grid .wide{grid-column:1/-1}.repeat-entry{position:relative;margin:12px 0;padding:16px;border:1px solid #64748b;border-radius:11px;background:#f9fbff}.field,.form-control,.form-select{border:1px solid #475569!important}.remove-entry{position:absolute;right:12px;top:10px;border:0;background:transparent;color:#c62828;cursor:pointer}.required-star{color:#dc2626}.current-row{display:flex;align-items:center;gap:8px}.skill-list{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:10px}.skill-chip{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border-radius:999px;background:#eaf2ff;color:#1557c0;font-weight:700}.skill-chip button{border:0;background:transparent;color:inherit}.preview-wrap{position:sticky;top:88px}.preview-paper{min-height:720px;padding:38px;border:2px solid #475569;background:#fff;box-shadow:0 14px 35px rgba(16,33,62,.1);font-family:Arial,sans-serif;color:#111}.preview-paper.executive-grey{border-top:12px solid #334155}.preview-paper.modern-blue{border-top:12px solid #1769ff}.preview-paper h1{margin:0;font-size:25px}.preview-paper h2{margin:18px 0 7px;padding-bottom:4px;border-bottom:1px solid #333;font-size:13px;text-transform:uppercase}.preview-paper p{margin:4px 0}.preview-paper ul{margin:5px 0;padding-left:18px}.muted-note{color:#667085;font-size:13px}.score{font-weight:800;color:#1769ff}.save-message{min-height:20px;color:#087443;font-size:13px}@media(max-width:900px){.resume-shell{grid-template-columns:1fr}.preview-wrap{position:static}.form-grid{grid-template-columns:1fr}.form-grid .wide{grid-column:auto}}
</style>
@endpush
@section('content')
<section class="section"><div class="container">
<div class="builder-top"><div><span class="text-primary fw-bold">ATS RESUME BUILDER</span><h1>Build a clean, recruiter-ready resume</h1><p class="muted-note">Single-column structure, standard headings and text-first formatting improve ATS readability.</p></div><div class="builder-actions"><span id="save-message" class="save-message"></span><button id="save-resume" type="button" class="btn btn-outline-primary">Save Resume</button><button id="download-resume" type="button" class="btn btn-primary">Download PDF</button></div></div>
<div class="resume-shell"><form id="ats-resume-form">@csrf
<section class="builder-card"><h2>Personal Details</h2><div class="form-grid"><div><label class="label">Full Name <span class="required-star">*</span></label><input class="field live-field" id="full_name" value="{{$resume->full_name}}" required minlength="2"></div><div><label class="label">Target Role <span class="required-star">*</span></label><select class="field live-field" id="headline" required><option value="">Select role</option>@foreach($roles as $role)<option @selected($resume->headline===$role)>{{$role}}</option>@endforeach</select></div><div><label class="label">Email <span class="required-star">*</span></label><input class="field live-field" id="email" type="email" value="{{$resume->email}}" required></div><div><label class="label">Phone <span class="required-star">*</span></label><input class="field live-field" id="resume_phone" value="{{$resume->phone}}" required pattern="\+?[0-9 ()-]{8,19}"></div><div class="wide"><label class="label">Location <span class="required-star">*</span></label><input class="field live-field location-lookup" id="resume_location" value="{{$resume->location}}" list="location-options" required></div></div></section>
<section class="builder-card"><h2>Resume Theme</h2><select class="field live-field" id="template">@foreach($templates as $key=>$label)<option value="{{$key}}" @selected(($resume->template??'ats-classic')===$key)>{{$label}}</option>@endforeach</select></section>
<section class="builder-card"><h2>Professional Summary <span class="required-star">*</span></h2><textarea class="field live-field" id="summary" rows="4" minlength="60" maxlength="1200" required placeholder="Write at least 60 characters focused on experience and measurable impact.">{{$resume->summary}}</textarea></section>
<section class="builder-card"><h2>Skills</h2><div id="skill-list" class="skill-list"></div><div class="input-group"><input id="skill-input" class="form-control" placeholder="Add a relevant skill"><button id="add-skill" type="button" class="btn btn-outline-primary">Add</button></div></section>
<section class="builder-card"><div class="d-flex justify-content-between align-items-center"><h2>Experience</h2><button id="add-experience" type="button" class="btn btn-sm btn-outline-primary">+ Add Experience</button></div><div id="experience-list"></div></section>
<section class="builder-card"><div class="d-flex justify-content-between align-items-center"><h2>Education</h2><button id="add-education" type="button" class="btn btn-sm btn-outline-primary">+ Add Education</button></div><div id="education-list"></div></section>
<section class="builder-card"><div class="d-flex justify-content-between align-items-center"><h2>Professional Links</h2><button id="add-link" type="button" class="btn btn-sm btn-outline-primary">+ Add Link</button></div><div id="links-list"></div></section>
</form><aside id="ats-preview" class="preview-wrap"><div class="d-flex justify-content-between mb-2"><strong>Live ATS Preview</strong><span>Completeness: <b id="resume-score" class="score">{{$resume->completeness??0}}%</b></span></div><div id="resume-preview" class="preview-paper"></div><p class="muted-note mt-2">The PDF intentionally avoids columns, icons, images and decorative tables so applicant-tracking systems can parse it reliably.</p></aside></div>
</div><datalist id="company-options"></datalist><datalist id="location-options"></datalist><datalist id="institution-options"></datalist></section>
@endsection
@push('scripts')
<script>
const resumeState={skills:@json($resume->skills??[]),experience:@json($resume->experience??[]),education:@json($resume->education??[]),links:@json($resume->links??[])};
const roleOptions=@json($roles),degreeOptions=@json($degrees),linkOptions=@json($linkTypes),noticeOptions=@json($noticePeriods);
const byId=id=>document.getElementById(id),safe=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function field(id){return byId(id).value.trim()}
function renderSkills(){byId('skill-list').innerHTML=resumeState.skills.map((skill,index)=>`<span class="skill-chip">${safe(skill)}<button type="button" data-remove-skill="${index}" aria-label="Remove ${safe(skill)}">×</button></span>`).join('')}
function entryInput(placeholder,key,value='',attributes=''){return `<input class="field" placeholder="${placeholder}" data-key="${key}" value="${safe(value)}" ${attributes}>`}
function selectInput(key,items,value,label,attributes=''){return `<select class="field" data-key="${key}" ${attributes}><option value="">${label}</option>${items.map(v=>`<option ${v===value?'selected':''}>${safe(v)}</option>`).join('')}</select>`}
function renderExperience(){byId('experience-list').innerHTML=resumeState.experience.map((item,index)=>{item.currently_working=!!item.currently_working;return `<div class="repeat-entry" data-experience="${index}"><button class="remove-entry" type="button" data-remove-experience="${index}">Remove</button><div class="form-grid">${entryInput('Company *','company',item.company,'required list="company-options" class="company-lookup"')}${selectInput('role',roleOptions,item.role,'Role *','required')}${entryInput('Location *','location',item.location,'required list="location-options"') }<input class="field" type="month" data-key="start_date" value="${safe(item.start_date)}" title="Start Date" required><input class="field" type="month" data-key="end_date" value="${safe(item.end_date)}" title="End Date" ${item.currently_working?'disabled':'required'}>${selectInput('notice_period',noticeOptions,item.notice_period,'Notice period',item.currently_working?'required':'disabled')}<label class="wide current-row"><input type="checkbox" data-key="currently_working" ${item.currently_working?'checked':''}> Currently working here</label><div class="wide"><textarea class="field" rows="3" data-key="bullets" required minlength="15" placeholder="One measurable achievement per line *">${safe((item.bullets||[]).join('\n'))}</textarea></div></div></div>`}).join('')}
function renderEducation(){byId('education-list').innerHTML=resumeState.education.map((item,index)=>`<div class="repeat-entry" data-education="${index}"><button class="remove-entry" type="button" data-remove-education="${index}">Remove</button><div class="form-grid">${selectInput('degree',degreeOptions,item.degree,'Degree *','required')}${entryInput('College / University *','institution',item.institution,'required list="institution-options"')}${entryInput('Location *','location',item.location,'required list="location-options"') }<input class="field" type="number" min="1950" max="${new Date().getFullYear()+10}" placeholder="Graduation year *" data-key="end_date" value="${safe(item.end_date)}" required>${entryInput('CGPA or percentage','gpa',item.gpa,'inputmode="decimal"')}</div></div>`).join('')}
function renderLinks(){byId('links-list').innerHTML=resumeState.links.map((item,index)=>`<div class="repeat-entry" data-link="${index}"><button class="remove-entry" type="button" data-remove-link="${index}">Remove</button><div class="form-grid">${selectInput('label',linkOptions,item.label,'Profile type *','required')}${entryInput('https://... *','url',item.url,'type="url" required')}</div></div>`).join('')}
function renderPreview(){byId('resume-preview').className='preview-paper '+field('template');let html=`<h1>${safe(field('full_name')||'Your Name')}</h1>`;if(field('headline'))html+=`<p><strong>${safe(field('headline'))}</strong></p>`;html+=`<p>${[field('email'),field('resume_phone'),field('resume_location')].filter(Boolean).map(safe).join(' | ')}</p>`;if(field('summary'))html+=`<h2>Summary</h2><p>${safe(field('summary'))}</p>`;if(resumeState.skills.length)html+=`<h2>Skills</h2><p>${resumeState.skills.map(safe).join(', ')}</p>`;if(resumeState.experience.length){html+='<h2>Experience</h2>';resumeState.experience.forEach(item=>{html+=`<p><strong>${safe(item.role)}${item.company?' — '+safe(item.company):''}</strong></p><p>${[item.location,[item.start_date,item.currently_working?'Present':item.end_date].filter(Boolean).join(' - ')].filter(Boolean).map(safe).join(' | ')}</p>${(item.bullets||[]).length?'<ul>'+item.bullets.map(b=>`<li>${safe(b)}</li>`).join('')+'</ul>':''}`})}if(resumeState.education.length){html+='<h2>Education</h2>';resumeState.education.forEach(item=>html+=`<p><strong>${safe(item.degree)}${item.institution?' — '+safe(item.institution):''}</strong><br>${[item.location,item.end_date,item.gpa].filter(Boolean).map(safe).join(' | ')}</p>`)}if(resumeState.links.length){html+='<h2>Links</h2>';resumeState.links.forEach(item=>html+=`<p>${safe(item.label)}: ${safe(item.url)}</p>`)}byId('resume-preview').innerHTML=html;updateScore()}
function updateScore(){const checks=[field('full_name'),field('email'),field('resume_phone'),field('summary'),resumeState.skills.length,resumeState.experience.length,resumeState.education.length];byId('resume-score').textContent=Math.round(checks.filter(Boolean).length/checks.length*100)+'%'}
function payload(){return{full_name:field('full_name'),headline:field('headline'),email:field('email'),phone:field('resume_phone'),location:field('resume_location'),summary:field('summary'),template:field('template'),...resumeState}}
function addSkill(){const input=byId('skill-input'),value=input.value.trim();if(value&&!resumeState.skills.some(item=>item.toLowerCase()===value.toLowerCase()))resumeState.skills.push(value);input.value='';renderAll()}
function renderAll(){renderSkills();renderExperience();renderEducation();renderLinks();renderPreview()}
document.addEventListener('input',event=>{const parent=event.target.closest('[data-experience],[data-education],[data-link]');if(parent&&event.target.dataset.key){const collection=parent.hasAttribute('data-experience')?'experience':parent.hasAttribute('data-education')?'education':'links',index=Number(parent.dataset[collection]),key=event.target.dataset.key;resumeState[collection][index][key]=key==='bullets'?event.target.value.split('\n').map(v=>v.trim()).filter(Boolean):key==='currently_working'?event.target.checked:event.target.value;if(key==='currently_working'){resumeState[collection][index].end_date='';renderAll();return}}renderPreview()});
let lookupTimer;document.addEventListener('input',event=>{const list=event.target.getAttribute('list');if(!['company-options','location-options','institution-options'].includes(list))return;clearTimeout(lookupTimer);lookupTimer=setTimeout(async()=>{const urls={'company-options':'{{route('resume.companies')}}','location-options':'{{route('resume.locations')}}','institution-options':'{{route('resume.institutions')}}'};const response=await fetch(urls[list]+'?q='+encodeURIComponent(event.target.value.trim()),{headers:{Accept:'application/json'}});if(response.ok)byId(list).innerHTML=(await response.json()).map(value=>`<option value="${safe(value)}">`).join('')},180)});
document.addEventListener('click',event=>{for(const collection of ['skill','experience','education','link']){const button=event.target.closest(`[data-remove-${collection}]`);if(button){resumeState[collection==='skill'?'skills':collection].splice(Number(button.dataset[`remove${collection[0].toUpperCase()+collection.slice(1)}`]),1);renderAll();return}}});
byId('add-skill').addEventListener('click',addSkill);byId('skill-input').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();addSkill()}});byId('add-experience').addEventListener('click',()=>{resumeState.experience.push({company:'',role:'',location:'',start_date:'',end_date:'',bullets:[]});renderAll()});byId('add-education').addEventListener('click',()=>{resumeState.education.push({degree:'',institution:'',location:'',end_date:'',gpa:''});renderAll()});byId('add-link').addEventListener('click',()=>{resumeState.links.push({label:'',url:''});renderAll()});document.querySelectorAll('.live-field').forEach(input=>input.addEventListener('input',renderPreview));
async function saveResume(){const button=byId('save-resume'),message=byId('save-message');button.disabled=true;message.textContent='Saving...';try{const response=await fetch('{{route('resume.save')}}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('[name=_token]').value},body:JSON.stringify(payload())});const result=await response.json();if(!response.ok)throw new Error(Object.values(result.errors||{}).flat()[0]||'Unable to save resume.');message.textContent=result.message;byId('resume-score').textContent=result.completeness+'%';return true}catch(error){message.style.color='#b42318';message.textContent=error.message;return false}finally{button.disabled=false;setTimeout(()=>{message.style.color='';message.textContent=''},5000)}}
byId('save-resume').addEventListener('click',saveResume);byId('download-resume').addEventListener('click',async()=>{if(await saveResume())window.location.href='{{route('resume.download')}}'});renderAll();
</script>
@endpush
