@if(!empty($lesson['sections']))
<div class="lesson-sections">@foreach($lesson['sections'] as $section)<article class="lesson-section"><h3>{{$section['title']}}</h3><p>{{$section['body']}}</p></article>@endforeach</div>
@endif
@once
<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.lab').forEach(lab=>{const examples=JSON.parse(lab.dataset.examples),code=lab.querySelector('.lab-code'),input=lab.querySelector('.lab-input'),output=lab.querySelector('.lab-output'),tabs=[...lab.querySelectorAll('.language-tab')];const select=language=>{tabs.forEach(tab=>tab.classList.toggle('active',tab.dataset.language===language));code.value=examples[language].code};tabs.forEach(tab=>tab.addEventListener('click',()=>select(tab.dataset.language)));lab.querySelector('.lab-run').addEventListener('click',()=>{const values=input.value.split(/\r?\n/);if(values.length<4||!values[0].trim()||Number.isNaN(Number(values[1]))||Number.isNaN(Number(values[2]))||!values[3].trim()){output.textContent='Input error: use four lines — name, age, height and grade.';return}output.textContent='----- Student Details -----\nName: '+values[0].trim()+'\nAge: '+Number(values[1])+'\nHeight: '+Number(values[2])+'\nGrade: '+values[3].trim().charAt(0)});if(tabs[0])select(tabs[0].dataset.language)})});</script>
@endonce
@if(!empty($lesson['playground']))
<section class="lab" data-examples='@json($lesson['playground']['examples'])'><div class="lab-head"><strong>Interactive I/O code lab</strong><div class="language-tabs">@foreach($lesson['playground']['examples'] as $language=>$example)<button type="button" class="language-tab {{$loop->first?'active':''}}" data-language="{{$language}}">{{$example['label']}}</button>@endforeach</div></div><div class="lab-grid"><div class="lab-pane"><textarea class="lab-code" spellcheck="false"></textarea></div><div class="lab-io"><label><strong>Standard input</strong><textarea class="lab-input">{{$lesson['playground']['stdin']}}</textarea></label><button type="button" class="lab-run">Run guided example</button><div><strong>Output</strong><pre class="lab-output">Select Run to test the supplied input.</pre></div><p class="lab-note">This guided browser lab validates this lesson's input/output flow without executing untrusted code on the Laravel server.</p></div></div></section>
@endif
