<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::table('candidate_profiles',function(Blueprint $t){$t->string('first_name',100)->nullable()->after('user_id');$t->string('last_name',100)->nullable()->after('first_name');$t->string('phone',30)->nullable()->after('last_name');$t->text('address')->nullable()->after('phone');$t->string('avatar_path')->nullable()->after('address');$t->string('headline')->nullable();$t->text('bio')->nullable();$t->string('current_company')->nullable();$t->string('current_designation')->nullable();$t->decimal('current_salary',12,2)->nullable();$t->string('notice_period',50)->nullable();$t->unsignedTinyInteger('profile_completion')->default(10)->index();});
  Schema::table('resumes',function(Blueprint $t){$t->string('mime_type',100)->nullable();$t->unsignedBigInteger('file_size')->nullable();$t->string('parsing_status',30)->default('queued')->index();$t->json('parsed_data')->nullable();$t->text('parse_error')->nullable();$t->timestamp('parsed_at')->nullable();});
  if(!Schema::hasTable('company_profiles'))Schema::create('company_profiles',function(Blueprint $t){$t->id();$t->foreignId('company_id')->unique()->constrained()->cascadeOnDelete();$t->string('legal_name')->nullable();$t->string('email')->nullable();$t->string('phone',30)->nullable();$t->text('address')->nullable();$t->string('logo_path')->nullable();$t->text('about')->nullable();$t->unsignedInteger('founded_year')->nullable();$t->string('company_size',50)->nullable();$t->timestamps();});
  if(!Schema::hasTable('company_locations'))Schema::create('company_locations',function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->string('country')->index();$t->string('state')->nullable()->index();$t->string('city')->nullable()->index();$t->text('address')->nullable();$t->boolean('is_headquarters')->default(false);$t->timestamps();});
  if(!Schema::hasTable('company_industries'))Schema::create('company_industries',function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->string('industry')->index();$t->unique(['company_id','industry']);});
  if(!Schema::hasTable('company_verifications'))Schema::create('company_verifications',function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained()->cascadeOnDelete();$t->string('verification_type',50);$t->string('document_path')->nullable();$t->string('status',30)->default('pending')->index();$t->foreignId('verified_by')->nullable()->constrained('users')->nullOnDelete();$t->text('notes')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();});
 }
 public function down():void{Schema::dropIfExists('company_verifications');Schema::dropIfExists('company_industries');Schema::dropIfExists('company_locations');Schema::dropIfExists('company_profiles');Schema::table('resumes',fn(Blueprint $t)=>$t->dropColumn(['mime_type','file_size','parsing_status','parsed_data','parse_error','parsed_at']));Schema::table('candidate_profiles',fn(Blueprint $t)=>$t->dropColumn(['first_name','last_name','phone','address','avatar_path','headline','bio','current_company','current_designation','current_salary','notice_period','profile_completion']));}
};
