<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('news_tags',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->string('name');$t->string('slug')->unique();$t->timestamps();}));
Schema::create('news_article_tag',fn(Blueprint $t)=>tap($t,function($t){$t->foreignId('news_article_id')->constrained()->cascadeOnDelete();$t->foreignId('news_tag_id')->constrained()->cascadeOnDelete();$t->primary(['news_article_id','news_tag_id']);}));
Schema::create('industry_insights',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('news_article_id')->constrained()->cascadeOnDelete();$t->string('industry');$t->string('metric_name')->nullable();$t->decimal('metric_value',16,2)->nullable();$t->string('metric_unit',40)->nullable();$t->text('analysis');$t->json('demand_drivers')->nullable();$t->timestamps();}));
Schema::create('career_insights',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('news_article_id')->constrained()->cascadeOnDelete();$t->string('role');$t->string('impact_level',20)->default('medium');$t->json('recommended_skills')->nullable();$t->text('analysis')->nullable();$t->timestamps();}));
Schema::create('news_fetch_logs',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('source_id')->nullable()->constrained('news_sources')->nullOnDelete();$t->string('status',20);$t->unsignedInteger('items_found')->default(0);$t->unsignedInteger('items_created')->default(0);$t->unsignedInteger('duplicates')->default(0);$t->unsignedInteger('duration_ms')->default(0);$t->text('error')->nullable();$t->timestamp('started_at');$t->timestamp('finished_at')->nullable();$t->timestamps();}));
Schema::create('salary_insights',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('news_article_id')->nullable()->constrained()->nullOnDelete();$t->string('role');$t->string('location')->nullable();$t->string('experience_range')->nullable();$t->string('company_type')->nullable();$t->string('currency',3)->default('INR');$t->decimal('minimum',12,2)->nullable();$t->decimal('maximum',12,2)->nullable();$t->string('source_period')->nullable();$t->string('source_url');$t->json('value_skills')->nullable();$t->timestamps();}));
Schema::create('news_article_companies',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('news_article_id')->constrained()->cascadeOnDelete();$t->foreignId('company_id')->nullable()->constrained()->nullOnDelete();$t->string('company_name');$t->string('relationship_type',30)->default('mentioned');$t->foreignId('parent_company_id')->nullable()->constrained('companies')->nullOnDelete();$t->timestamps();$t->unique(['news_article_id','company_name','relationship_type'],'news_company_relation_unique');}));
Schema::table('news_articles',function(Blueprint $t){$t->string('processing_status',20)->default('fetched')->index();$t->string('content_hash',64)->nullable()->unique();$t->text('raw_content')->nullable();$t->json('entities')->nullable();$t->json('locations')->nullable();$t->timestamp('processed_at')->nullable();$t->timestamp('moderated_at')->nullable();$t->foreignId('moderated_by')->nullable()->constrained('users')->nullOnDelete();});
}public function down():void{Schema::table('news_articles',fn(Blueprint $t)=>$t->dropConstrainedForeignId('moderated_by'));Schema::table('news_articles',fn(Blueprint $t)=>$t->dropColumn(['processing_status','content_hash','raw_content','entities','locations','processed_at','moderated_at']));Schema::dropIfExists('news_article_companies');Schema::dropIfExists('salary_insights');Schema::dropIfExists('news_fetch_logs');Schema::dropIfExists('career_insights');Schema::dropIfExists('industry_insights');Schema::dropIfExists('news_article_tag');Schema::dropIfExists('news_tags');}};
