<?php

return [
    'featured_collections' => [
        'MNCs',
        'Product Companies',
        'Banking & Finance',
        'FMCG & Retail',
        'Startups',
        'Education Technology',
        'Healthcare',
        'Unicorns',
    ],

    // Canonical labels and common aliases. Counts are derived from active jobs.
    'locations' => [
        'Bengaluru' => ['bengaluru', 'bangalore'],
        'Delhi / NCR' => ['delhi / ncr', 'delhi ncr', 'ncr'],
        'Mumbai (All Areas)' => ['mumbai (all areas)', 'greater mumbai'],
        'Hyderabad' => ['hyderabad'], 'Pune' => ['pune'], 'Mumbai' => ['mumbai'],
        'Chennai' => ['chennai', 'madras'], 'Gurugram' => ['gurugram', 'gurgaon'],
        'New Delhi' => ['new delhi'], 'Noida' => ['noida'], 'Ahmedabad' => ['ahmedabad'],
        'Kolkata' => ['kolkata', 'calcutta'], 'Navi Mumbai' => ['navi mumbai'],
        'Coimbatore' => ['coimbatore'], 'Jaipur' => ['jaipur'], 'Thane' => ['thane'],
        'Vadodara' => ['vadodara', 'baroda'], 'Kochi' => ['kochi', 'cochin'],
        'Indore' => ['indore'], 'Nagpur' => ['nagpur'], 'Surat' => ['surat'],
        'Mumbai Suburban' => ['mumbai suburban'], 'Chandigarh' => ['chandigarh'],
        'Lucknow' => ['lucknow'], 'Nashik' => ['nashik', 'nasik'], 'Rajkot' => ['rajkot'],
        'Chhatrapati Sambhajinagar' => ['chhatrapati sambhajinagar', 'aurangabad'],
        'Bhubaneswar' => ['bhubaneswar', 'bhubaneshwar'], 'Visakhapatnam' => ['visakhapatnam', 'vizag'],
        'Mohali' => ['mohali', 'sahibzada ajit singh nagar'],
        'Thiruvananthapuram' => ['thiruvananthapuram', 'trivandrum'],
        'Faridabad' => ['faridabad'], 'Madurai' => ['madurai'], 'Bhopal' => ['bhopal'],
        'Ghaziabad' => ['ghaziabad'], 'Mysuru' => ['mysuru', 'mysore'], 'Ludhiana' => ['ludhiana'],
        'Greater Noida' => ['greater noida'], 'Vijayawada' => ['vijayawada'],
        'Guwahati' => ['guwahati'], 'Jamnagar' => ['jamnagar'], 'Raipur' => ['raipur'],
        'Dehradun' => ['dehradun'], 'Mangaluru' => ['mangaluru', 'mangalore'],
        'Patna' => ['patna'], 'Tiruchirappalli' => ['tiruchirappalli', 'trichy'],
        'Kanpur' => ['kanpur'], 'Bangalore Rural' => ['bangalore rural', 'bengaluru rural'],
        'Hubballi' => ['hubballi', 'hubli'], 'Agra' => ['agra'], 'Ranchi' => ['ranchi'],
        'Salem' => ['salem'], 'Udaipur' => ['udaipur'], 'Hosur' => ['hosur'],
        'Jodhpur' => ['jodhpur'], 'Belagavi' => ['belagavi', 'belgaum'],
        'Kozhikode' => ['kozhikode', 'calicut'], 'Jalandhar' => ['jalandhar'],
        'Sonipat' => ['sonipat', 'sonepat'], 'Tiruppur' => ['tiruppur'],
        'Gandhinagar' => ['gandhinagar'], 'Varanasi' => ['varanasi', 'banaras'],
        'Thrissur' => ['thrissur', 'trichur'], 'Siliguri' => ['siliguri'], 'Kota' => ['kota'],
        'Amritsar' => ['amritsar'], 'Panaji' => ['panaji', 'panjim'], 'Warangal' => ['warangal'],
        'Tirupati' => ['tirupati'], 'Haridwar' => ['haridwar'], 'Hisar' => ['hisar'],
        'Nellore' => ['nellore'], 'Panipat' => ['panipat'], 'Ernakulam' => ['ernakulam'],
        'Puducherry' => ['puducherry', 'pondicherry'], 'Prayagraj' => ['prayagraj', 'allahabad'],
        'Jabalpur' => ['jabalpur'], 'Guntur' => ['guntur'], 'Panvel' => ['panvel'],
        'Bharuch' => ['bharuch'], 'Vapi' => ['vapi'], 'Gwalior' => ['gwalior'],
        'Nagar' => ['nagar'], 'North Goa' => ['north goa'], 'Jamshedpur' => ['jamshedpur'],
        'Kolhapur' => ['kolhapur'], 'Vellore' => ['vellore'], 'Dahej' => ['dahej'],
        'Goregaon' => ['goregaon'], 'Jammu' => ['jammu'], 'Durgapur' => ['durgapur'],
        'Bikaner' => ['bikaner'], 'Manesar' => ['manesar'], 'Meerut' => ['meerut'],
        'Panchkula' => ['panchkula'], 'Yamunanagar' => ['yamunanagar', 'yamuna nagar'],
    ],
];
