<?php

return [
    'A Block Shastri Nagar','A Block Vikaspuri','A1 Block Janakpuri','A1 Block Paschim Vihar','A2 Block Janakpuri','A2 Block Paschim Vihar','A3 Block Janakpuri','A3 Block Paschim Vihar','A4 Block Paschim Vihar','AD Block Pitampura',
    'Adarsh Nagar','Adhchini','Aerocity','Agar Nagar','Ajmeri Gate','Akshardham','Alaknanda','Amar Colony','Ambedkar Colony','Anand Lok','Anand Niketan','Anand Parbat','Anand Vihar','Arjun Nagar','Asaf Ali Road','Ashok Nagar','Ashok Vihar','Ashok Vihar Phase I','Ashok Vihar Phase II',
    'Azad Market','Azad Nagar','Badarpur','Badli','Bahapur','Bakhtawarpur','Bali Nagar','Bapa Nagar','Barakhamba Road','Bawana','Begumpur','Ber Sarai','Bhajanpura','Bhalswa','Bijwasan','Bindapur','Burari','Chanakyapuri','Chandni Chowk','Chattarpur','Chirag Delhi','Chittaranjan Park','Civil Lines','Connaught Place',
    'Dabri','Dakshinpuri','Daryaganj','Defence Colony','Delhi Cantonment','Dilshad Garden','Dwarka','East of Kailash','Fateh Nagar','Gandhi Nagar','Geeta Colony','Ghitorni','Govindpuri','Greater Kailash I','Greater Kailash II','Green Park','Gulmohar Park','Hari Nagar','Hauz Khas','Inderpuri','ITO','Jahangirpuri','Jaitpur','Jamia Nagar','Janakpuri','Jangpura','Jasola','Jor Bagh',
    'Kalkaji','Kamla Nagar','Karol Bagh','Kashmere Gate','Khirki Extension','Kirti Nagar','Kondli','Krishna Nagar','Lajpat Nagar','Laxmi Nagar','Lodhi Colony','Madangir','Mahipalpur','Malviya Nagar','Mangolpuri','Mayapuri','Mayur Vihar','Mehrauli','Model Town','Moti Nagar','Mukherjee Nagar','Munirka','Nangloi','Naraina','Narela','Nehru Place','New Ashok Nagar','New Friends Colony','Nizamuddin','Okhla','Paharganj','Palam','Pandav Nagar','Paschim Vihar','Patel Nagar','Patparganj','Pitampura','Preet Vihar','Punjabi Bagh','R K Puram','Rajinder Nagar','Rajouri Garden','Rohini','Sadar Bazaar','Safdarjung Enclave','Saket','Sangam Vihar','Sarita Vihar','Sarojini Nagar','Seelampur','Shahdara','Shalimar Bagh','Shastri Nagar','Sheikh Sarai','Sonia Vihar','Subhash Nagar','Sultanpuri','Tilak Nagar','Timarpur','Tughlakabad','Uttam Nagar','Vasant Kunj','Vasant Vihar','Vijay Nagar','Vikaspuri','Wazirabad','Wazirpur','Yamuna Vihar',
];
