<?php

return [
    'user_agent' => env('DISCOVERY_USER_AGENT', 'AscendiaJobs/1.0 (+' . env('APP_URL', 'http://localhost') . ')'),
    'overpass_url' => env('OVERPASS_URL', 'https://overpass-api.de/api/interpreter'),
    'nominatim_url' => env('NOMINATIM_URL', 'https://nominatim.openstreetmap.org/search'),
    'wikidata_url' => env('WIKIDATA_SPARQL_URL', 'https://query.wikidata.org/sparql'),
    // Search radius around an industrial area's centre, in metres.
    'radius' => (int) env('DISCOVERY_RADIUS', 4500),

    // Technology searches sent to job feeds; industrial roles are added from the sector catalog's role lists.
    'technology_queries' => [
        'Java developer', 'Python developer', 'PHP Laravel developer', 'React developer', 'Angular developer', 'Node.js developer', '.NET developer',
        'Golang developer', 'DevOps engineer', 'Cloud engineer AWS', 'Azure engineer', 'Data engineer', 'Data scientist', 'Machine learning engineer',
        'Android developer', 'iOS developer', 'Flutter developer', 'QA automation engineer', 'SAP consultant', 'Salesforce developer',
        'Cybersecurity analyst', 'Full stack developer', 'Embedded software engineer', 'VLSI engineer', 'Product manager', 'Scrum master',
    ],

    // Wikidata country items scanned by `companies:discover wikidata`.
    'countries' => [
        'IN' => ['qid' => 'Q668', 'name' => 'India'],
        'US' => ['qid' => 'Q30', 'name' => 'United States'],
        'GB' => ['qid' => 'Q145', 'name' => 'United Kingdom'],
        'DE' => ['qid' => 'Q183', 'name' => 'Germany'],
        'FR' => ['qid' => 'Q142', 'name' => 'France'],
        'CH' => ['qid' => 'Q39', 'name' => 'Switzerland'],
        'JP' => ['qid' => 'Q17', 'name' => 'Japan'],
        'AE' => ['qid' => 'Q878', 'name' => 'United Arab Emirates'],
        'SG' => ['qid' => 'Q334', 'name' => 'Singapore'],
        'CA' => ['qid' => 'Q16', 'name' => 'Canada'],
        'AU' => ['qid' => 'Q408', 'name' => 'Australia'],
        'NL' => ['qid' => 'Q55', 'name' => 'Netherlands'],
        'KR' => ['qid' => 'Q884', 'name' => 'South Korea'],
        'CN' => ['qid' => 'Q148', 'name' => 'China'],
    ],

    // Industrial estates and tech parks scanned on OpenStreetMap. Coordinates are approximate centres.
    'hubs' => [
        ['name' => 'IMT Manesar', 'city' => 'Manesar', 'state' => 'Haryana', 'lat' => 28.3600, 'lon' => 76.9250],
        ['name' => 'DLF Cyber City', 'city' => 'Gurugram', 'state' => 'Haryana', 'lat' => 28.4950, 'lon' => 77.0890, 'type' => 'tech_park'],
        ['name' => 'Udyog Vihar', 'city' => 'Gurugram', 'state' => 'Haryana', 'lat' => 28.5020, 'lon' => 77.0830],
        ['name' => 'HSIIDC IMT Bawal', 'city' => 'Bawal', 'state' => 'Haryana', 'lat' => 28.0870, 'lon' => 76.5820],
        ['name' => 'Dharuhera Industrial Area', 'city' => 'Dharuhera', 'state' => 'Haryana', 'lat' => 28.2050, 'lon' => 76.7980],
        ['name' => 'Faridabad Industrial Area', 'city' => 'Faridabad', 'state' => 'Haryana', 'lat' => 28.3900, 'lon' => 77.3000],
        ['name' => 'RIICO Industrial Area Bhiwadi', 'city' => 'Bhiwadi', 'state' => 'Rajasthan', 'lat' => 28.2100, 'lon' => 76.8600],
        ['name' => 'Neemrana Industrial Area', 'city' => 'Neemrana', 'state' => 'Rajasthan', 'lat' => 27.9870, 'lon' => 76.3880],
        ['name' => 'Sanand GIDC', 'city' => 'Sanand', 'state' => 'Gujarat', 'lat' => 22.9800, 'lon' => 72.3800],
        ['name' => 'Halol GIDC', 'city' => 'Halol', 'state' => 'Gujarat', 'lat' => 22.5000, 'lon' => 73.4700],
        ['name' => 'Vapi GIDC', 'city' => 'Vapi', 'state' => 'Gujarat', 'lat' => 20.3700, 'lon' => 72.9100],
        ['name' => 'Ankleshwar GIDC', 'city' => 'Ankleshwar', 'state' => 'Gujarat', 'lat' => 21.6200, 'lon' => 73.0100],
        ['name' => 'SIDCUL IIE Pantnagar', 'city' => 'Rudrapur', 'state' => 'Uttarakhand', 'lat' => 28.9800, 'lon' => 79.4300],
        ['name' => 'SIDCUL IIE Haridwar', 'city' => 'Haridwar', 'state' => 'Uttarakhand', 'lat' => 29.9500, 'lon' => 78.0700],
        ['name' => 'Kashipur Industrial Area', 'city' => 'Kashipur', 'state' => 'Uttarakhand', 'lat' => 29.2100, 'lon' => 78.9600],
        ['name' => 'SIDCUL Sitarganj', 'city' => 'Sitarganj', 'state' => 'Uttarakhand', 'lat' => 28.9300, 'lon' => 79.7000],
        ['name' => 'Selaqui Industrial Area', 'city' => 'Dehradun', 'state' => 'Uttarakhand', 'lat' => 30.3700, 'lon' => 77.8600],
        ['name' => 'Ludhiana Focal Point', 'city' => 'Ludhiana', 'state' => 'Punjab', 'lat' => 30.8800, 'lon' => 75.9300],
        ['name' => 'Hi-Tech Cycle Valley Ludhiana', 'city' => 'Ludhiana', 'state' => 'Punjab', 'lat' => 30.9650, 'lon' => 75.9500],
        ['name' => 'Mohali Industrial Area', 'city' => 'Mohali', 'state' => 'Punjab', 'lat' => 30.7100, 'lon' => 76.7000],
        ['name' => 'Mohali IT City', 'city' => 'Mohali', 'state' => 'Punjab', 'lat' => 30.6550, 'lon' => 76.7300, 'type' => 'tech_park'],
        ['name' => 'PSIEC Industrial Area Hoshiarpur', 'city' => 'Hoshiarpur', 'state' => 'Punjab', 'lat' => 31.5150, 'lon' => 75.9300],
        ['name' => 'Jalandhar Focal Point', 'city' => 'Jalandhar', 'state' => 'Punjab', 'lat' => 31.3600, 'lon' => 75.5900],
        ['name' => 'Rajpura Industrial Area', 'city' => 'Rajpura', 'state' => 'Punjab', 'lat' => 30.4800, 'lon' => 76.6000],
        ['name' => 'Baddi Industrial Area', 'city' => 'Baddi', 'state' => 'Himachal Pradesh', 'lat' => 30.9600, 'lon' => 76.7900],
        ['name' => 'Noida Phase 2', 'city' => 'Noida', 'state' => 'Uttar Pradesh', 'lat' => 28.5400, 'lon' => 77.4000],
        ['name' => 'Greater Noida Industrial Area', 'city' => 'Greater Noida', 'state' => 'Uttar Pradesh', 'lat' => 28.4700, 'lon' => 77.5100],
        ['name' => 'Whitefield ITPL', 'city' => 'Bengaluru', 'state' => 'Karnataka', 'lat' => 12.9850, 'lon' => 77.7300, 'type' => 'tech_park'],
        ['name' => 'Electronic City', 'city' => 'Bengaluru', 'state' => 'Karnataka', 'lat' => 12.8450, 'lon' => 77.6600, 'type' => 'tech_park'],
        ['name' => 'Bagmane Tech Park', 'city' => 'Bengaluru', 'state' => 'Karnataka', 'lat' => 12.9800, 'lon' => 77.6600, 'type' => 'tech_park'],
        ['name' => 'Peenya Industrial Area', 'city' => 'Bengaluru', 'state' => 'Karnataka', 'lat' => 13.0300, 'lon' => 77.5200],
        ['name' => 'Bidadi Industrial Area', 'city' => 'Bidadi', 'state' => 'Karnataka', 'lat' => 12.8000, 'lon' => 77.4000],
        ['name' => 'Hinjawadi IT Park', 'city' => 'Pune', 'state' => 'Maharashtra', 'lat' => 18.5900, 'lon' => 73.7400, 'type' => 'tech_park'],
        ['name' => 'Kharadi EON IT Park', 'city' => 'Pune', 'state' => 'Maharashtra', 'lat' => 18.5500, 'lon' => 73.9500, 'type' => 'tech_park'],
        ['name' => 'Chakan MIDC', 'city' => 'Pune', 'state' => 'Maharashtra', 'lat' => 18.7600, 'lon' => 73.8500],
        ['name' => 'Bhosari MIDC', 'city' => 'Pune', 'state' => 'Maharashtra', 'lat' => 18.6300, 'lon' => 73.8400],
        ['name' => 'Waluj MIDC', 'city' => 'Chhatrapati Sambhajinagar', 'state' => 'Maharashtra', 'lat' => 19.8400, 'lon' => 75.2400],
        ['name' => 'MIHAN Nagpur', 'city' => 'Nagpur', 'state' => 'Maharashtra', 'lat' => 21.0900, 'lon' => 79.0500],
        ['name' => 'Butibori MIDC', 'city' => 'Nagpur', 'state' => 'Maharashtra', 'lat' => 20.9300, 'lon' => 78.9400],
        ['name' => 'HITEC City', 'city' => 'Hyderabad', 'state' => 'Telangana', 'lat' => 17.4480, 'lon' => 78.3800, 'type' => 'tech_park'],
        ['name' => 'Salt Lake Sector V', 'city' => 'Kolkata', 'state' => 'West Bengal', 'lat' => 22.5760, 'lon' => 88.4330, 'type' => 'tech_park'],
        ['name' => 'Oragadam', 'city' => 'Chennai', 'state' => 'Tamil Nadu', 'lat' => 12.8400, 'lon' => 79.9500],
        ['name' => 'Sriperumbudur SIPCOT', 'city' => 'Sriperumbudur', 'state' => 'Tamil Nadu', 'lat' => 12.9500, 'lon' => 79.9500],
        ['name' => 'OMR IT Corridor', 'city' => 'Chennai', 'state' => 'Tamil Nadu', 'lat' => 12.9000, 'lon' => 80.2270, 'type' => 'tech_park'],
        ['name' => 'Hosur SIPCOT', 'city' => 'Hosur', 'state' => 'Tamil Nadu', 'lat' => 12.7400, 'lon' => 77.8300],
        ['name' => 'Coimbatore SIDCO', 'city' => 'Coimbatore', 'state' => 'Tamil Nadu', 'lat' => 11.0200, 'lon' => 76.9600],
        ['name' => 'Pithampur Industrial Area', 'city' => 'Pithampur', 'state' => 'Madhya Pradesh', 'lat' => 22.6100, 'lon' => 75.6800],
        ['name' => 'Adityapur Industrial Area', 'city' => 'Jamshedpur', 'state' => 'Jharkhand', 'lat' => 22.7900, 'lon' => 86.1600],
        ['name' => 'Sri City', 'city' => 'Tirupati', 'state' => 'Andhra Pradesh', 'lat' => 13.5300, 'lon' => 79.9900],
    ],
];
