<?php

$lesson = fn (string $title, string $summary, string $code, string $task, array $options, int $answer, string $why): array => compact('title','summary','code','task','options','answer','why');

return [
 $lesson('Even or Odd','Use the remainder operator. An integer is even when division by 2 leaves remainder 0; otherwise it is odd. Time O(1), space O(1).',"static boolean isEven(int n) {\n    return n % 2 == 0;\n}\n\nSystem.out.println(isEven(42)); // true",'Test positive, negative and zero values. Then return the text EVEN or ODD.',['n % 2 == 0','n / 2 == 0','n % 1 == 0','n > 2'],0,'Divisibility by 2 is exactly represented by a zero remainder.'),
 $lesson('Sum of Natural Numbers','The arithmetic-series formula computes 1 through n without a loop. Use long before multiplication to reduce integer overflow risk. Time O(1), space O(1).',"static long sum(long n) {\n    if (n < 0) throw new IllegalArgumentException();\n    return n * (n + 1) / 2;\n}", 'Compare the formula with a loop for n values from 0 to 100.', ['n * (n + 1) / 2','n * n','n + (n - 1)','2 * n'],0,'The first n natural numbers form an arithmetic series with sum n(n+1)/2.'),
 $lesson('Closest Number Divisible by M','Compute the lower multiple using integer division and compare it with the next multiple. Define how ties and negative inputs should behave before coding.',"static int closest(int n, int m) {\n    if (m == 0) throw new IllegalArgumentException();\n    int q = n / m;\n    int a = m * q;\n    int b = n * m > 0 ? m * (q + 1) : m * (q - 1);\n    return Math.abs(n - a) < Math.abs(n - b) ? a : b;\n}", 'Test 13 with divisor 4, a tie case, and negative values.', ['Compare neighboring multiples','Try every integer forever','Sort all natural numbers','Use only n % 2'],0,'The closest divisible value must be one of the neighboring multiples around n.'),
 $lesson('Floyd’s Triangle','Floyd’s triangle prints consecutive integers across rows of increasing length. A running counter avoids recomputing each value. Time O(rows²).',"static void floyd(int rows) {\n    int value = 1;\n    for (int row = 1; row <= rows; row++) {\n        for (int col = 1; col <= row; col++)\n            System.out.print(value++ + \" \");\n        System.out.println();\n    }\n}", 'Print five rows, then modify the program to collect rows in a list for testing.', ['The inner loop runs row times','Every row has one value','The counter resets for each column','Recursion is mandatory'],0,'Row r contains r consecutive values, so the inner loop runs r times.'),
 $lesson('Print 1 to N Using Recursion','The base case stops at zero. Recursive calls first move toward the base case, then printing during stack unwinding produces ascending order. Time O(n), stack O(n).',"static void printOneToN(int n) {\n    if (n <= 0) return;\n    printOneToN(n - 1);\n    System.out.print(n + \" \");\n}", 'Move the print statement before the recursive call and explain why the order reverses.', ['Print after the recursive call','Remove the base case','Always call with n + 1','Use a global infinite loop'],0,'Printing after recursion emits values while calls return, producing ascending order.'),
 $lesson('Factorial','Factorial follows n! = n × (n−1)! with 0! = 1. Standard numeric types overflow quickly, so BigInteger is appropriate for larger n.',"static BigInteger factorial(int n) {\n    if (n < 0) throw new IllegalArgumentException();\n    if (n <= 1) return BigInteger.ONE;\n    return BigInteger.valueOf(n).multiply(factorial(n - 1));\n}", 'Implement iterative and recursive versions and compare stack usage.', ['0! equals 1','0! equals 0','Factorial is defined for negative integers here','int never overflows'],0,'The factorial recurrence requires the identity 0! = 1.'),
 $lesson('Greatest Common Divisor','Euclid’s algorithm repeatedly replaces (a,b) with (b,a mod b). It finishes when b becomes zero. Time O(log min(a,b)).',"static int gcd(int a, int b) {\n    a = Math.abs(a); b = Math.abs(b);\n    while (b != 0) {\n        int remainder = a % b;\n        a = b; b = remainder;\n    }\n    return a;\n}", 'Use gcd to implement lcm safely and test gcd(48,18).', ['Repeated remainders','Enumerate every real number','Multiply until overflow','Sort decimal digits'],0,'Euclid’s invariant preserves the common divisors while reducing the problem.'),
 $lesson('Power with Fast Exponentiation','Exponentiation by squaring halves the exponent each step. Even exponents square the half result; odd exponents multiply by the base once more. Time O(log exponent).',"static long power(long base, int exp) {\n    if (exp < 0) throw new IllegalArgumentException();\n    if (exp == 0) return 1;\n    long half = power(base, exp / 2);\n    long result = half * half;\n    return exp % 2 == 0 ? result : result * base;\n}", 'Trace power(2,10), then discuss overflow and modular exponentiation.', ['Halve the exponent each step','Subtract zero each step','Use n nested loops','Ignore exponent zero'],0,'Exponentiation by squaring reduces the recursion depth from O(n) to O(log n).'),
 $lesson('Prime Testing','A composite number must have a factor no greater than its square root. Check 2 separately, then test odd divisors while d ≤ n/d to avoid overflow.',"static boolean isPrime(int n) {\n    if (n < 2) return false;\n    if (n % 2 == 0) return n == 2;\n    for (int d = 3; d <= n / d; d += 2)\n        if (n % d == 0) return false;\n    return true;\n}", 'Test 1, 2, 3, 4, 97 and a large composite number.', ['Check possible factors through √n','Only check divisibility by 2','Treat 1 as prime','Test factors through n²'],0,'If both factors exceeded √n, their product would exceed n.'),
 $lesson('Armstrong Number','For a k-digit number, sum each digit raised to k and compare the result with the original number. Example: 153 = 1³+5³+3³.',"static boolean isArmstrong(int n) {\n    if (n < 0) return false;\n    int digits = String.valueOf(n).length();\n    int value = n; long total = 0;\n    do {\n        int digit = value % 10;\n        total += Math.round(Math.pow(digit, digits));\n        value /= 10;\n    } while (value != 0);\n    return total == n;\n}", 'Test 0, 153, 370, 9474 and 100. Replace Math.pow with an integer-power helper.', ['Raise every digit to the digit count','Add digits only','Square the complete number','Reverse the text only'],0,'Armstrong numbers equal the sum of their digits raised to the number of digits.'),
 $lesson('Tower of Hanoi','Move n−1 disks to the helper peg, move the largest disk to the destination, then move n−1 disks onto it. Moves are 2ⁿ−1; time O(2ⁿ), stack O(n).',"static void hanoi(int n, char from, char helper, char to) {\n    if (n == 0) return;\n    hanoi(n - 1, from, to, helper);\n    System.out.println(from + \" -> \" + to);\n    hanoi(n - 1, helper, from, to);\n}", 'Print moves for three disks and verify exactly seven moves occur.', ['2^n - 1 moves','n moves for every n','One move regardless of n','n²/2 moves exactly'],0,'The recurrence T(n)=2T(n−1)+1 resolves to 2ⁿ−1.'),
 $lesson('Josephus Problem','With zero-based indexing, the survivor satisfies J(1)=0 and J(n)=(J(n−1)+k) mod n. Add one for a one-based answer. Time O(n), space O(1) iteratively.',"static int josephus(int n, int k) {\n    if (n <= 0 || k <= 0) throw new IllegalArgumentException();\n    int survivor = 0;\n    for (int size = 2; size <= n; size++)\n        survivor = (survivor + k) % size;\n    return survivor + 1;\n}", 'Trace n=7, k=3 manually and compare with the algorithm.', ['J(n) = (J(n-1) + k) mod n','Always choose person n','Sort participants alphabetically','Use binary search on names'],0,'The recurrence shifts the smaller-circle survivor after each eliminated position.'),
];
