<?php

$items = [
['What is Apache Kafka?','A distributed event-streaming platform for publishing, storing, processing and consuming durable records at scale.'],
['What are Kafka’s main use cases?','Event-driven systems, real-time pipelines, log aggregation, service integration, event sourcing and stream processing.'],
['What is a Kafka broker?','A Kafka server that stores partitions and serves producer and consumer requests.'],
['What is a Kafka cluster?','A cooperating group of brokers providing scalable, fault-tolerant event storage.'],
['What is a topic?','A named logical category to which producers publish and consumers subscribe.'],
['What is a partition?','An ordered, append-only portion of a topic distributed across brokers.'],
['Why are partitions important?','They enable parallelism, horizontal scaling, throughput and distributed storage.'],
['What is an offset?','A record’s position within one partition and the basis for consumer progress.'],
['Is an offset unique across a topic?','No. It is unique only inside its partition.'],
['What do producers and consumers do?','Producers publish records; consumers poll assigned partitions.'],
['What is a consumer group?','Consumers cooperating so each partition is handled by at most one member of that group.'],
['Can multiple consumer groups read one topic?','Yes. Each group reads independently and owns separate offsets.'],
['Can two consumers in one group read the same partition?','Normally no; one group member owns a partition at a time.'],
['Can one consumer read several partitions?','Yes, when partitions outnumber consumers.'],
['What is replication?','Maintaining partition copies on multiple brokers for resilience.'],
['What is a partition leader?','The replica handling reads and writes while followers replicate it.'],
['What is ISR?','The set of in-sync replicas sufficiently caught up with the leader.'],
['What is replication factor?','The configured number of replicas for each partition.'],
['What happens when a leader broker fails?','Kafka elects an eligible in-sync replica as the new leader.'],
['What is retention?','Time- or size-based policy controlling how long Kafka keeps records.'],
['Does Kafka delete messages after consumption?','No; retention is independent of consumer reads.'],
['Kafka versus a traditional queue?','Kafka keeps a replayable log with offsets; queues commonly remove acknowledged messages.'],
['Kafka versus RabbitMQ?','Kafka favors durable high-throughput streams; RabbitMQ favors task queues and flexible routing.'],
['What does producer acks control?','When a producer considers a write acknowledged: 0, 1 or all.'],
['What does acks=0 mean?','Do not wait for broker acknowledgement; fastest but least assurance.'],
['What does acks=1 mean?','The leader acknowledges locally without waiting for all required replicas.'],
['What does acks=all mean?','Wait for the configured ISR requirement, giving strongest acknowledgement semantics.'],
['What is min.insync.replicas?','The minimum ISR count required for acks=all writes.'],
['What is producer batching?','Grouping records before sending to improve throughput.'],
['What does linger.ms do?','Briefly waits for more records to create larger batches.'],
['Which compression codecs does Kafka support?','Common choices include gzip, snappy, lz4 and zstd.'],
['What is an idempotent producer?','A producer mode that prevents retry-generated duplicate records.'],
['How can retries create duplicates?','The record is stored, its ACK is lost, and the producer sends it again.'],
['Why use a message key?','It controls partitioning and keeps related records together.'],
['How do you preserve per-customer ordering?','Use customerId as key so those events share a partition.'],
['Does Kafka guarantee global topic ordering?','No; ordering is guaranteed only within a partition.'],
['What is an offset commit?','Recording a group’s processed position for a partition.'],
['What is auto commit?','The client periodically commits offsets automatically.'],
['What is manual commit?','The application commits after its chosen processing boundary.'],
['What does enable.auto.commit=false do?','It requires application-controlled offset commits.'],
['What if a consumer crashes before committing?','Records after the last commit can be processed again.'],
['What is at-least-once delivery?','Records are not lost but duplicates can occur.'],
['What is at-most-once delivery?','Records run zero or one time, so failures can cause loss.'],
['What is exactly-once processing?','Kafka transactions prevent duplicate effects within the supported Kafka pipeline.'],
['What is consumer lag?','The gap between the latest and consumed offsets.'],
['What causes high lag?','Slow work, too few consumers, downstream latency, network issues or traffic spikes.'],
['How do you reduce lag?','Optimize and batch work, add capacity and add partitions when justified.'],
['What is a rebalance?','Redistribution of partitions after group membership or partition changes.'],
['What is cooperative rebalancing?','Incremental reassignment that reduces stop-the-world disruption.'],
['What does max.poll.interval.ms control?','Maximum allowed delay between consumer poll calls.'],
['What does session.timeout.ms control?','How long the broker waits for consumer heartbeats.'],
['What does heartbeat.interval.ms control?','How frequently consumers heartbeat the coordinator.'],
['What does max.poll.records control?','Maximum records returned by one poll.'],
['What is a dead-letter topic?','A topic for records that remain unprocessable after retries.'],
['How do retry topics work?','Failures move through retry topics and finally to a DLT.'],
['What is Kafka Connect?','A framework for moving data between Kafka and external systems.'],
['What is a source connector?','It imports external-system data into Kafka.'],
['What is a sink connector?','It exports Kafka records to another system.'],
['What is Kafka Streams?','A Java library for filtering, joining, aggregating and windowing Kafka records.'],
['Kafka Connect versus Kafka Streams?','Connect moves data; Streams processes it.'],
['What is a KStream?','An event stream in which every record matters independently.'],
['What is a KTable?','A changelog representation of the latest value for every key.'],
['KStream versus KTable?','KStream models events; KTable models current keyed state.'],
['What is a state store?','Local durable state used for joins, counts and aggregations.'],
['What is a Kafka transaction?','An atomic group of Kafka writes and supported offset updates.'],
['What is transactional.id?','A stable producer identity used for transactions and fencing.'],
['What does read_committed do?','It hides aborted or uncommitted transactional records from consumers.'],
['What is log compaction?','Retaining the latest record for each key.'],
['When should compacted topics be used?','For profiles, configuration, reference data and latest account state.'],
['What is a tombstone?','A keyed null-value record signalling deletion in compacted state.'],
['What if a replica falls behind?','It leaves ISR, reducing current redundancy.'],
['What is unclean leader election?','Electing outside ISR to regain availability, risking data loss.'],
['What is the Kafka controller?','The role coordinating metadata and partition leadership.'],
['What is KRaft?','Kafka’s Raft-based metadata architecture replacing ZooKeeper.'],
['Is KRaft an alternative to Kafka?','No; it is Kafka’s modern metadata architecture.'],
['What is a KRaft controller quorum?','Controllers reaching Raft consensus on cluster metadata.'],
['What is rack awareness?','Spreading replicas across failure domains such as racks or zones.'],
['How do you design for high throughput?','Use measured partitioning, brokers, replication, batching, compression and consumer capacity.'],
['How do you choose partition count?','Consider throughput, parallelism, capacity, growth, ordering and key distribution, then load test.'],
['What is a hot partition?','A partition receiving disproportionate traffic because keys are skewed.'],
['How do you fix a hot partition?','Improve keys, salt carefully, add partitions and preserve ordering requirements.'],
['How are null-key records partitioned?','Behavior varies by client; do not rely on null keys for business ordering.'],
['How do you order bank account events?','Key deposit, withdrawal and balance events by accountId.'],
['Where does Kafka fit in banking?','It distributes notification, fraud, audit and integration events; it is not the ledger.'],
['What is the transactional outbox pattern?','Write business data and an outbox event atomically, then publish the outbox to Kafka.'],
['What problem does an outbox solve?','It prevents database success with a lost Kafka event.'],
['How does Kafka support order processing?','orders.created independently drives payment, inventory, shipping, notification and analytics.'],
['What if one downstream service is unavailable?','Other groups continue and the service resumes from its committed offset.'],
['REST versus Kafka?','REST is typically synchronous; Kafka is asynchronous, durable and decoupled.'],
['Should Kafka replace REST?','No; production systems commonly use both at different boundaries.'],
['How should consumers handle duplicates?','Be idempotent and record unique event IDs before side effects.'],
['Which Kafka metrics matter?','Lag, throughput, latency, ISR changes, offline partitions, resources and client errors.'],
['What is an under-replicated partition?','A partition with fewer in-sync replicas than its replication factor.'],
['How do you secure Kafka?','Use TLS, SASL, ACLs, private networking, secret management and audit logs.'],
['Design an e-commerce Kafka flow.','Commit the order and outbox, publish orders.created, then consume it independently downstream.'],
['Does Kafka deduct money?','No; payment or core banking performs transactions and Kafka distributes events.'],
['Design a bank-transfer Kafka flow.','The ledger and outbox commit atomically; Kafka feeds notification, fraud and audit.'],
['Which system owns financial balances?','The authoritative transactional ledger, never Kafka alone.'],
['How do you combine durability settings?','Use zone-aware replication, acks=all, suitable min ISR and safe elections.'],
['What makes production Kafka reliable?','Idempotency, retries, DLTs, security, observability, capacity tests and recovery procedures.'],
];

return array_map(fn ($item, $index) => ['number'=>$index + 1, 'question'=>$item[0], 'answer'=>$item[1]], $items, array_keys($items));
