<?php

$topics = [
    ['queue:work versus queue:listen', 'queue:work is a long-running production worker; queue:listen reloads Laravel for each job and is slower but convenient in development.', 'php artisan queue:work --tries=3 --backoff=10'],
    ['Handling Failed Queue Jobs', 'Configure attempts and failure storage, inspect failures with queue:failed, retry recoverable work, and monitor repeated failures.', 'php artisan queue:failed\nphp artisan queue:retry all'],
    ['Laravel Job Batching', 'Bus batches group many queue jobs and expose progress, completion, cancellation, then and catch callbacks.', 'Bus::batch([new ImportChunk(1), new ImportChunk(2)])->allowFailures()->dispatch();'],
    ['Laravel Scheduler', 'The scheduler defines time-based commands and queued jobs in application code while one system cron entry calls schedule:run.', "Schedule::command('jobs:expire')->daily();"],
    ['Cron Jobs and Laravel', 'Cron is the operating-system trigger; Laravel decides which scheduled tasks are due.', '* * * * * php /var/www/html/artisan schedule:run'],
    ['Scheduling Every Minute', 'Use everyMinute for genuinely frequent lightweight work and protect long tasks from overlap.', "Schedule::command('jobs:update')->everyMinute()->withoutOverlapping();"],
    ['Scheduling Daily at Midnight', 'dailyAt executes a scheduled task at a specific application-timezone time.', "Schedule::command('jobs:expire')->dailyAt('00:00');"],
    ['Queue versus Scheduler', 'Queues execute background work; schedulers decide when work begins. A schedule can dispatch a queued job.', 'Schedule::job(new GenerateDailyReport())->daily();'],
    ['Laravel Cache', 'Cache stores expensive, frequently reused results for a bounded time to reduce queries and response latency.', "Cache::remember('featured_jobs', 3600, fn () => Job::featured()->get());"],
    ['Choosing a Cache Driver', 'Array suits tests, file/database suit simple deployments, while Redis is a strong shared production cache for multiple servers.', 'CACHE_STORE=redis'],
    ['Clearing Laravel Caches', 'Clear only the relevant cache during development; optimize:clear removes generated framework caches together.', 'php artisan optimize:clear'],
    ['Route Cache', 'route:cache compiles serializable routes for production and must be rebuilt after route changes.', 'php artisan route:cache\nphp artisan route:clear'],
    ['Configuration Cache', 'config:cache compiles configuration; application code should read config values instead of calling env outside config files.', 'php artisan config:cache\nphp artisan config:clear'],
    ['Caching Data Between Screens', 'Use a user-scoped cache key for expensive, non-sensitive temporary state and assign an explicit expiration.', "Cache::put('user_search.'.auth()->id(), \$filters, now()->addMinutes(30));"],
    ['Redis in Laravel', 'Redis is an in-memory data store commonly used for shared cache, queues, sessions, rate limiting and distributed locks.', 'REDIS_CLIENT=predis\nCACHE_STORE=redis\nQUEUE_CONNECTION=redis'],
    ['API Rate Limiting', 'Rate limiting caps requests per identity or IP to reduce brute force, abuse and accidental overload.', "Route::middleware('throttle:100,1')->group(function () { /* API routes */ });"],
    ['API Resources', 'API Resources transform models and relationships into stable public JSON contracts.', 'php artisan make:resource JobResource\nreturn JobResource::collection($jobs);'],
    ['Global API Exception Handling', 'Central exception handling maps validation, authentication, authorization and not-found failures to consistent safe JSON.', "return response()->json(['success'=>false,'message'=>'Job not found'], 404);"],
    ['Database Transactions', 'A transaction commits every critical database change together or rolls all of them back on failure.', 'DB::transaction(function () use ($data) { $company = Company::create($data); $company->jobs()->create($data); });'],
    ['try-catch Exception Handling', 'Catch errors only where the application can add context, recover or translate them; otherwise use centralized handling.', "try { \$service->publish(\$job); } catch (PublishingFailed \$e) { report(\$e); }"],
    ['Laravel Logging', 'Structured logs record operational context without exposing secrets; production logs should flow to centralized monitoring.', "Log::info('Job created', ['job_id'=>\$job->id, 'user_id'=>auth()->id()]);"],
    ['Roles and Permissions', 'Roles group permissions while policies and middleware enforce what authenticated users may do.', "\$user->can('update', \$job);"],
    ['Designing RBAC', 'Model users, roles and permissions with pivots, enforce least privilege server-side, and avoid scattered role string checks.', "Route::middleware(['auth','role:hr'])->group(function () { /* employer routes */ });"],
    ['Pagination', 'Pagination limits memory and response size; cursor pagination is efficient for large, ordered datasets.', 'Job::query()->latest()->cursorPaginate(20);'],
    ['get, first, find and firstOrFail', 'get returns a collection, first returns one optional row, find searches the primary key, and firstOrFail throws a 404-capable exception.', "Job::where('slug', \$slug)->firstOrFail();"],
    ['Chunking Large Datasets', 'chunkById processes stable batches without loading an entire table and avoids offset problems when records change.', 'Job::query()->chunkById(1000, function ($jobs) { /* process */ });'],
    ['Lazy Collections', 'lazy and cursor stream records with low memory usage for large exports, migrations and background processing.', 'Job::query()->lazyById()->each(function ($job) { /* process */ });'],
    ['Laravel Telescope', 'Telescope is a development observability tool for requests, queries, jobs, events, cache and exceptions; restrict it in production.', 'php artisan telescope:install'],
    ['Laravel Horizon', 'Horizon monitors and balances Redis queue workers, throughput, wait times and failures.', 'php artisan horizon'],
    ['Optimizing a Slow Laravel Application', 'Measure first, then fix slow queries and N+1, add appropriate indexes, paginate, cache stable results and queue expensive work.', 'Job::with("company")->where("status", "published")->paginate(20);'],
    ['High-Level System Design', 'HLD describes services, data stores, communication, scaling and infrastructure rather than individual methods.', 'Client -> CDN/LB -> Laravel API -> PostgreSQL + Redis + Search + Queue'],
    ['Low-Level System Design', 'LLD defines classes, interfaces, methods, schemas, relationships and patterns implementing a use case.', 'JobController -> JobService -> JobRepository -> Job model'],
    ['Job Portal High-Level Design', 'A scalable portal separates transactional data, cached discovery responses, full-text search and asynchronous side effects.', 'Users -> Load Balancer -> Laravel -> PostgreSQL / Redis / OpenSearch / Queue'],
    ['Designing Job Search', 'Store authoritative jobs in SQL, index searchable fields in a search engine, and support ranking, facets, autocomplete and filters.', 'keyword + location + skills + experience + salary + work_mode + posted_at'],
    ['Job Search Indexing', 'Commit the job first, dispatch an after-commit event, then queue an idempotent search-index update or deletion.', 'JobSaved event -> queue -> OpenSearch update'],
    ['Microservices', 'Microservices independently deploy and scale bounded capabilities, but introduce networking, consistency and observability complexity.', 'Auth | Jobs | Companies | Search | Notifications'],
    ['Monolith versus Microservices', 'Start with a modular monolith for simpler transactions and deployment; extract services when team or scaling boundaries justify it.', 'Modular monolith first -> measure -> extract bounded service'],
    ['Microservice Communication', 'Use HTTP or gRPC for required immediate responses and brokers for decoupled asynchronous events.', 'Job Service -> broker -> Search + Notification + Analytics'],
    ['Event-Driven Architecture', 'Producers publish facts and independent consumers react asynchronously, requiring idempotency and observability.', 'JobCreated -> SearchIndexer, NotificationSender, AnalyticsConsumer'],
    ['Idempotency', 'An idempotent operation produces one intended effect when retried; persist an idempotency key or use unique constraints.', 'Idempotency-Key: application-123'],
    ['Database Indexing', 'Indexes speed selective reads but cost storage and write work; design compound indexes from real query order and filters.', 'CREATE INDEX jobs_status_created_idx ON jobs(status, created_at);'],
    ['Preventing Duplicate Applications', 'Combine application validation with a database unique constraint so concurrent requests cannot create duplicates.', 'UNIQUE(candidate_id, job_id)'],
    ['Handling One Million Jobs', 'Never load everything: paginate, index filters, use search infrastructure, cache popular queries and process data asynchronously.', 'API -> Redis cache -> OpenSearch -> PostgreSQL'],
    ['Securing a Laravel API', 'Use HTTPS, authentication, authorization, validation, rate limits, safe errors, secret management and security monitoring.', "Route::middleware(['auth:sanctum','throttle:api'])->group(function () { /* protected */ });"],
    ['SQL Injection Prevention', 'Eloquent and parameter bindings separate SQL structure from untrusted values; never interpolate request input into raw SQL.', 'DB::select("select * from users where id = ?", [$id]);'],
    ['XSS Prevention', 'Escape untrusted output with Blade double braces and sanitize any intentionally allowed HTML before raw rendering.', '{{ $candidateName }}'],
    ['PHP Arrays versus Objects', 'Arrays suit simple collections; objects combine typed state, behavior, invariants and domain relationships.', '$filters = ["remote"=>true]; $job = new JobPosting();'],
    ['PHP Switch and Match', 'switch handles multiple known values; PHP match is expression-based, strict and often clearer for simple mappings.', '$label = match ($status) { "approved" => "Approved", default => "Unknown" };'],
    ['Production Laravel Folder Architecture', 'Organize by clear responsibilities or domains: controllers handle HTTP, requests validate, services coordinate, and jobs handle background work.', 'Route -> Middleware -> Controller -> FormRequest -> Service -> Model -> Resource'],
    ['Building a Production Job Portal', 'Use a modular monolith, PostgreSQL, Redis, queues, search indexing, object storage, policies, monitoring, tests and CI/CD; scale from measured bottlenecks.', 'Candidates + Companies + Jobs + Applications + Search + Notifications'],
];

return array_map(static function (array $topic): array {
    [$title, $summary, $code] = $topic;

    return [
        'title' => $title,
        'summary' => $summary,
        'code' => $code,
        'task' => 'Apply this concept to one small feature in the EngineerLaunch job portal and verify the result with a focused test.',
        'options' => [
            $summary,
            'It is primarily a Blade styling feature with no backend effect.',
            'It requires loading every database record into application memory.',
            'It removes the need for validation, authorization and testing.',
        ],
        'answer' => 0,
        'why' => $summary,
    ];
}, $topics);
