<?php

return [
    'java' => ['title'=>'Java','icon'=>'J','color'=>'#2563eb','description'=>'Core Java and object-oriented interview preparation from beginner to advanced.','topics'=>[
        'class'=>['title'=>'Class','questions'=>['What is a class in Java?','Why do we need a class?','What is the difference between a class and an object?','Can a Java class exist without creating an object?','What are instance variables?','What are instance methods?','What are class variables?','What is a nested class?','What is an inner class?','What is an anonymous class?','Can a top-level class be private?','What is an abstract class?']],
        'object'=>['title'=>'Object','questions'=>['What is an object in Java?','How do you create an object?','Where is an object stored in Java memory?','What is the difference between an object and a reference?','Can multiple references point to the same object?','What happens when an object reference is null?','What is object initialization?','What is the lifecycle of an object?','What is garbage collection?','What is shallow copy?','What is deep copy?','What is the difference between == and equals()?']],
        'constructors'=>['title'=>'Constructors','questions'=>['What is a constructor?','Why do we use a constructor?','Does a constructor have a return type?','Can a constructor be private?','What is a default constructor?','What is a parameterized constructor?','What is constructor overloading?','What is constructor chaining?','What is this()?','What is super()?','Can constructors be inherited?','How are private constructors used in the Singleton pattern?']],
        'access-modifiers'=>['title'=>'Access Modifiers','questions'=>['What are access modifiers?','What is public access?','What is private access?','What is protected access?','What is package-private access?','Which modifier is most restrictive?','Can a method or constructor be private?','What is the difference between private and protected?','Why should fields usually be private?']],
        'static'=>['title'=>'Static Keyword','questions'=>['What is the static keyword?','What is a static variable?','What is a static method?','Can a static method access instance data directly?','Can a static method be overridden?','What is method hiding?','Can a static method be overloaded?','What is a static block?','When is a static block executed?','What is a static nested class?']],
        'exceptions'=>['title'=>'Exception Handling','questions'=>['What is exception handling?','What is the difference between Error and Exception?','What is Throwable?','What are checked and unchecked exceptions?','What is the difference between throw and throws?','Can try exist without catch?','What is try-with-resources?','What is AutoCloseable?','How do you create a custom exception?','What is exception propagation?']],
        'multithreading'=>['title'=>'Multithreading','questions'=>['What is a process?','What is a thread?','What is multithreading?','What is the difference between Thread and Runnable?','What is Callable?','What is Future?','What is ExecutorService?','What is synchronization?','What is a race condition?','What is deadlock?','What is volatile?','What is the difference between wait() and sleep()?','What is ConcurrentHashMap?','What is the difference between Runnable and Iterable?']],
        'oop'=>['title'=>'OOP Principles','questions'=>['What is abstraction?','What is encapsulation?','What is inheritance?','What is polymorphism?','What is method overloading?','What is method overriding?','What is an interface?','What is the difference between an abstract class and an interface?','What is an IS-A relationship?','What is a HAS-A relationship?','When should composition be preferred?']],
        'arrays-strings'=>['title'=>'Arrays and Strings','questions'=>['How are arrays created and initialized?','What is the difference between an array and ArrayList?','How do multidimensional arrays work?','Why is String immutable?','What is the String pool?','What is the difference between String, StringBuilder and StringBuffer?','How do equals() and compareTo() differ?']],
        'streams-collections'=>['title'=>'Collections and Stream API','questions'=>['What is the Java Collections Framework?','What is the difference between List, Set and Map?','ArrayList versus LinkedList?','HashMap versus ConcurrentHashMap?','Comparable versus Comparator?','What is the Stream API?','What are intermediate and terminal operations?','What do map(), filter() and reduce() do?','When should parallel streams be avoided?']],
    ]],
    'spring-boot' => ['title'=>'Spring Boot','icon'=>'SB','color'=>'#16a34a','description'=>'Build secure production APIs, batch jobs and resilient microservices.','topics'=>[
        'fundamentals'=>['title'=>'Spring Boot Fundamentals','questions'=>['What problem does Spring Boot solve?','What is auto-configuration?','What are starter dependencies?','What is dependency injection?','What is the application context?']],
        'rest-api'=>['title'=>'REST API Development','questions'=>['How do you design a REST controller?','DTO versus entity?','How is request validation implemented?','How should API errors be handled?','How do you version an API?']],
        'data'=>['title'=>'Spring Data JPA','questions'=>['What is a repository?','What is the N+1 query problem?','What are lazy and eager loading?','How do transactions work?','How do you paginate large result sets?']],
        'security'=>['title'=>'Security','questions'=>['How does Spring Security work?','Authentication versus authorization?','How do JWT access tokens work?','What is CSRF?','How should passwords and secrets be stored?']],
        'microservices'=>['title'=>'Microservices','questions'=>['How do you choose service boundaries?','What is service discovery?','What is a circuit breaker?','How do you make an API idempotent?','How do distributed transactions work?']],
        'batch'=>['title'=>'Spring Batch','questions'=>['What are jobs and steps?','What is chunk processing?','What are ItemReader, ItemProcessor and ItemWriter?','How does restartability work?','How do you schedule and monitor a batch job?']],
    ]],
    'dsa' => ['title'=>'Data Structures & Algorithms','icon'=>'DS','color'=>'#f97316','description'=>'Topic-wise interview problems selected from your supplied DSA curriculum.','topics'=>[
        'maths-recursion'=>['title'=>'Maths, Pattern and Recursion','questions'=>['Even or Odd','Sum of Natural Numbers','Closest Number Divisible by M','Floyd\'s Triangle','Print 1 to N','Factorial','GCD','Power','Prime Testing','Armstrong Number','Tower of Hanoi','Josephus Problem']],
        'array-string'=>['title'=>'Array and String','questions'=>['Check if Array is Sorted','Reverse Array','Rotate Array','Generate All Subarrays','Arrange Array by Sign','Best Time to Buy and Sell Stock','Leaders in an Array','Check Same Strings','Reverse a String','Longest Common Prefix']],
        'searching'=>['title'=>'Searching','questions'=>['Linear Search','Binary Search','First and Last Occurrence','Search in Rotated Sorted Array','Find Peak Element','Square Root Using Binary Search','Median of Two Sorted Arrays']],
        'sorting'=>['title'=>'Sorting','questions'=>['Bubble Sort','Selection Sort','Insertion Sort','Merge Sort','Quick Sort','Heap Sort','Sort 0s, 1s and 2s','Count Inversions']],
        'hashing'=>['title'=>'Hashing and Two Pointer','questions'=>['Frequency of Elements','Two Sum','Longest Consecutive Sequence','Valid Anagram','Remove Duplicates from Sorted Array','Container With Most Water','Three Sum']],
        'sliding-window'=>['title'=>'Sliding Window and Prefix Sum','questions'=>['Maximum Sum Subarray of Size K','Longest Substring Without Repeating Characters','Minimum Window Substring','Subarray Sum Equals K','Range Sum Query','Longest Subarray With Given Sum']],
        'linked-list'=>['title'=>'Linked List','questions'=>['Reverse a Linked List','Find Middle Node','Detect a Cycle','Merge Two Sorted Lists','Remove Nth Node from End','Clone List With Random Pointer','LRU Cache']],
        'stack-queue'=>['title'=>'Stack, Queue and Deque','questions'=>['Valid Parentheses','Next Greater Element','Min Stack','Implement Queue Using Stacks','Sliding Window Maximum','Largest Rectangle in Histogram']],
        'trees'=>['title'=>'Binary Tree and BST','questions'=>['Tree Traversals','Level Order Traversal','Height of Binary Tree','Diameter of Binary Tree','Lowest Common Ancestor','Validate Binary Search Tree','Insert and Delete in BST','Kth Smallest Element in BST']],
        'heap-graph'=>['title'=>'Heap and Graph','questions'=>['Kth Largest Element','Top K Frequent Elements','Merge K Sorted Lists','Breadth First Search','Depth First Search','Detect Cycle in Graph','Dijkstra\'s Algorithm','Topological Sort']],
        'greedy-dp'=>['title'=>'Greedy and Dynamic Programming','questions'=>['Activity Selection','Job Sequencing','Fractional Knapsack','Climbing Stairs','House Robber','Coin Change','Longest Increasing Subsequence','Longest Common Subsequence','0/1 Knapsack']],
    ]],
    'react' => ['title'=>'React','icon'=>'R','color'=>'#0891b2','description'=>'Modern React fundamentals, state management, performance and frontend architecture.','topics'=>[
        'fundamentals'=>['title'=>'React Fundamentals','questions'=>['What is React?','What is JSX?','What are components?','Props versus state?','What is the virtual DOM?']],
        'hooks'=>['title'=>'Hooks','questions'=>['How does useState work?','How does useEffect work?','What are effect dependencies?','When should useMemo and useCallback be used?','How do you create a custom hook?']],
        'state'=>['title'=>'State Management','questions'=>['What is lifting state up?','When should Context be used?','Controlled versus uncontrolled components?','How do reducers manage complex state?','How do server-state libraries differ from global stores?']],
        'performance'=>['title'=>'Performance and Testing','questions'=>['Why does a component re-render?','How does React.memo work?','What is code splitting?','How do you test user behavior?','How do you diagnose a slow React page?']],
        'architecture'=>['title'=>'Frontend Architecture','questions'=>['How should a React project be structured?','How do error boundaries work?','How do you secure API calls?','What is hydration?','CSR versus SSR versus SSG?']],
    ]],
];
