<?php

$springLessons = require __DIR__.'/spring_boot_foundations.php';
$springAdvancedLessons = require __DIR__.'/spring_boot_advanced.php';
$reportingGitLessons = require __DIR__.'/reporting_git_lessons.php';
$dsaFoundationLessons = require __DIR__.'/dsa_foundations.php';
$dsaForLoopLessons = require __DIR__.'/dsa_for_loops.php';
$javaInputOutputLessons = require __DIR__.'/java_input_output.php';

return [
    'java' => ['title'=>'Java','icon'=>'J','color'=>'#2563eb','description'=>'Core Java and object-oriented interview preparation from beginner to advanced.','topics'=>[
        'input-output'=>['title'=>'Input and Output','type'=>'tutorial','lessons_config'=>'java_input_output','offset'=>0,'limit'=>1,'questions'=>array_column($javaInputOutputLessons,'title')],
        'class'=>['title'=>'Class','questions'=>['What is a class in Java?','Why do we need a class?','What is the difference between a class and an object?','Can a Java class exist without creating an object?','What are instance variables?','What are instance methods?','What are class variables?','What is a nested class?','What is an inner class?','What is an anonymous class?','Can a top-level class be private?','What is an abstract class?']],
        'object'=>['title'=>'Object','questions'=>['What is an object in Java?','How do you create an object?','Where is an object stored in Java memory?','What is the difference between an object and a reference?','Can multiple references point to the same object?','What happens when an object reference is null?','What is object initialization?','What is the lifecycle of an object?','What is garbage collection?','What is shallow copy?','What is deep copy?','What is the difference between == and equals()?']],
        'constructors'=>['title'=>'Constructors','questions'=>['What is a constructor?','Why do we use a constructor?','Does a constructor have a return type?','Can a constructor be private?','What is a default constructor?','What is a parameterized constructor?','What is constructor overloading?','What is constructor chaining?','What is this()?','What is super()?','Can constructors be inherited?','How are private constructors used in the Singleton pattern?']],
        'access-modifiers'=>['title'=>'Access Modifiers','questions'=>['What are access modifiers?','What is public access?','What is private access?','What is protected access?','What is package-private access?','Which modifier is most restrictive?','Can a method or constructor be private?','What is the difference between private and protected?','Why should fields usually be private?']],
        'static'=>['title'=>'Static Keyword','questions'=>['What is the static keyword?','What is a static variable?','What is a static method?','Can a static method access instance data directly?','Can a static method be overridden?','What is method hiding?','Can a static method be overloaded?','What is a static block?','When is a static block executed?','What is a static nested class?']],
        'exceptions'=>['title'=>'Exception Handling','questions'=>['What is exception handling?','What is the difference between Error and Exception?','What is Throwable?','What are checked and unchecked exceptions?','What is the difference between throw and throws?','Can try exist without catch?','What is try-with-resources?','What is AutoCloseable?','How do you create a custom exception?','What is exception propagation?']],
        'multithreading'=>['title'=>'Multithreading','questions'=>['What is a process?','What is a thread?','What is multithreading?','What is the difference between Thread and Runnable?','What is Callable?','What is Future?','What is ExecutorService?','What is synchronization?','What is a race condition?','What is deadlock?','What is volatile?','What is the difference between wait() and sleep()?','What is ConcurrentHashMap?','What is the difference between Runnable and Iterable?']],
        'oop'=>['title'=>'OOP Principles','questions'=>['What is abstraction?','What is encapsulation?','What is inheritance?','What is polymorphism?','What is method overloading?','What is method overriding?','What is an interface?','What is the difference between an abstract class and an interface?','What is an IS-A relationship?','What is a HAS-A relationship?','When should composition be preferred?']],
        'arrays-strings'=>['title'=>'Arrays and Strings','questions'=>['How are arrays created and initialized?','What is the difference between an array and ArrayList?','How do multidimensional arrays work?','Why is String immutable?','What is the String pool?','What is the difference between String, StringBuilder and StringBuffer?','How do equals() and compareTo() differ?']],
        'streams-collections'=>['title'=>'Collections and Stream API','questions'=>['What is the Java Collections Framework?','What is the difference between List, Set and Map?','ArrayList versus LinkedList?','HashMap versus ConcurrentHashMap?','Comparable versus Comparator?','What is the Stream API?','What are intermediate and terminal operations?','What do map(), filter() and reduce() do?','When should parallel streams be avoided?']],
    ]],
    'spring-boot' => ['title'=>'Spring Boot','icon'=>'SB','color'=>'#16a34a','description'=>'Build secure production APIs, batch jobs and resilient microservices.','topics'=>[
        'fundamentals'=>['title'=>'Spring & Spring Boot Fundamentals','type'=>'tutorial','lessons_config'=>'spring_boot_foundations','offset'=>0,'limit'=>10,'questions'=>array_column(array_slice($springLessons,0,10),'title')],
        'annotations'=>['title'=>'Spring Annotations','type'=>'tutorial','lessons_config'=>'spring_boot_foundations','offset'=>10,'limit'=>10,'questions'=>array_column(array_slice($springLessons,10,10),'title')],
        'bean-lifecycle'=>['title'=>'Bean Management & Lifecycle','type'=>'tutorial','lessons_config'=>'spring_boot_foundations','offset'=>20,'limit'=>10,'questions'=>array_column(array_slice($springLessons,20,10),'title')],
        'rest-api'=>['title'=>'REST API Development','type'=>'tutorial','lessons_config'=>'spring_boot_foundations','offset'=>30,'limit'=>10,'questions'=>array_column(array_slice($springLessons,30,10),'title')],
        'data'=>['title'=>'Spring Data JPA & Database','type'=>'tutorial','lessons_config'=>'spring_boot_foundations','offset'=>40,'limit'=>10,'questions'=>array_column(array_slice($springLessons,40,10),'title')],
        'security'=>['title'=>'Spring Security','type'=>'tutorial','lessons_config'=>'spring_boot_advanced','offset'=>0,'limit'=>10,'questions'=>array_column(array_slice($springAdvancedLessons,0,10),'title')],
        'microservices'=>['title'=>'Microservices','type'=>'tutorial','lessons_config'=>'spring_boot_advanced','offset'=>10,'limit'=>10,'questions'=>array_column(array_slice($springAdvancedLessons,10,10),'title')],
        'kafka'=>['title'=>'Kafka & Event-Driven Architecture','type'=>'tutorial','lessons_config'=>'spring_boot_advanced','offset'=>20,'limit'=>5,'questions'=>array_column(array_slice($springAdvancedLessons,20,5),'title')],
        'redis'=>['title'=>'Caching & Redis','type'=>'tutorial','lessons_config'=>'spring_boot_advanced','offset'=>25,'limit'=>5,'questions'=>array_column(array_slice($springAdvancedLessons,25,5),'title')],
        'scheduling-batch'=>['title'=>'Scheduling, Async & Spring Batch','type'=>'tutorial','lessons_config'=>'spring_boot_advanced','offset'=>30,'limit'=>5,'questions'=>array_column(array_slice($springAdvancedLessons,30,5),'title')],
        'testing'=>['title'=>'Testing','type'=>'tutorial','lessons_config'=>'spring_boot_advanced','offset'=>35,'limit'=>5,'questions'=>array_column(array_slice($springAdvancedLessons,35,5),'title')],
        'production'=>['title'=>'Production & Deployment','type'=>'tutorial','lessons_config'=>'spring_boot_advanced','offset'=>40,'limit'=>5,'questions'=>array_column(array_slice($springAdvancedLessons,40,5),'title')],
        'architecture'=>['title'=>'Advanced Scalable Architecture','type'=>'tutorial','lessons_config'=>'spring_boot_advanced','offset'=>45,'limit'=>5,'questions'=>array_column(array_slice($springAdvancedLessons,45,5),'title')],
    ]],
    'dsa' => ['title'=>'Data Structures & Algorithms','icon'=>'DS','color'=>'#f97316','description'=>'Topic-wise interview problems selected from your supplied DSA curriculum.','topics'=>[
        'for-loop-in-programing'=>['title'=>'For Loop in Programming','type'=>'tutorial','view'=>'learning.dsa-for-loop','lessons_config'=>'dsa_for_loops','offset'=>0,'limit'=>1,'questions'=>array_column($dsaForLoopLessons,'title')],
        'maths-recursion'=>['title'=>'Maths, Pattern and Recursion','type'=>'tutorial','lessons_config'=>'dsa_foundations','offset'=>0,'limit'=>12,'questions'=>array_column($dsaFoundationLessons,'title')],
        'array-string'=>['title'=>'Array and String','questions'=>['Check if Array is Sorted','Reverse Array','Rotate Array','Generate All Subarrays','Arrange Array by Sign','Best Time to Buy and Sell Stock','Leaders in an Array','Check Same Strings','Reverse a String','Longest Common Prefix']],
        'searching'=>['title'=>'Searching','questions'=>['Linear Search','Binary Search','First and Last Occurrence','Search in Rotated Sorted Array','Find Peak Element','Square Root Using Binary Search','Median of Two Sorted Arrays']],
        'sorting'=>['title'=>'Sorting','questions'=>['Bubble Sort','Selection Sort','Insertion Sort','Merge Sort','Quick Sort','Heap Sort','Sort 0s, 1s and 2s','Count Inversions']],
        'hashing'=>['title'=>'Hashing and Two Pointer','questions'=>['Frequency of Elements','Two Sum','Longest Consecutive Sequence','Valid Anagram','Remove Duplicates from Sorted Array','Container With Most Water','Three Sum']],
        'sliding-window'=>['title'=>'Sliding Window and Prefix Sum','questions'=>['Maximum Sum Subarray of Size K','Longest Substring Without Repeating Characters','Minimum Window Substring','Subarray Sum Equals K','Range Sum Query','Longest Subarray With Given Sum']],
        'linked-list'=>['title'=>'Linked List','questions'=>['Reverse a Linked List','Find Middle Node','Detect a Cycle','Merge Two Sorted Lists','Remove Nth Node from End','Clone List With Random Pointer','LRU Cache']],
        'stack-queue'=>['title'=>'Stack, Queue and Deque','questions'=>['Valid Parentheses','Next Greater Element','Min Stack','Implement Queue Using Stacks','Sliding Window Maximum','Largest Rectangle in Histogram']],
        'trees'=>['title'=>'Binary Tree and BST','questions'=>['Tree Traversals','Level Order Traversal','Height of Binary Tree','Diameter of Binary Tree','Lowest Common Ancestor','Validate Binary Search Tree','Insert and Delete in BST','Kth Smallest Element in BST']],
        'heap-graph'=>['title'=>'Heap and Graph','questions'=>['Kth Largest Element','Top K Frequent Elements','Merge K Sorted Lists','Breadth First Search','Depth First Search','Detect Cycle in Graph','Dijkstra\'s Algorithm','Topological Sort']],
        'greedy-dp'=>['title'=>'Greedy and Dynamic Programming','questions'=>['Activity Selection','Job Sequencing','Fractional Knapsack','Climbing Stairs','House Robber','Coin Change','Longest Increasing Subsequence','Longest Common Subsequence','0/1 Knapsack']],
    ]],
    'php-laravel' => ['title'=>'PHP & Laravel','icon'=>'PHP','color'=>'#7c3aed','description'=>'Complete PHP and Laravel preparation built around a production job portal.','topics'=>[
        'laravel-foundations'=>['title'=>'Laravel Foundations: Practical Lessons','type'=>'tutorial','questions'=>array_column(array_merge(config('laravel_foundations', []), config('laravel_advanced', [])),'title')],
        'php-strings'=>['title'=>'PHP Strings','questions'=>['How do strlen() and mb_strlen() differ?','How do strpos(), stripos() and str_contains() work?','How do substr(), explode() and implode() work?','When should you use str_replace() versus preg_replace()?','How do trim(), ltrim(), rtrim() and str_pad() work?','How do sprintf() and number_format() format output?','How do Laravel Str::slug(), Str::limit() and Str::mask() work?','How do you escape output safely with htmlspecialchars()?']],
        'php-oop'=>['title'=>'Classes and Objects','questions'=>['How do you define a typed PHP class?','What are properties, constructors and methods?','How does inheritance work in PHP?','What is method overriding?','What contract does an interface provide?','When should you use an abstract class?','What is a trait?','How do static properties and methods work?','How would you model JobPosting and FeaturedJobPosting?']],
        'arrays-loops'=>['title'=>'Arrays, Loops and Collections','questions'=>['How are indexed and associative arrays different?','When should you use for instead of foreach?','How do array_map(), array_filter() and array_reduce() work?','How do you sort and group PHP arrays?','What advantages do Laravel Collections provide?','How do map(), filter(), groupBy() and pluck() work?','How should you iterate over 10,000 database records safely?']],
        'carbon'=>['title'=>'Carbon and Date Handling','questions'=>['How does PHP DateTime differ from Carbon?','How do you parse and format dates with Carbon?','How do you calculate tomorrow at 9 AM?','How do you check whether a time is before 4 PM?','How do isBefore(), isAfter() and between() work?','How do you add or subtract time safely?','How would you validate an HR working-hours window?']],
        'composer-di'=>['title'=>'Composer and Dependency Injection','questions'=>['What is Composer?','What is the difference between composer.json and composer.lock?','Why should composer.lock be committed?','What is PSR-4 autoloading?','What is dependency injection?','How does Laravel resolve dependencies from its service container?','What is constructor injection?','When should you bind an interface to an implementation?']],
        'roles-middleware'=>['title'=>'Roles, Middleware and Policies','questions'=>['How do you model Admin, Compliance, Recruiter and Sales Director roles?','How does route middleware enforce a role?','Authentication versus authorization?','When should you use a policy instead of middleware?','How do gates and policies work?','How do you show role-specific Blade controls safely?','What is least-privilege authorization?']],
        'events-listeners'=>['title'=>'Events and Listeners','questions'=>['What is a Laravel event?','What is a listener?','Why decouple job application actions from notifications?','How do you dispatch an event?','When should a listener be queued?','How do you make listeners idempotent?','How do events interact with database transactions?']],
        'queues-batches-cron'=>['title'=>'Queues, Jobs, Batches and Cron','questions'=>['Why move slow work to a queue?','How do you create and dispatch a queued job?','How do retries, backoff and failed jobs work?','What is a Laravel job batch?','How do you track batch completion?','How does the Laravel Scheduler work?','What does the system cron entry execute?','How do withoutOverlapping() and onOneServer() prevent duplicate work?']],
        'excel'=>['title'=>'Excel & PDF Reports','type'=>'tutorial','lessons_config'=>'reporting_git_lessons','offset'=>0,'limit'=>8,'questions'=>array_column(array_slice($reportingGitLessons,0,8),'title')],
        'git-collaboration'=>['title'=>'Git Collaboration & Conflict Resolution','type'=>'tutorial','lessons_config'=>'reporting_git_lessons','offset'=>8,'limit'=>4,'questions'=>array_column(array_slice($reportingGitLessons,8,4),'title')],
        'migrations'=>['title'=>'Migrations and Job Portal Schema','questions'=>['What is a Laravel migration?','What do up() and down() do?','How do foreign keys and indexes work?','How would you model companies, jobs and applications?','How do you create a safe production schema change?','How do unique constraints prevent duplicate jobs?','How do you roll back a migration?']],
        'form-request'=>['title'=>'Form Request and Validation','questions'=>['What is a Form Request?','Why should validation be separated from a controller?','How does authorize() work?','How do nested-array validation rules work?','How do you create custom validation messages?','How does Laravel return 422 API errors?','How do you normalize validated input before a service receives it?']],
        'mvc-routing'=>['title'=>'MVC, Blade and Routing','questions'=>['Explain the Laravel MVC request lifecycle.','What belongs in routes/web.php?','What belongs in routes/api.php?','What is a controller responsible for?','Where should business logic live?','What is an Eloquent model?','How does Blade render dynamic views?','How do named routes keep navigation coordinated?','How do CSRF and API authentication differ?']],
    ]],
    'react' => ['title'=>'React','icon'=>'R','color'=>'#0891b2','description'=>'Modern React fundamentals, state management, performance and frontend architecture.','topics'=>[
        'fundamentals'=>['title'=>'React Fundamentals','questions'=>['What is React?','What is JSX?','What are components?','Props versus state?','What is the virtual DOM?']],
        'hooks'=>['title'=>'Hooks','questions'=>['How does useState work?','How does useEffect work?','What are effect dependencies?','When should useMemo and useCallback be used?','How do you create a custom hook?']],
        'state'=>['title'=>'State Management','questions'=>['What is lifting state up?','When should Context be used?','Controlled versus uncontrolled components?','How do reducers manage complex state?','How do server-state libraries differ from global stores?']],
        'performance'=>['title'=>'Performance and Testing','questions'=>['Why does a component re-render?','How does React.memo work?','What is code splitting?','How do you test user behavior?','How do you diagnose a slow React page?']],
        'architecture'=>['title'=>'Frontend Architecture','questions'=>['How should a React project be structured?','How do error boundaries work?','How do you secure API calls?','What is hydration?','CSR versus SSR versus SSG?']],
    ]],
];
