<?php

$lesson = fn (string $title, string $summary, string $code, string $task, array $options, int $answer, string $why): array => compact('title','summary','code','task','options','answer','why');

return [
    $lesson('Choosing an Excel library','Maatwebsite/Laravel-Excel is the common Laravel integration built on PhpSpreadsheet. PhpSpreadsheet gives lower-level control, while Spatie Simple Excel is useful for memory-efficient streaming of simple, very large files.',"// Common Laravel choice\ncomposer require maatwebsite/excel\n\n// Lower-level spreadsheet engine\ncomposer require phpoffice/phpspreadsheet",'Compare the libraries for a formatted monthly report and a two-million-row CSV export.',['Maatwebsite integrates naturally with Laravel concerns','DomPDF generates XLSX workbooks','Browsershot is an Excel parser','Redis is required for every spreadsheet'],0,'Maatwebsite/Laravel-Excel provides Laravel-oriented imports and exports on top of PhpSpreadsheet.'),
    $lesson('Installing Excel and PDF packages','Install only the packages the application needs and commit composer.json plus composer.lock. DomPDF renders controlled Blade HTML without requiring Chromium.',"composer require maatwebsite/excel barryvdh/laravel-dompdf\ncomposer show maatwebsite/excel\ncomposer show barryvdh/laravel-dompdf",'Install in a feature branch and confirm Composer selected versions compatible with the project PHP version.',['Commit vendor and delete composer.lock','Commit composer.json and composer.lock, not vendor','Put package names only in .env','Install packages on every request'],1,'Composer manifests make dependency installation repeatable; vendor is normally excluded from Git.'),
    $lesson('Creating a Laravel Excel export','An export class describes the rows and headings independently from the HTTP controller. Concerns compose features without turning the controller into report logic.',"namespace App\\Exports;\n\nuse App\\Models\\User;\nuse Maatwebsite\\Excel\\Concerns\\FromQuery;\nuse Maatwebsite\\Excel\\Concerns\\WithHeadings;\n\nfinal class UsersExport implements FromQuery, WithHeadings {\n public function query() { return User::query()->select('id','name','email','created_at'); }\n public function headings(): array { return ['ID','Name','Email','Created At']; }\n}",'Generate UsersExport and export only columns approved for the report.',['Put the query in JavaScript','Create a focused export class','Return User::all() from a Blade view','Store the XLSX in the users table'],1,'A dedicated export class keeps data selection and spreadsheet behavior testable.'),
    $lesson('Exporting large datasets safely','Avoid loading a massive dataset with get(). Query-based or generator-based exports, chunk reading, queues and temporary object storage keep HTTP memory stable.',"final class JobsExport implements FromQuery, ShouldQueue {\n public function query() {\n  return Job::query()->published()->select('id','title','company_id');\n }\n}", 'Test the export with 100,000 factory records and monitor peak memory.', ['Use User::all() for every export size','Stream or queue query-based exports','Increase memory_limit without bounds','Build XLSX rows in the browser session'],1,'Large reports should be streamed/chunked or queued rather than fully materialized in request memory.'),
    $lesson('Downloading an Excel report','The controller authorizes the report, constructs the export and returns Excel::download. Filters should be validated and passed explicitly.',"use Maatwebsite\\Excel\\Facades\\Excel;\n\npublic function excel(ReportFilterRequest \$request) {\n \$this->authorize('exportUsers');\n return Excel::download(new UsersExport(\$request->validated()), 'users-report.xlsx');\n}",'Protect a candidate export so only an authorized owner can download it.', ['Return Excel::download from an authorized action','Expose every email publicly','Build SQL from raw query strings','Disable validation for reports'],0,'Report downloads need the same validation and authorization as other sensitive endpoints.'),
    $lesson('Choosing a PDF renderer','DomPDF converts conservative HTML/CSS to PDF and works well for invoices and reports. Spatie Laravel PDF or Browsershot uses Chromium when exact modern CSS rendering is essential.',"use Barryvdh\\DomPDF\\Facade\\Pdf;\n\n\$pdf = Pdf::loadView('reports.users-pdf', ['users'=>\$users]);\nreturn \$pdf->download('users-report.pdf');",'Choose a renderer for an ATS resume and another for a pixel-perfect dashboard printout.',['DomPDF is appropriate for controlled report HTML','Maatwebsite renders CSS Grid PDFs','Redis converts Blade into PDF','PDF generation belongs in a migration'],0,'Renderer choice depends on layout complexity, runtime dependencies and performance.'),
    $lesson('Building a PDF Blade template','A PDF view should have deterministic dimensions, embedded print-safe CSS, escaped values and a layout supported by the selected renderer.',"<!doctype html>\n<html><head><style>\ntable{width:100%;border-collapse:collapse}\nth,td{border:1px solid #ddd;padding:8px;text-align:left}\n</style></head><body>\n<h2>Users List</h2>\n@foreach(\$users as \$user) <p>{{ \$user->name }} — {{ \$user->email }}</p> @endforeach\n</body></html>",'Render malicious-looking user text and confirm Blade escapes it in the PDF HTML.',['Use escaped Blade output for user data','Render all data with {!! !!}','Load remote scripts in every PDF','Store PHP code in report fields'],0,'Escaping untrusted values prevents HTML injection during document generation.'),
    $lesson('Defining secure report routes','Use named controller routes protected by authentication, authorization and appropriate throttling. Keep report creation out of anonymous GET endpoints when it is expensive or sensitive.',"Route::middleware(['auth','throttle:reports'])->group(function(){\n Route::get('/reports/users.xlsx',[ReportController::class,'excel'])->name('reports.users.excel');\n Route::get('/reports/users.pdf',[ReportController::class,'pdf'])->name('reports.users.pdf');\n});",'Add policy checks and a feature test proving an ordinary student receives 403.',['Protect routes and authorize inside the action','Use public routes for private candidate data','Pass database passwords in the URL','Disable throttling on expensive exports'],0,'Routes, policies and throttling protect report data and compute resources.'),

    $lesson('The daily Git workflow','Inspect changes, stage intentionally, commit a focused unit and push a feature branch. Avoid blindly adding secrets or unrelated user work.',"git status\ngit diff\ngit add path/to/changed-file.php\ngit commit -m \"Add applicant report export\"\ngit push origin feature/applicant-reports",'Create a focused commit containing only the reporting module.',['Inspect diff before staging and commit focused changes','Always run git add . without review','Commit .env credentials','Force-push main after every edit'],0,'Reviewing and staging intentionally prevents secrets and unrelated work entering a commit.'),
    $lesson('Synchronizing before development','Fetch remote references, update local main, then merge or rebase main into a feature branch before pushing.',"git fetch origin\ngit switch main\ngit pull --ff-only origin main\ngit switch feature/applicant-reports\ngit merge main",'Synchronize a disposable feature branch and inspect the resulting history.',['Delete main before fetching','Fetch, update main, then integrate it into the feature branch','Pull directly into random dirty files','Use reset --hard for every update'],1,'Regular synchronization reduces large, late conflicts while preserving controlled history.'),
    $lesson('Resolving a merge conflict','Git conflict markers show current and incoming alternatives. Understand both changes, produce the intended final code, remove every marker, test, then stage the resolution.',"<<<<<<< HEAD\n\$users = User::active()->get();\n=======\n\$users = User::active()->latest('id')->get();\n>>>>>>> main\n\n// Resolved\n\$users = User::active()->latest('id')->get();",'Create a harmless conflict on a practice branch, resolve it and run the related test.',['Leave conflict markers in PHP','Choose or combine intent, remove markers and test','Delete both files automatically','Resolve only on the production server'],1,'A correct resolution reconciles intent and is verified before committing.'),
    $lesson('Healthy team Git practices','Small feature branches and pull requests, frequent synchronization, clear reviews and automated tests reduce conflicts and regression risk.',"feature/applicant-report\n  → small commits\n  → pull request\n  → automated tests\n  → review\n  → merge",'Split a large reporting change into reviewable commits and draft a concise pull-request description.',['Commit every feature directly to main','Use focused branches, small PRs and automated checks','Combine unrelated work into one PR','Skip review when conflicts occurred'],1,'Small isolated changes are easier to review, test, merge and revert safely.'),
];
