<?php

$lesson = function (string $title, string $summary, string $code, string $task, string $correct): array {
    return ['title'=>$title,'summary'=>$summary,'code'=>$code,'task'=>$task,'options'=>[$correct,'It is only a browser-side feature.','It requires disabling the Spring container.','It stores all application data in source code.'],'answer'=>0,'why'=>$correct];
};

return [
 $lesson('What is Spring Security?','Spring Security provides authentication, authorization, password protection, session security, OAuth2/JWT integration and defenses such as CSRF protection.',"implementation(\"org.springframework.boot:spring-boot-starter-security\")",'Protect a private endpoint and verify an anonymous request receives 401.','Spring Security is the Spring ecosystem framework for authentication and authorization.'),
 $lesson('Authentication versus authorization','Authentication proves who the caller is; authorization decides which resources and operations that identity may access.',"http.authorizeHttpRequests(auth -> auth\n .requestMatchers(\"/admin/**\").hasRole(\"ADMIN\")\n .anyRequest().authenticated());",'Identify the authentication and authorization phases of an HR login request.','Authentication establishes identity; authorization evaluates permissions.'),
 $lesson('What is JWT?','A JSON Web Token is a signed compact token containing header, payload and signature. Treat claims as readable and verify signature, issuer, audience and expiry.',"Authorization: Bearer eyJhbGciOi...\n// header.payload.signature",'Decode a test JWT, then reject one with an invalid signature or expired exp claim.','JWT is a signed token format composed of header, payload and signature.'),
 $lesson('How does JWT authentication work?','After credential verification a server issues a short-lived token; the client sends it as a Bearer token and a security filter validates it before authorization.',"String header = request.getHeader(\"Authorization\");\n// extract Bearer token, validate, create Authentication",'Trace login, token issuance, validation and authorization for a protected jobs API.','A validated Bearer token establishes an authenticated security context for the request.'),
 $lesson('What is SecurityFilterChain?','Modern Spring Security configuration exposes a SecurityFilterChain bean defining request authorization, authentication mechanisms and security protections.',"@Bean\nSecurityFilterChain security(HttpSecurity http) throws Exception {\n return http.authorizeHttpRequests(a -> a\n  .requestMatchers(\"/public/**\").permitAll()\n  .anyRequest().authenticated()).build();\n}",'Permit health checks, require authentication elsewhere, and test both paths.','SecurityFilterChain defines the ordered web-security rules and filters.'),
 $lesson('What is PasswordEncoder?','PasswordEncoder performs one-way adaptive password hashing. BCrypt or Argon2 should be used with unique salts; plain text and reversible encryption are unsafe.',"@Bean PasswordEncoder passwordEncoder() {\n return new BCryptPasswordEncoder();\n}", 'Hash a password, verify it with matches(), and confirm equal passwords have different hashes.', 'PasswordEncoder securely hashes and verifies passwords without storing the original value.'),
 $lesson('What is OAuth2?','OAuth2 is an authorization framework for delegated access. OpenID Connect adds identity/login capabilities commonly used for Google, GitHub and enterprise SSO.',"spring.security.oauth2.client.registration.github.client-id=\${GITHUB_CLIENT_ID}", 'Describe authorization-code flow and where client secrets belong.', 'OAuth2 delegates access; OpenID Connect commonly supplies login identity on top of it.'),
 $lesson('What is CORS?','CORS is a browser-enforced policy controlling which origins may call a server. Configure an explicit allow-list rather than reflecting arbitrary origins.',"@Bean CorsConfigurationSource cors() {\n var c = new CorsConfiguration();\n c.setAllowedOrigins(List.of(\"https://app.example.com\"));\n return request -> c;\n}",'Allow the production frontend and reject an untrusted origin.', 'CORS controls permitted cross-origin browser requests through response headers.'),
 $lesson('What is CSRF?','CSRF tricks an authenticated browser into sending an unwanted state-changing request. It matters especially with automatically attached session cookies.',"http.csrf(csrf -> csrf\n .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse()));",'Submit a session-authenticated POST without a CSRF token, then with a valid token.', 'CSRF protection verifies that state-changing cookie-authenticated requests originate from the trusted application.'),
 $lesson('What is role-based authorization?','Role-based access control grants permissions through roles such as ADMIN, EMPLOYER, HR, RECRUITER and JOB_SEEKER; server-side checks remain mandatory.',"@PreAuthorize(\"hasAnyRole('ADMIN','HR')\")\npublic void updateApplicationStatus(long id) {}",'Create a role matrix and test that recruiters cannot access owner-only analytics.', 'RBAC maps permissions to roles and enforces them at HTTP and method boundaries.'),

 $lesson('What is microservices architecture?','Microservices divide a system into independently deployable services aligned with business capabilities and usually owning their data.',"user-service\ncompany-service\njob-service\napplication-service\nnotification-service",'Draw service boundaries for a job portal without splitting every database table into a service.', 'Microservices are independently deployable services organized around business capabilities.'),
 $lesson('Monolith versus microservices','A monolith is simpler to build and operate initially; microservices add independent scaling and deployment but introduce network, data and observability complexity.',"// Start modular\ncom.ascendia.jobs\ncom.ascendia.applications\ncom.ascendia.companies",'Choose an architecture for an early-stage portal and explain when extraction becomes justified.', 'Microservices trade operational complexity for independently evolvable and scalable services.'),
 $lesson('What is an API Gateway?','A gateway is the client entry point for routing, authentication integration, throttling, logging and request transformation. Domain logic should remain in services.',"spring.cloud.gateway.routes[0].id=job-service\nspring.cloud.gateway.routes[0].uri=lb://job-service",'Route /api/jobs to job-service and add a rate limit.', 'An API gateway centralizes cross-cutting edge concerns and routes requests to services.'),
 $lesson('What is service discovery?','Service discovery maps logical service names to healthy instances. Kubernetes commonly provides this through Services and DNS; other environments may use Consul.',"http://job-service/api/jobs\n// resolved by platform service discovery",'Scale job-service to three instances and call it using its logical name.', 'Service discovery lets clients find changing healthy service instances dynamically.'),
 $lesson('What is OpenFeign?','OpenFeign declares typed HTTP clients through annotated interfaces. Production clients still need timeouts, error handling and resilience policies.',"@FeignClient(name=\"user-service\")\ninterface UserClient {\n @GetMapping(\"/users/{id}\") UserDto get(@PathVariable long id);\n}",'Create a client with connection/read timeouts and a test stub.', 'OpenFeign is a declarative HTTP-client abstraction used in Spring Cloud applications.'),
 $lesson('How do microservices communicate?','Use synchronous HTTP/gRPC for immediate responses and asynchronous brokers for decoupled, durable event processing. Choose based on consistency and latency needs.',"// synchronous: GET /users/42\n// asynchronous: ApplicationSubmitted event",'Choose communication modes for profile lookup and notification delivery.', 'Services use synchronous APIs or asynchronous messaging according to workflow requirements.'),
 $lesson('What is a circuit breaker?','A circuit breaker stops repeated calls to a failing dependency, fails fast while open and probes recovery after a delay.',"@CircuitBreaker(name=\"companyService\", fallbackMethod=\"fallback\")\nCompanyDto company(long id) { return client.get(id); }",'Simulate timeouts and observe closed, open and half-open behavior.', 'A circuit breaker prevents cascading failure by temporarily blocking calls to an unhealthy dependency.'),
 $lesson('What is resilience?','Resilience combines bounded timeouts, cautious retries, circuit breakers, bulkheads, fallbacks and load shedding to contain failures.',"@Retry(name=\"jobs\")\n@TimeLimiter(name=\"jobs\")\n@CircuitBreaker(name=\"jobs\")",'Define a timeout and prove retries do not multiply a non-idempotent request.', 'Resilience techniques keep partial failures from taking down the entire system.'),
 $lesson('What is distributed tracing?','Distributed tracing propagates trace and span identifiers across services so a request path and latency can be reconstructed.',"management.tracing.sampling.probability=0.1\n// propagate traceparent header",'Trace an application submission through gateway, application and notification services.', 'Distributed tracing correlates work belonging to one request across service boundaries.'),
 $lesson('Designing job-portal microservices','Useful boundaries include identity, companies, jobs, applications, interviews, notifications and analytics, connected through APIs and events.',"Gateway -> Job Service -> Search Index\nApplication Service -> broker -> Notification + Analytics",'Define ownership of application status and prevent two services writing the same table.', 'Each service should own a cohesive business capability and its authoritative data.'),

 $lesson('What is Apache Kafka?','Kafka is a distributed durable event-streaming platform used for integration, audit streams, analytics and high-throughput event processing.',"application-submitted\njob-published\ninterview-scheduled",'Publish a JobPublished event and consume it in a search-index worker.', 'Kafka stores ordered event streams in distributed topics for scalable producers and consumers.'),
 $lesson('What is a Kafka topic?','A topic is a named event stream. Event names and schemas should describe completed facts and evolve compatibly.',"topic: application-submitted\nkey: applicationId\nvalue: {eventId, occurredAt, candidateId, jobId}",'Design a versioned schema for ApplicationStatusChanged.', 'A Kafka topic groups a logical category of records.'),
 $lesson('What is a Kafka partition?','Partitions provide parallelism and ordered records within each partition. The record key determines partition placement.',"producer.send(new ProducerRecord<>(\"applications\", applicationId, event));",'Choose a key that preserves order for one job application.', 'Partitions scale throughput while preserving order only within each partition.'),
 $lesson('What is a Kafka consumer group?','Consumers in the same group divide topic partitions so one group member processes each partition; separate groups receive independent copies.',"spring.kafka.consumer.group-id=notification-service",'Run two consumers in one group and observe partition assignment.', 'A consumer group shares partitions among its members for parallel processing.'),
 $lesson('Using Kafka in a job portal','After an application transaction commits, publish an event that email, analytics, audit and notification consumers handle independently.',"ApplicationSubmitted -> [Email, Analytics, HR Notification, Audit]",'Implement idempotent consumers using event IDs and a processed-events table.', 'Events decouple downstream work so the application request need not wait for every consumer.'),

 $lesson('What is caching?','Caching stores frequently read or expensive results in faster storage. Every cache needs a TTL, key design and invalidation strategy.',"cache key: jobs:search:java:pune:page0\nTTL: 10 minutes",'Measure database queries before and after caching a popular search.', 'A cache trades some consistency complexity for faster repeated reads.'),
 $lesson('Why use Redis?','Redis supports caches, sessions, counters, rate limits, temporary values, streams and distributed coordination with explicit expiry.',"spring.data.redis.host=localhost\nspring.cache.type=redis",'Store a one-hour company profile cache and inspect its TTL.', 'Redis is an in-memory data platform commonly used for cache and ephemeral distributed state.'),
 $lesson('What is @Cacheable?','@Cacheable checks the configured cache before method execution and stores the result on a miss. Keys must include every input affecting the result.',"@Cacheable(value=\"users\", key=\"#id\")\npublic UserDto getUser(long id) { return repository.findById(id).map(mapper::toDto).orElseThrow(); }",'Call the method twice and prove the repository runs once.', '@Cacheable can skip method execution when a valid cached value exists.'),
 $lesson('What is @CacheEvict?','@CacheEvict removes stale entries after writes. allEntries should be used carefully because it can cause a cache stampede.',"@CacheEvict(value=\"users\", key=\"#id\")\npublic UserDto update(long id, UpdateUserRequest request) { return service.update(id, request); }",'Update a user and verify the next read reloads fresh data.', '@CacheEvict invalidates cached data that a state change made stale.'),
 $lesson('Choosing a caching strategy','Cache-aside loads from cache first, falls back to the database, then fills cache. Protect hot keys with TTL jitter and request coalescing.',"value = cache.get(key);\nif (value == null) { value = repository.load(id); cache.put(key,value,ttl); }",'Design cache keys and invalidation for company job counts.', 'Cache-aside keeps the database authoritative while the application fills cache on misses.'),

 $lesson('What is @Scheduled?','@Scheduled triggers methods using fixed delay, fixed rate or cron. In a cluster, use a distributed lock or platform scheduler to prevent duplicate execution.',"@Scheduled(cron=\"0 0 9 * * *\", zone=\"Asia/Kolkata\")\nvoid refreshJobs() {}",'Schedule a daily refresh and prevent overlapping runs.', '@Scheduled invokes a managed method according to a configured schedule.'),
 $lesson('What is a cron expression?','Spring cron fields represent second, minute, hour, day-of-month, month and day-of-week; timezone must be explicit for business schedules.',"0 0 9 * * *  // every day at 09:00",'Write schedules for hourly and weekday-at-9-AM tasks and test them.', 'A cron expression defines calendar-based execution times.'),
 $lesson('What is @Async?','@Async submits work to a configured task executor. Calls must cross a Spring proxy and thread pools need bounded queues and rejection policies.',"@EnableAsync\n@Async(\"mailExecutor\")\npublic CompletableFuture<Void> sendEmail() { return CompletableFuture.completedFuture(null); }",'Configure a bounded executor and observe that self-invocation is not asynchronous.', '@Async runs eligible proxied method calls through a task executor.'),
 $lesson('@Async versus Kafka','@Async is in-process and usually not durable; Kafka supports durable cross-service messaging, replay and independent consumers.',"// @Async: local background calculation\n// Kafka: durable ApplicationSubmitted integration event",'Choose the correct option for thumbnail generation and cross-service application events.', '@Async is local execution; Kafka is durable distributed event streaming.'),
 $lesson('What is Spring Batch?','Spring Batch models restartable jobs and steps with readers, processors, writers, chunk transactions, metadata and skip/retry policies.',"Job -> Step -> ItemReader -> ItemProcessor -> ItemWriter",'Design a chunked CSV job import that restarts after a failed chunk.', 'Spring Batch provides structured, restartable processing for large datasets.'),

 $lesson('What is unit testing?','A unit test exercises one class quickly and deterministically with dependencies replaced by fakes or mocks.',"@Test void publishesJob() {\n when(repository.save(any())).thenReturn(job);\n assertEquals(\"PUBLISHED\", service.publish(job).status());\n}",'Test service success, validation failure and repository failure without Spring context.', 'Unit testing isolates a small component and its behavior.'),
 $lesson('What is integration testing?','Integration tests verify collaboration between real framework components such as controller, service, repository and a test database.',"@DataJpaTest\nclass JobRepositoryTest {}",'Test a repository query using a disposable database rather than mocking JPA.', 'Integration tests exercise multiple real components together.'),
 $lesson('What is @SpringBootTest?','@SpringBootTest loads a complete Boot ApplicationContext and is suitable for broad integration tests, not every unit test.',"@SpringBootTest\n@ActiveProfiles(\"test\")\nclass ApplicationFlowTest {}",'Write one end-to-end service integration and compare runtime with a unit test.', '@SpringBootTest boots the application context for comprehensive integration testing.'),
 $lesson('What is MockMvc?','MockMvc exercises the MVC filter/controller stack without an external server and supports assertions on status, headers and JSON.',"mockMvc.perform(get(\"/api/jobs\"))\n .andExpect(status().isOk())\n .andExpect(jsonPath(\"$.content\").isArray());",'Test authentication, validation and a successful controller response.', 'MockMvc tests Spring MVC request handling without launching a real network server.'),
 $lesson('What is Mockito?','Mockito creates test doubles and verifies interactions. Prefer state/output assertions and mock only true boundaries.',"@Mock JobRepository repository;\n@InjectMocks JobService service;",'Mock the repository and verify save is not called when validation fails.', 'Mockito creates mocks and stubs for isolated Java tests.'),

 $lesson('What is Spring Boot Actuator?','Actuator exposes operational health, metrics, info and management capabilities. Secure sensitive endpoints and expose only what operations require.',"management.endpoints.web.exposure.include=health,info,prometheus\nmanagement.endpoint.health.probes.enabled=true",'Expose health and Prometheus metrics while keeping environment details private.', 'Actuator provides production observability and management endpoints.'),
 $lesson('Configuring different environments','Profiles and externalized configuration select environment-specific settings while keeping code identical.',"application.yml\napplication-dev.yml\napplication-prod.yml\nSPRING_PROFILES_ACTIVE=prod",'Use a production database URL from environment variables and a test container locally.', 'Profiles and external configuration separate environment settings from application code.'),
 $lesson('Managing secrets','Secrets must not be committed. Inject them through environment variables or a secret manager, restrict access and rotate them.',"spring.datasource.password=\${DB_PASSWORD}\nsecurity.jwt.secret=\${JWT_SECRET}",'Remove a test secret from configuration and load it through the environment.', 'Production secrets belong in controlled secret storage, not source control.'),
 $lesson('Dockerizing Spring Boot','Build an executable JAR and run it in a minimal non-root JRE image with health checks, pinned versions and layered caching.',"FROM eclipse-temurin:21-jre\nRUN useradd -r appuser\nCOPY target/app.jar /app.jar\nUSER appuser\nENTRYPOINT [\"java\",\"-jar\",\"/app.jar\"]",'Build the image, run it with an environment variable and test its health endpoint.', 'A hardened image packages the application runtime reproducibly and avoids root execution.'),
 $lesson('Deploying to Kubernetes','A Deployment manages replicas, a Service provides discovery, and Ingress or a load balancer exposes traffic; probes and resource limits support safe operation.',"Deployment -> Pods -> Service -> Ingress\nreadinessProbe: /actuator/health/readiness",'Define two replicas with readiness/liveness probes and CPU/memory requests.', 'Kubernetes Deployments, Services and ingress resources operate containerized Spring applications.'),

 $lesson('Handling millions of API requests','Scale horizontally behind load balancers, cache reads, index queries, paginate responses, rate limit callers and move slow work to queues.',"CDN -> Load Balancer -> Gateway -> App replicas -> Redis -> Database cluster",'Identify the bottleneck using metrics before selecting a scaling technique.', 'High scale requires measured horizontal scaling, caching, indexing, backpressure and asynchronous processing.'),
 $lesson('Preventing duplicate API requests','Use idempotency keys with stored outcomes, unique database constraints and transactional state changes; locks are a targeted last resort.',"Idempotency-Key: 123456\nUNIQUE(candidate_id, job_id)", 'Submit the same application concurrently and prove only one row is created.', 'Idempotency keys and database constraints make repeated requests safe.'),
 $lesson('Designing scalable job search','Keep the relational database authoritative and publish normalized jobs to Elasticsearch/OpenSearch for full-text search, facets and relevance.',"Ingestion -> PostgreSQL -> outbox event -> Search index -> Search API",'Index title, skills, location, experience and salary with filters and pagination.', 'A dedicated search index serves fast text queries while the database remains the source of truth.'),
 $lesson('Designing a job application system','The application service validates eligibility and uniqueness, stores status/audit history transactionally, then emits events for notifications and analytics.',"POST /jobs/{id}/applications\nUNIQUE(candidate_id,job_id)\nApplicationSubmitted -> broker",'Implement duplicate prevention and a status-history transition rule.', 'The system needs transactional persistence, duplicate protection, audit history and asynchronous side effects.'),
 $lesson('Complete production Spring Boot architecture','A production platform combines clients, gateway/security, domain services, broker, Redis, relational storage, search, observability and container orchestration.',"Client -> Gateway -> Security -> Services\nServices -> Kafka -> Notification/Analytics\nRedis + PostgreSQL + Elasticsearch\nPrometheus/Grafana + Docker/Kubernetes",'Draw failure boundaries, ownership and data flow for the complete job portal.', 'Production architecture integrates secure services, durable data, messaging, caching, search and observability.'),
];
