<?php
$number=0;
$q=function(string $question,string $answer)use(&$number){$number++;return compact('number','question','answer');};
return [
$q('What is SQL?','SQL (Structured Query Language) creates, reads, updates and deletes relational data; it also supports joins, aggregation, transactions and permissions.'),
$q('What are DDL, DML, DQL, DCL and TCL?',"DDL: CREATE, ALTER, DROP, TRUNCATE. DML: INSERT, UPDATE, DELETE. DQL: SELECT. DCL: GRANT, REVOKE. TCL: COMMIT, ROLLBACK, SAVEPOINT.\n\nSELECT * FROM employees;"),
$q('How do you retrieve all employees?',"SELECT *\nFROM employees;"),
$q('How do you retrieve specific columns?',"SELECT id, name, salary\nFROM employees;"),
$q('How do you find employees earning more than 50,000?',"SELECT * FROM employees\nWHERE salary > 50000;"),
$q('How do you find employees earning between 30,000 and 70,000?',"SELECT * FROM employees\nWHERE salary BETWEEN 30000 AND 70000;"),
$q('How do you find employees from specific departments?',"SELECT * FROM employees\nWHERE department_id IN (1, 2, 3);"),
$q("How do you find employees whose name starts with 'A'?", "SELECT * FROM employees WHERE name LIKE 'A%';"),
$q("How do you find names ending with 'n'?", "SELECT * FROM employees WHERE name LIKE '%n';"),
$q("How do you find names containing 'an'?", "SELECT * FROM employees WHERE name LIKE '%an%';"),
$q('How do you retrieve unique department IDs?',"SELECT DISTINCT department_id FROM employees;"),
$q('How do you sort employees by salary?',"SELECT * FROM employees ORDER BY salary ASC;\nSELECT * FROM employees ORDER BY salary DESC;"),
$q('How do you get the top 5 highest-paid employees?',"MySQL: SELECT * FROM employees ORDER BY salary DESC LIMIT 5;\nSQL Server: SELECT TOP 5 * FROM employees ORDER BY salary DESC;"),
$q('How do you count employees?',"SELECT COUNT(*) FROM employees;"),
$q('How do you find the maximum salary?',"SELECT MAX(salary) FROM employees;"),
$q('How do you find the minimum salary?',"SELECT MIN(salary) FROM employees;"),
$q('How do you find the average salary?',"SELECT AVG(salary) FROM employees;"),
$q('How do you find total salary?',"SELECT SUM(salary) FROM employees;"),
$q('Find the number of employees in each department.',"SELECT department_id, COUNT(*) AS employee_count FROM employees GROUP BY department_id;"),
$q('Find average salary of each department.',"SELECT department_id, AVG(salary) AS avg_salary FROM employees GROUP BY department_id;"),
$q('Find maximum salary in each department.',"SELECT department_id, MAX(salary) AS max_salary FROM employees GROUP BY department_id;"),
$q('Find departments having more than 5 employees.',"SELECT department_id, COUNT(*) AS employee_count FROM employees GROUP BY department_id HAVING COUNT(*) > 5;\n\nWHERE filters rows; HAVING filters groups."),
$q('Find departments whose average salary is greater than 60,000.',"SELECT department_id, AVG(salary) AS avg_salary FROM employees GROUP BY department_id HAVING AVG(salary) > 60000;"),
$q('How do you find employees without a manager?',"SELECT * FROM employees WHERE manager_id IS NULL;\nUse IS NULL, not = NULL."),
$q('How do you replace NULL salary with 0?',"SELECT name, COALESCE(salary, 0) AS salary FROM employees;"),
$q('Difference between NULL and 0?','NULL is unknown or missing; 0 is an actual numeric value.'),
$q('What is an INNER JOIN?',"Returns matches from both tables.\nSELECT e.name,d.department_name FROM employees e INNER JOIN departments d ON e.department_id=d.id;"),
$q('What is LEFT JOIN?',"Returns all left rows and right-side matches.\nSELECT e.name,d.department_name FROM employees e LEFT JOIN departments d ON e.department_id=d.id;"),
$q("Find employees who don't belong to any department.","SELECT e.* FROM employees e LEFT JOIN departments d ON e.department_id=d.id WHERE d.id IS NULL;"),
$q('What is RIGHT JOIN?',"Returns all right rows and left-side matches.\nSELECT e.name,d.department_name FROM employees e RIGHT JOIN departments d ON e.department_id=d.id;"),
$q('What is FULL OUTER JOIN?','Returns matches plus unmatched rows from both sides. MySQL simulates it with UNION.'),
$q('What is a SELF JOIN?',"Joins a table to itself.\nSELECT e.name employee,m.name manager FROM employees e LEFT JOIN employees m ON e.manager_id=m.id;"),
$q('What is CROSS JOIN?',"Produces a Cartesian product.\nSELECT * FROM employees CROSS JOIN departments;"),
$q('Find employees earning more than the average salary.',"SELECT * FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);"),
$q('Find the employee with the highest salary.',"SELECT * FROM employees WHERE salary = (SELECT MAX(salary) FROM employees);"),
$q('Find employees earning the maximum salary in their department.',"SELECT * FROM employees e WHERE salary=(SELECT MAX(e2.salary) FROM employees e2 WHERE e2.department_id=e.department_id);"),
$q('What is a correlated subquery?','A subquery that depends on values from the current outer-query row.'),
$q('Find the second-highest salary.',"SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees);"),
$q('Find the third-highest salary.',"SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees));"),
$q('Find the second-highest DISTINCT salary using DENSE_RANK.',"SELECT salary FROM (SELECT salary,DENSE_RANK() OVER(ORDER BY salary DESC) rnk FROM employees)x WHERE rnk=2;"),
$q('What is a window function?', "It calculates across related rows without collapsing them.\nSELECT name,salary,AVG(salary) OVER() company_avg FROM employees;"),
$q('Difference between RANK, DENSE_RANK and ROW_NUMBER?','ROW_NUMBER always increments. RANK shares ranks for ties and leaves gaps. DENSE_RANK shares ranks without gaps.'),
$q('Find highest-paid employee in each department.',"SELECT * FROM (SELECT e.*,ROW_NUMBER() OVER(PARTITION BY department_id ORDER BY salary DESC) rn FROM employees e)x WHERE rn=1;"),
$q('Find top 3 employees from each department.',"SELECT * FROM (SELECT e.*,ROW_NUMBER() OVER(PARTITION BY department_id ORDER BY salary DESC) rn FROM employees e)x WHERE rn<=3;"),
$q('Find second-highest salary in every department.',"SELECT * FROM (SELECT e.*,DENSE_RANK() OVER(PARTITION BY department_id ORDER BY salary DESC) rnk FROM employees e)x WHERE rnk=2;"),
$q('Calculate salary rank of every employee.',"SELECT name,salary,RANK() OVER(ORDER BY salary DESC) salary_rank FROM employees;"),
$q('Calculate department-wise salary rank.',"SELECT name,department_id,salary,RANK() OVER(PARTITION BY department_id ORDER BY salary DESC) dept_rank FROM employees;"),
$q('Find running total of salaries.',"SELECT name,salary,SUM(salary) OVER(ORDER BY id) running_total FROM employees;"),
$q('Find running total of orders.',"SELECT id,order_date,amount,SUM(amount) OVER(ORDER BY order_date,id) running_total FROM orders;"),
$q('Find previous employee salary.',"SELECT name,salary,LAG(salary) OVER(ORDER BY salary DESC) previous_salary FROM employees;"),
];
