<?php
namespace App\Http\Controllers;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
class AuthController extends Controller {
 public function registerForm(){return view('auth.register-v2',['stats'=>['jobs'=>0,'companies'=>0,'remote'=>0]]);}
 public function register(Request $r){$data=$r->validate(['name'=>'required|string|max:100','email'=>'required|email|max:190|unique:users','password'=>'required|string|min:8|confirmed','account_type'=>'nullable|in:student,employer']);$role=$data['account_type']??'student';$code=(string)random_int(100000,999999);DB::table('email_otps')->where('email',$data['email'])->whereNull('used_at')->delete();DB::table('email_otps')->insert(['email'=>$data['email'],'code_hash'=>Hash::make($code),'expires_at'=>now()->addMinutes(10),'created_at'=>now(),'updated_at'=>now()]);session(['pending_registration'=>['name'=>$data['name'],'email'=>$data['email'],'password'=>Hash::make($data['password']),'role'=>$role,'role_code'=>$role==='employer'?0:1],'dev_otp'=>app()->isLocal()?$code:null]);try{Mail::raw("Your EngineerLaunch verification code is {$code}. It expires in 10 minutes.",fn($m)=>$m->to($data['email'])->subject('Verify your EngineerLaunch account'));}catch(\Throwable $e){report($e);if(app()->isLocal()){return redirect()->route('otp.form')->with('mail_warning','Email delivery is unavailable because the local SMTP account could not authenticate. Use the development OTP shown below.');}DB::table('email_otps')->where('email',$data['email'])->whereNull('used_at')->delete();session()->forget(['pending_registration','dev_otp']);return back()->withInput($r->only('name','email','account_type'))->withErrors(['email'=>'We could not send your verification email. Please try again shortly or contact support.']);}return redirect()->route('otp.form');}
 public function otpForm(){abort_unless(session('pending_registration'),403);return view('auth.otp',['email'=>session('pending_registration.email'),'devOtp'=>app()->isLocal()?session('dev_otp'):null]);}
 public function verify(Request $r){$r->validate(['code'=>'required|digits:6']);$pending=session('pending_registration');abort_unless($pending,403);$otp=DB::table('email_otps')->where('email',$pending['email'])->whereNull('used_at')->where('expires_at','>',now())->latest()->first();if(!$otp||!Hash::check($r->code,$otp->code_hash))return back()->withErrors(['code'=>'The code is invalid or expired.']);DB::table('email_otps')->where('id',$otp->id)->update(['used_at'=>now()]);$pending['role']=config('services.admin_email')&&strcasecmp($pending['email'],config('services.admin_email'))===0?'admin':($pending['role']??'student');$pending['role_code']=$pending['role']==='admin'?2:($pending['role']==='employer'?0:1);$user=User::create($pending);if($user->role_code===1){$parts=preg_split('/\s+/',trim($user->name),2);$user->candidateProfile()->create(['first_name'=>$parts[0]??$user->name,'last_name'=>$parts[1]??null,'profile_completion'=>15]);}session()->forget('pending_registration');Auth::login($user);$r->session()->regenerate();return redirect($user->role==='employer'?'/employer':($user->role==='admin'?'/admin':'/dashboard'));}
 public function loginForm(){return view('auth.login');}
 public function employerLoginForm(){return view('auth.employer-login');}
 public function ownerLoginForm(){return view('auth.owner-login');}
 public function login(Request $r){$credentials=$r->validate(['email'=>'required|email','password'=>'required|string','expected_role'=>'nullable|in:student,employer,owner']);if(!Auth::attempt(['email'=>$credentials['email'],'password'=>$credentials['password']],$r->boolean('remember')))return back()->withErrors(['email'=>'Invalid credentials.'])->onlyInput('email');$user=$r->user();$matches=match($credentials['expected_role']??null){'employer'=>$user->role_code===0||$user->role==='employer','owner'=>$user->role_code===2||$user->role==='admin','student'=>$user->role_code===1||$user->role==='student',default=>true};if(!$matches){Auth::logout();return back()->withErrors(['email'=>'This account cannot use the selected login portal.'])->onlyInput('email');}$r->session()->regenerate();return redirect()->intended(($user->role_code===2||$user->role==='admin')?'/admin':(($user->role_code===0||$user->role==='employer')?'/employer':'/dashboard'));}
 public function logout(Request $r){Auth::logout();$r->session()->invalidate();$r->session()->regenerateToken();return redirect('/');}
}
