<?php
namespace App\Http\Controllers;
use App\Models\Job;use App\Models\JobApplication;use App\Services\SimilarJobRecommendationService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class CandidateJobController extends Controller
{
 public function show(Job $job,SimilarJobRecommendationService $recommendationsService){abort_unless($job->is_active&&$job->status==='published'&&$job->job_visibility==='public',404);$job->load(['company','skills','locations','screeningQuestions']);$job->incrementViews();$recommendations=session('success')?$recommendationsService->for($job,auth()->id(),15):collect();return view('jobs.show',compact('job','recommendations'));}
 public function apply(Request $r,Job $job){abort_unless($job->is_active&&$job->status==='published'&&$job->application_method==='portal',404);abort_if(in_array($r->user()->role,['employer','admin'],true)||in_array($r->user()->role_code,[0,2],true),403,'Employer accounts cannot apply.');$job->load('screeningQuestions');$rules=['cover_letter'=>'nullable|string|max:5000','answers'=>'nullable|array'];foreach($job->screeningQuestions as $question)$rules['answers.'.$question->id]=[$question->is_required?'required':'nullable','string','max:3000'];$data=$r->validate($rules);DB::transaction(function()use($r,$job,$data){$application=$job->applications()->where('user_id',$r->user()->id)->first();if($application&&$application->status!=='withdrawn')throw \Illuminate\Validation\ValidationException::withMessages(['application'=>'You have already applied for this job.']);$from=$application?->status;if($application)$application->update(['status'=>'applied','cover_letter'=>$data['cover_letter']??$application->cover_letter,'applied_at'=>now()]);else $application=$job->applications()->create(['user_id'=>$r->user()->id,'status'=>'applied','cover_letter'=>$data['cover_letter']??null,'applied_at'=>now()]);DB::table('application_status_history')->insert(['job_application_id'=>$application->id,'changed_by'=>$r->user()->id,'from_status'=>$from,'to_status'=>'applied','note'=>'Application submitted by candidate.','created_at'=>now()]);foreach(($data['answers']??[]) as $question=>$answer)DB::table('application_answers')->updateOrInsert(['job_application_id'=>$application->id,'question_id'=>$question],['answer'=>$answer]);});return back()->with('success','Application submitted successfully.');}
 public function withdraw(Request $r,JobApplication $application){abort_unless($application->user_id===$r->user()->id,403);abort_unless(in_array($application->status,['applied','viewed_by_recruiter','in_progress'],true),422,'This application can no longer be withdrawn.');DB::transaction(function()use($r,$application){$from=$application->status;$application->update(['status'=>'withdrawn']);DB::table('application_status_history')->insert(['job_application_id'=>$application->id,'changed_by'=>$r->user()->id,'from_status'=>$from,'to_status'=>'withdrawn','note'=>'Application withdrawn by candidate.','created_at'=>now()]);});return back()->with('success','Application withdrawn.');}
}
