<?php
namespace App\Http\Controllers;use App\Jobs\ParseCandidateResume;use App\Models\CandidateProfile;use App\Models\Resume;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;
class CandidateProfileController extends Controller
{
 public function dashboard(Request $r){$profile=$this->profile($r);$profile->load('resumes');$applications=$r->user()->applications()->with('job.company')->latest('applied_at')->paginate(10);return view('candidate.dashboard',compact('profile','applications'));}
 public function update(Request $r){$profile=$this->profile($r);$d=$r->validate(['first_name'=>'required|string|max:100','last_name'=>'nullable|string|max:100','phone'=>'nullable|string|max:30','address'=>'nullable|string|max:1000','headline'=>'nullable|string|max:255','bio'=>'nullable|string|max:3000','current_company'=>'nullable|string|max:150','current_designation'=>'nullable|string|max:150','experience_years'=>'nullable|integer|min:0|max:60','current_salary'=>'nullable|numeric|min:0','expected_salary'=>'nullable|numeric|min:0','notice_period'=>'nullable|string|max:50','location'=>'nullable|string|max:150','preferred_role'=>'nullable|string|max:150','education'=>'nullable|string|max:2000','avatar'=>'nullable|image|max:3072']);if($r->hasFile('avatar')){if($profile->avatar_path)Storage::disk('public')->delete($profile->avatar_path);$d['avatar_path']=$r->file('avatar')->store('candidate-avatars','public');}$d['profile_completion']=$this->completion($d+$profile->toArray());unset($d['avatar']);$profile->update($d);$r->user()->update(['name'=>trim($d['first_name'].' '.($d['last_name']??''))]);return back()->with('success','Profile updated.');}
 public function uploadResume(Request $r){$profile=$this->profile($r);$d=$r->validate(['resume'=>'required|file|mimes:pdf|max:5120']);$file=$r->file('resume');$path=$file->store('candidate-resumes','local');DB::transaction(function()use($profile,$file,$path,&$resume){$profile->resumes()->update(['is_primary'=>false]);$resume=Resume::create(['candidate_profile_id'=>$profile->id,'disk'=>'local','path'=>$path,'original_name'=>$file->getClientOriginalName(),'is_primary'=>true,'mime_type'=>$file->getMimeType(),'file_size'=>$file->getSize(),'parsing_status'=>'queued']);});ParseCandidateResume::dispatch($resume->id)->onQueue('resume-processing');return back()->with('success','Resume uploaded and queued for processing.');}
 private function profile(Request $r):CandidateProfile{abort_unless($r->user()->role_code===1||$r->user()->role==='student',403);$parts=preg_split('/\s+/',trim($r->user()->name),2);return CandidateProfile::firstOrCreate(['user_id'=>$r->user()->id],['first_name'=>$parts[0]??$r->user()->name,'last_name'=>$parts[1]??null,'profile_completion'=>15]);}
 private function completion(array $d):int{$fields=['first_name','last_name','phone','address','headline','bio','current_company','current_designation','experience_years','expected_salary','notice_period','location'];return (int)round(collect($fields)->filter(fn($f)=>filled($d[$f]??null))->count()/count($fields)*100);}
}
