<?php
namespace App\Http\Controllers;use App\Jobs\ParseCandidateResume;use App\Http\Requests\UpdateCandidateProfileRequest;use App\Services\GeographyService;use App\Models\CandidateProfile;use App\Models\Resume;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\ValidationException;use libphonenumber\PhoneNumberFormat;use libphonenumber\PhoneNumberUtil;
class CandidateProfileController extends Controller
{
 public function dashboard(Request $r,GeographyService $geo){$profile=$this->profile($r);$profile->load('resumes');$countries=$geo->countries();$delhiLocalities=config('delhi_localities',[]);$applications=$r->user()->applications()->with('job.company')->latest('applied_at')->paginate(50);$autoApply=DB::table('candidate_auto_apply_preferences')->where('user_id',$r->user()->id)->first();return view('candidate.dashboard-v2',compact('profile','applications','countries','delhiLocalities','autoApply'));}
 public function updateGuidance(Request $r){$profile=$this->profile($r);$data=$r->validate(['locality'=>'required|string|max:150','phone_confirmation'=>'required|in:yes,update','job_search_status'=>'required|in:actively_searching,preparing_for_interviews,appearing_for_interviews,received_job_offer,casually_exploring,not_looking']);if($data['phone_confirmation']==='update')return back()->withInput()->with('open_profile_editor',true)->withErrors(['phone'=>'Update and verify your current mobile number in the profile form.']);$profile->update(['locality'=>$data['locality'],'job_search_status'=>$data['job_search_status'],'phone_confirmed_at'=>now(),'guidance_completed_at'=>now()]);return back()->with('success','Your job preferences and location have been updated.');}
 public function update(UpdateCandidateProfileRequest $r){abort_unless($r->user()->role_code===1||$r->user()->role==='student',403);$d=$r->validated();$id=(int)($d['profile_id']??0);$existing=CandidateProfile::where('user_id',$r->user()->id)->first();if($id){$profile=CandidateProfile::where('id',$id)->where('user_id',$r->user()->id)->firstOrFail();}else{if($existing)throw ValidationException::withMessages(['profile_id'=>'Your candidate profile is already created. Use Edit Profile to update it.']);$profile=new CandidateProfile(['user_id'=>$r->user()->id]);}unset($d['profile_id']);if(filled($d['phone']??null)){$util=PhoneNumberUtil::getInstance();$d['phone']=$util->format($util->parse($d['phone'],strtoupper($d['phone_country_code']??'IN')),PhoneNumberFormat::E164);}$d['location']=collect([$d['city']??null,$d['state']??null,$d['country_code']??null])->filter()->implode(', ');if($r->hasFile('avatar')){if($profile->avatar_path)Storage::disk('public')->delete($profile->avatar_path);$d['avatar_path']=$r->file('avatar')->store('candidate-avatars','public');}$d['profile_completion']=$this->completion($d+$profile->toArray());unset($d['avatar']);DB::transaction(function()use($profile,$d,$r){$profile->fill($d);$profile->user_id=$r->user()->id;$profile->save();$r->user()->update(['name'=>trim($d['first_name'].' '.($d['last_name']??''))]);});return back()->with(['success'=>'Your profile has been saved successfully.','profile_saved'=>true]);}
 public function uploadResume(Request $r){$profile=$this->profile($r);$r->validate(['resume'=>'required|file|mimes:pdf|max:5120']);$file=$r->file('resume');$path=$file->store('candidate-resumes','local');DB::transaction(function()use($profile,$file,$path,&$resume){$profile->resumes()->update(['is_primary'=>false]);$resume=Resume::create(['candidate_profile_id'=>$profile->id,'disk'=>'local','path'=>$path,'original_name'=>$file->getClientOriginalName(),'is_primary'=>true,'mime_type'=>$file->getMimeType(),'file_size'=>$file->getSize(),'parsing_status'=>'queued']);});if(app()->isLocal()){ParseCandidateResume::dispatchSync($resume->id);return back()->with('success','Resume processed. Extracted details were added to empty profile fields; please review and save any corrections.');}ParseCandidateResume::dispatch($resume->id)->onQueue('resume-processing');return back()->with('success','Resume uploaded. Profile extraction is processing in the background.');}
 private function profile(Request $r):CandidateProfile{abort_unless($r->user()->role_code===1||$r->user()->role==='student',403);$parts=preg_split('/\s+/',trim($r->user()->name),2);return CandidateProfile::firstOrCreate(['user_id'=>$r->user()->id],['first_name'=>$parts[0]??$r->user()->name,'last_name'=>$parts[1]??null,'profile_completion'=>15]);}
 private function completion(array $d):int{$fields=['first_name','last_name','phone','address','headline','bio','current_company','current_designation','experience_years','expected_salary','notice_period','location'];return (int)round(collect($fields)->filter(fn($f)=>filled($d[$f]??null))->count()/count($fields)*100);}
}
