<?php
namespace App\Http\Controllers;
use App\Models\CandidateProfile;use Illuminate\Http\Request;
class CandidateAssistantController extends Controller{
 private array $steps=['first_name'=>['What is your first name?','text'],'last_name'=>['What is your last name?','text'],'education'=>['What is your highest qualification?','textarea'],'current_company'=>['What is your current or most recent company?','text'],'current_designation'=>['What is your current role or designation?','text'],'preferred_role'=>['Which role are you looking for?','text'],'experience_years'=>['How many years of experience do you have?','number'],'current_salary'=>['What is your current annual salary?','number'],'expected_salary'=>['What annual salary do you expect?','number'],'notice_period'=>['What is your notice period?','text'],'country_code'=>['What is your country code? For example IN, US, CA or AU.','text'],'state'=>['Which state or region do you live in?','text'],'city'=>['Which city do you live in?','text'],'address'=>['What is your address?','textarea'],'phone'=>['What is your phone number including country code?','tel'],'headline'=>['Write a short professional headline.','text']];
 public function setup(Request $r){$this->candidate($r);return view('candidate.setup');}
 public function show(Request $r){$profile=$this->candidate($r);$answers=session('candidate_assistant.answers',[]);$keys=array_keys($this->steps);$index=min((int)session('candidate_assistant.index',0),count($keys));return view('candidate.assistant',['profile'=>$profile,'answers'=>$answers,'steps'=>$this->steps,'keys'=>$keys,'index'=>$index,'review'=>$index>=count($keys)]);}
 public function answer(Request $r){$this->candidate($r);$keys=array_keys($this->steps);$index=(int)session('candidate_assistant.index',0);abort_if($index>=count($keys),422);$key=$keys[$index];$rules=in_array($key,['experience_years'],true)?['required','integer','min:0','max:60']:(in_array($key,['current_salary','expected_salary'],true)?['nullable','numeric','min:0']:['nullable','string','max:2000']);$value=$r->validate(['answer'=>$rules])['answer']??null;$answers=session('candidate_assistant.answers',[]);$answers[$key]=$value;session(['candidate_assistant.answers'=>$answers,'candidate_assistant.index'=>$index+1]);return redirect()->route('candidate.assistant');}
 public function back(Request $r){$this->candidate($r);session(['candidate_assistant.index'=>max(0,(int)session('candidate_assistant.index',0)-1)]);return redirect()->route('candidate.assistant');}
 public function complete(Request $r){$profile=$this->candidate($r);$answers=session('candidate_assistant.answers',[]);abort_if(count($answers)<count($this->steps),422,'Complete all assistant questions first.');$answers['country_code']=strtoupper(substr($answers['country_code']??'',0,2));$answers['location']=collect([$answers['city']??null,$answers['state']??null,$answers['country_code']??null])->filter()->implode(', ');$answers['profile_completion']=$this->completion($answers+$profile->toArray());$profile->update($answers);$r->user()->update(['name'=>trim(($answers['first_name']??'').' '.($answers['last_name']??''))]);session()->forget('candidate_assistant');return redirect()->route('dashboard')->with('success','Guided profile completed. Please review the saved information.');}
 public function reset(Request $r){$this->candidate($r);session()->forget('candidate_assistant');return redirect()->route('candidate.assistant');}
 private function candidate(Request $r):CandidateProfile{abort_unless($r->user()&&($r->user()->role_code===1||$r->user()->role==='student'),403);return CandidateProfile::firstOrCreate(['user_id'=>$r->user()->id],['first_name'=>$r->user()->name,'profile_completion'=>10]);}
 private function completion(array $d):int{$fields=array_keys($this->steps);return (int)round(collect($fields)->filter(fn($f)=>filled($d[$f]??null))->count()/count($fields)*100);}
}
