<?php
namespace App\Http\Controllers;
use App\Http\Requests\StoreEmployerJobRequest;use App\Models\Company;use App\Models\EmployerProfile;use App\Models\Job;use App\Models\JobApplication;use App\Models\Skill;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class EmployerController extends Controller
{
 public function dashboard(Request $r){$profile=$r->user()->employerProfile()->with('company')->first();$base=$r->user()->postedJobs();$mine=fn()=>JobApplication::whereHas('job',fn($q)=>$q->where('employer_id',$r->user()->id));$stats=['active'=>(clone $base)->where('status','published')->count(),'applications'=>$mine()->count(),'new'=>$mine()->where('status','applied')->count(),'shortlisted'=>$mine()->where('status','shortlisted')->count(),'interviews'=>$mine()->where('status','interview_scheduled')->count(),'closed'=>(clone $base)->where('status','closed')->count()];$jobs=$base->withCount(['applications','applications as shortlisted_count'=>fn($q)=>$q->where('status','shortlisted')])->latest()->paginate(12);$recentApplicants=$mine()->with(['candidate','job'])->latest('applied_at')->take(6)->get();return view('employer.dashboard-v2',compact('profile','jobs','stats','recentApplicants'));}
 public function company(Request $r){$d=$r->validate(['name'=>'required|string|max:150','company_type'=>'required|in:company,recruitment_agency,consultancy,staffing_agency','website'=>'nullable|url|max:255','country'=>'required|string|max:100','designation'=>'nullable|string|max:100','phone'=>'nullable|string|max:30']);DB::transaction(function()use($r,$d){$c=Company::firstOrCreate(['slug'=>Str::slug($d['name'])],['name'=>$d['name'],'company_type'=>$d['company_type'],'website'=>$d['website']??null,'country'=>$d['country'],'is_active'=>true]);EmployerProfile::updateOrCreate(['user_id'=>$r->user()->id],['company_id'=>$c->id,'designation'=>$d['designation']??null,'phone'=>$d['phone']??null]);});return back()->with('success','Company profile saved.');}
 public function create(){return view('employer.job-form-v2',['job'=>new Job,'options'=>config('recruitment')]);}
 public function store(StoreEmployerJobRequest $r){$job=$this->save(new Job,$r);return $r->input('action')==='draft'?redirect()->route('employer.jobs.edit',$job)->with('success','Draft saved.'):redirect()->route('employer.dashboard')->with('success','Job published successfully.');}
 public function edit(Request $r,Job $job){$this->own($r,$job);$job->load(['skills','locations','screeningQuestions']);return view('employer.job-form-v2',['job'=>$job,'options'=>config('recruitment')]);}
 public function update(StoreEmployerJobRequest $r,Job $job){$this->own($r,$job);$this->save($job,$r);return redirect()->route('employer.dashboard')->with('success',$r->input('action')==='draft'?'Draft saved.':'Job published successfully.');}
 public function status(Request $r,Job $job,string $status){$this->own($r,$job);abort_unless(in_array($status,['published','paused','closed'],true),422);$from=$job->status;$job->update(['status'=>$status,'is_active'=>$status==='published','published_at'=>$status==='published'?($job->published_at??now()):$job->published_at,'expires_at'=>$status==='closed'?now():$job->expires_at]);DB::table('job_status_history')->insert(['job_id'=>$job->id,'changed_by'=>$r->user()->id,'from_status'=>$from,'to_status'=>$status,'created_at'=>now()]);return back()->with('success','Job status updated.');}
 public function destroy(Request $r,Job $job){$this->own($r,$job);abort_unless(in_array($job->status,['draft','closed'],true),422,'Only draft or closed jobs can be deleted.');DB::transaction(function()use($r,$job){DB::table('deleted_job_events')->insert(['job_id'=>$job->id,'employer_id'=>$r->user()->id,'company_id'=>$job->company_id,'job_title'=>$job->title,'deleted_at'=>now()]);$job->delete();});return back()->with('success','Job deleted and recorded in the owner audit log.');}
 public function duplicate(Request $r,Job $job){$this->own($r,$job);$copy=$job->replicate(['slug','status','published_at']);$copy->title.=' (Copy)';$copy->slug=Str::slug($copy->title).'-'.Str::lower(Str::random(7));$copy->status='draft';$copy->is_active=false;$copy->save();foreach($job->skills as $skill)$copy->skills()->attach($skill->id,['importance'=>$skill->pivot->importance]);return redirect()->route('employer.jobs.edit',$copy)->with('success','Job duplicated as a draft.');}
 public function applicants(Request $r,Job $job){$this->own($r,$job);$applications=$job->applications()->with('candidate.candidateProfile')->latest('applied_at')->paginate(20);return view('employer.applicants-v2',compact('job','applications'));}
 public function applicationStatus(Request $r,JobApplication $application){$this->own($r,$application->job);$d=$r->validate(['status'=>'required|in:new,verified,in_process,processed,approved,rejected,job_offer_received,no_offer']);$from=$application->status;$application->update($d);DB::table('application_status_history')->insert(['job_application_id'=>$application->id,'changed_by'=>$r->user()->id,'from_status'=>$from,'to_status'=>$d['status'],'created_at'=>now()]);return back()->with('success','Application status updated.');}
 private function own(Request $r,Job $j){abort_unless($r->user()->role==='admin'||$j->employer_id===$r->user()->id,403);}
 private function save(Job $j,StoreEmployerJobRequest $r):Job{$p=$r->user()->employerProfile;abort_unless($p,422,'Create a company profile first.');return DB::transaction(function()use($j,$r,$p){$d=$r->validated();$pub=$d['action']==='publish';$j->fill(array_merge($d,['company_id'=>$p->company_id,'employer_id'=>$r->user()->id,'slug'=>$j->slug?:Str::slug($d['title']??'draft').'-'.Str::lower(Str::random(7)),'status'=>$pub?'published':'draft','job_visibility'=>$pub?($d['job_visibility']??'public'):'draft','posting_source'=>'official_company','source'=>'employer','is_active'=>$pub,'posted_at'=>$pub?now():$j->posted_at,'published_at'=>$pub?now():null]));$j->save();$j->skills()->detach();foreach(['required_skills'=>'required','mandatory_skills'=>'mandatory','good_to_have_skills'=>'preferred'] as $field=>$importance)foreach($this->csv($d[$field]??'') as $name){$skill=Skill::firstOrCreate(['slug'=>Str::slug($name)],['name'=>$name]);$j->skills()->attach($skill->id,['importance'=>$importance]);}$j->locations()->delete();foreach(($d['locations']??[]) as $loc)if(array_filter($loc))$j->locations()->create($loc);if(!$j->locations()->exists()&&($d['country']??null))$j->locations()->create(['country'=>$d['country'],'state'=>$d['state']??null,'city'=>$d['location']??null]);DB::table('job_benefits')->where('job_id',$j->id)->delete();foreach(($d['benefits']??[]) as $name)DB::table('job_benefits')->insert(['job_id'=>$j->id,'name'=>$name]);$j->screeningQuestions()->delete();foreach(($d['questions']??[]) as $i=>$q)if(!empty($q['question']))$j->screeningQuestions()->create(['question'=>$q['question'],'type'=>$q['type']??'text','is_required'=>(bool)($q['required']??false),'sort_order'=>$i]);return $j;});}
 private function csv(string $value){return collect(preg_split('/[,\n]+/',$value))->map(fn($v)=>trim($v))->filter()->unique()->take(50);}
}
