<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title', config('platform.name'))</title><style>:root{--ink:#10213e;--blue:#2563eb;--blue-dark:#1d4ed8;--blue-soft:#eff6ff;--blue-soft-2:#e7f0ff;--muted:#667085;--line:#cfe0f7;--bg:#f3f8ff}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:linear-gradient(180deg,#f8fbff 0,#eef6ff 100%);font-family:Inter,system-ui,sans-serif}.page{min-height:calc(100vh - 140px)}.container{width:min(1100px,calc(100% - 32px));margin:auto}.hero-band{padding:42px 0;color:#fff;background:linear-gradient(120deg,#10213e,#1d4ed8)}.section{padding:45px 0}.panel,.card,article{border-color:var(--line)!important}.panel{padding:28px;border:1px solid var(--line);border-radius:16px;background:linear-gradient(145deg,#fff,#f5f9ff);box-shadow:0 10px 28px rgba(37,99,235,.07)}input:not([type=checkbox]):not([type=radio]),select,textarea{border-color:#bdd2ef!important;background-color:#fff!important}input:focus,select:focus,textarea:focus{border-color:#60a5fa!important;box-shadow:0 0 0 3px rgba(96,165,250,.16)!important;outline:0}.btn-primary,.primary{background:linear-gradient(135deg,var(--blue),#3b82f6)!important;border-color:var(--blue)!important;color:#fff!important;box-shadow:0 6px 16px rgba(37,99,235,.18)}.btn-primary:hover,.primary:hover{background:linear-gradient(135deg,var(--blue-dark),var(--blue))!important;transform:translateY(-1px)}.alert-info{background:#e8f4ff!important;border-color:#a9d5ff!important;color:#075985!important}.student-reward-badge{margin-left:8px;padding:5px 9px;border-radius:999px;background:#fff5cc;color:#8a5700;font-size:12px;font-weight:800}</style>@stack('styles')</head><body>@include('partials.header')<main class="page">@yield('content')</main>@include('partials.footer')
@auth
@if((auth()->user()->role_code ?? null) === 1 || (auth()->user()->role ?? null) === 'student')
<script>
document.addEventListener('DOMContentLoaded',()=>{const name=document.querySelector('.candidate-nav b');if(!name)return;const badge=document.createElement('span');badge.className='student-reward-badge';badge.dataset.rewardBadge='1';badge.textContent='⭐ {{(int)auth()->user()->total_stars}} · {{(int)auth()->user()->total_points}} pts';name.insertAdjacentElement('afterend',badge)});
document.addEventListener('click',async event=>{const option=event.target.closest('.quiz .option');if(!option)return;const quiz=option.closest('.quiz');const options=Array.from(quiz.querySelectorAll('.option'));const path=location.pathname.split('/').filter(Boolean);if(path[0]!=='learn'||path.length<3)return;option.disabled=true;try{const response=await fetch('{{route('learning.quiz.store')}}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{csrf_token()}}'},body:JSON.stringify({track:path[1],module:path[2],lesson:Number(quiz.dataset.lesson),selected_option:options.indexOf(option)})});const result=await response.json();if(!response.ok)throw new Error(result.message||'The answer could not be checked.');option.classList.add(result.correct?'correct':'wrong');const badge=document.querySelector('[data-reward-badge]');if(badge)badge.textContent=`⭐ ${result.stars} · ${result.points} pts`;if(result.premium_activated)alert('Premium unlocked for 10 days. Review and approve matched jobs before any application is submitted.')}catch(error){alert(error.message);option.disabled=false}});
</script>
@endif
@endauth
@stack('scripts')</body></html>
