<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title', config('platform.name'))</title><style>:root{--ink:#10213e;--blue:#2563eb;--muted:#667085;--line:#e4e9f2;--bg:#f6f8fc}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--bg);font-family:Inter,system-ui,sans-serif}.page{min-height:calc(100vh - 140px)}.container{width:min(1100px,calc(100% - 32px));margin:auto}.hero-band{padding:42px 0;color:#fff;background:linear-gradient(120deg,#10213e,#1d4ed8)}.section{padding:45px 0}.panel{padding:28px;border:1px solid var(--line);border-radius:16px;background:#fff}.student-reward-badge{margin-left:8px;padding:5px 9px;border-radius:999px;background:#fff5cc;color:#8a5700;font-size:12px;font-weight:800}</style>@stack('styles')</head><body>@include('partials.header')<main class="page">@yield('content')</main>@include('partials.footer')
@auth
@if((auth()->user()->role_code ?? null) === 1 || (auth()->user()->role ?? null) === 'student')
<script>
document.addEventListener('DOMContentLoaded',()=>{const name=document.querySelector('.candidate-nav b');if(!name)return;const badge=document.createElement('span');badge.className='student-reward-badge';badge.dataset.rewardBadge='1';badge.textContent='⭐ {{(int)auth()->user()->total_stars}} · {{(int)auth()->user()->total_points}} pts';name.insertAdjacentElement('afterend',badge)});
document.addEventListener('click',async event=>{const option=event.target.closest('.quiz .option');if(!option)return;const quiz=option.closest('.quiz');const options=Array.from(quiz.querySelectorAll('.option'));const path=location.pathname.split('/').filter(Boolean);if(path[0]!=='learn'||path.length<3)return;option.disabled=true;try{const response=await fetch('{{route('learning.quiz.store')}}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{csrf_token()}}'},body:JSON.stringify({track:path[1],module:path[2],lesson:Number(quiz.dataset.lesson),selected_option:options.indexOf(option)})});const result=await response.json();if(!response.ok)throw new Error(result.message||'The answer could not be checked.');option.classList.add(result.correct?'correct':'wrong');const badge=document.querySelector('[data-reward-badge]');if(badge)badge.textContent=`⭐ ${result.stars} · ${result.points} pts`;if(result.premium_activated)alert('Premium unlocked for 10 days. Review and approve matched jobs before any application is submitted.')}catch(error){alert(error.message);option.disabled=false}});
</script>
@endif
@endauth
@stack('scripts')</body></html>
